feat: cluster rate limit by client ip
alibaba/higress pull request #1002
Opened 2024-05-26 01:10 UTC by hanxiantao

### Ⅰ. Describe what this PR did
支持根据客户端IP来进行集群限流

### Ⅱ. Does this pull request fix one issue?

feat [#851](https://github.com/alibaba/higress/issues/851)

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
wasmplugin.yam：

根据请求头X-Forwarded-For限流

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    ip_source_type: header
    rule_name: test
    redis_service_name: redis
    redis_service_host: redis
    redis_service_port: 80
    redis_service_source: ip
    show_limit_quota_header: true
    limit_keys:
      - key: 1.1.1.1
        query_per_day: 10
      - key: 1.1.1.0/24
        query_per_day: 100
      - key: 0.0.0.0/0
        query_per_day: 1000
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.40
  imagePullSecret: aliyun
```

**命中1.1.1.1规则：**

```
curl --location --request GET 'http://localhost:8082/test' \
--header 'Host: www.test.com' \
--header 'X-Forwarded-For: 1.1.1.1'
```

连续请求5次：

![case1](https://github.com/alibaba/higress/assets/45159482/7919d6cf-9fe7-42c7-a9aa-3e691b48938c)

响应头中`X-RateLimit-Limit`（限制的总请求数）为10和`X-RateLimit-Remaining`（剩余还可以发送的请求数）为5

redis中数据：

![case1 redis](https://github.com/alibaba/higress/assets/45159482/843089ff-e7dc-4a01-aea2-972062c8684a)

继续请求触发限流后响应如下：

![case触发限流](https://github.com/alibaba/higress/assets/45159482/2c51e673-1a60-4382-a3d4-d2f8b05b4f5d)

**命中1.1.1.0/24规则：**

```
curl --location --request GET 'http://localhost:8082/test' \
--header 'Host: www.test.com' \
--header 'X-Forwarded-For: 1.1.1.2'
```

连续请求3次：

![case2](https://github.com/alibaba/higress/assets/45159482/468a4d96-2cec-4c86-85b0-461bb1fff288)

响应头中`X-RateLimit-Limit`（限制的总请求数）为100和`X-RateLimit-Remaining`（剩余还可以发送的请求数）为97

redis中数据：	

![case2 redis](https://github.com/alibaba/higress/assets/45159482/df019130-d7d3-436f-be96-03dc7b57e026)

**命中0.0.0.0/0规则：**

```
curl --location --request GET 'http://localhost:8082/test' \
--header 'Host: www.test.com' \
--header 'X-Forwarded-For: 172.20.91.5'
```

连续请求2次：

![case3](https://github.com/alibaba/higress/assets/45159482/e56aa45c-c2eb-4ca7-b4d0-7c97e8a5acf2)

响应头中`X-RateLimit-Limit`（限制的总请求数）为1000和`X-RateLimit-Remaining`（剩余还可以发送的请求数）为998

redis中数据：	

![case3 redis](https://github.com/alibaba/higress/assets/45159482/7b73986e-230b-4267-a2e9-3ef2140b9700)

2024-05-27 03:53 UTC, johnlanni requested changes

2024-05-27 03:53 UTC, johnlanni commented on plugins/wasm-go/extensions/key-cluster-rate-limit/README.md
> +| ip_source_type          | string | 否 | origin-source | 可选值：1. `origin-source`：对端socket ip 2. `header`：通过header获取 |
建议用这样的的配置方式来支持 ip 粒度限流：

```yaml
# 和 limit_by_header、limit_by_param 对称，这三个只能选一个配置
limit_by_per_ip: from-header-x-forwarded-for
limit_keys:
# 精确ip
- key: 1.1.1.1
  query_per_second: 10
# ip段，符合这个ip段的ip，每个ip 100qps
- key: 1.1.1.0/24
  query_per_second: 100
# 兜底用，即默认每个 ip 1000qps
- key: 0.0.0.0/0
  query_per_second: 1000
```

2024-05-27 03:53 UTC, johnlanni commented on plugins/wasm-go/extensions/key-cluster-rate-limit/README.md
> +| redis_service_source | string | 必填   | -          | 类型为固定ip或者DNS，输入redis服务的注册来源                             |
redis 相关配置可以收敛一个子配置项，例如:

```yaml
redis:
  service_source: xxx  （默认值 dns）
  service_name: xxx
  service_port: xxx (默认值 6379)
```

2024-05-27 05:10 UTC, hanxiantao commented on plugins/wasm-go/extensions/key-cluster-rate-limit/README.md
> +| ip_source_type          | string | 否 | origin-source | 可选值：1. `origin-source`：对端socket ip 2. `header`：通过header获取 |
> 建议用这样的的配置方式来支持 ip 粒度限流：
> 
> ```yaml
> # 和 limit_by_header、limit_by_param 对称，这三个只能选一个配置
> limit_by_per_ip: from-header-x-forwarded-for
> limit_keys:
> # 精确ip
> - key: 1.1.1.1
>   query_per_second: 10
> # ip段，符合这个ip段的ip，每个ip 100qps
> - key: 1.1.1.0/24
>   query_per_second: 100
> # 兜底用，即默认每个 ip 1000qps
> - key: 0.0.0.0/0
>   query_per_second: 1000
> ```

limit_by_per_ip这个应该是要支持直接获取对端socket ip和从请求头获取。如果是从header可以配置成limit_by_per_ip: from-header-对应的header名；如果是origin-source这种取对端socket ip，可以配置成limit_by_per_ip: from-origin-source，这个您看ok吗？

2024-05-31 12:21 UTC, hanxiantao commented on plugins/wasm-go/extensions/key-cluster-rate-limit/README.md
> +| ip_source_type          | string | 否 | origin-source | 可选值：1. `origin-source`：对端socket ip 2. `header`：通过header获取 |
@johnlanni 集群限流的场景需要一个rule_name，来区分不同的限流规则，不然只通过limit_key很难区分，比如两个相同的limit_key在不同的path使用这种场景

2024-06-03 01:47 UTC, johnlanni commented on plugins/wasm-go/extensions/key-cluster-rate-limit/README.md
> +| ip_source_type          | string | 否 | origin-source | 可选值：1. `origin-source`：对端socket ip 2. `header`：通过header获取 |
@hanxiantao 嗯 是的，可以增加一个rule name字段

2024-06-03 04:23 UTC, hanxiantao commented
@johnlanni  代码已调整，麻烦再帮忙review下

2024-06-06 02:28 UTC, johnlanni requested changes

2024-06-06 02:28 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| service_source | string | 必填 | -      | 类型为固定ip或者DNS，输入redis服务的注册来源    |
https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-cache/main.go

麻烦参考下这里的redis配置解析和client初始化逻辑，使用FQDNCluster，简化用户的配置方式

2024-06-06 02:28 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| service_domain | string | 必填 | -      | 当类型为DNS时必须填写，输入redis服务的domain    |
其实redis 不需要设置domain

2024-06-06 02:28 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +	# 精确ip
这里有一段空白符

2024-06-06 02:30 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| service_source | string | 必填 | -      | 类型为固定ip或者DNS，输入redis服务的注册来源    |
> https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-cache/main.go
> 
> 麻烦参考下这里的redis配置解析和client初始化逻辑，使用FQDNCluster，简化用户的配置方式

好的，这里我再调整下

2024-06-06 02:36 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
可以考虑加一个 limit_by_consumer, 现在通过 x-mse-consumer 这个request header可以取出 consumer 的名字

2024-06-06 02:42 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
> 可以考虑加一个 limit_by_consumer, 现在通过 x-mse-consumer 这个request header可以取出 consumer 的名字

这个应该是要配合认证的插件一起使用对吧

2024-06-06 02:50 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
是的，如果用户开了 key-auth 等认证插件，就可以配合基于 consumer 做流控了，在openapi场景下挺有用的

2024-06-06 02:51 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
> 是的，如果用户开了 key-auth 等认证插件，就可以配合基于 consumer 做流控了，在openapi场景下挺有用的

好的

2024-06-06 03:06 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| redis                   | object          | 是                                                           | -                 | redis相关配置                                                |
可以进一步扩展一下，类似 per ip 这种，用于不可枚举场景的限流：
limit_by_per_header
limit_by_per_param

key 可以支持配置一个正则表达式，符合正则匹配的进行限制

2024-06-06 09:45 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| redis                   | object          | 是                                                           | -                 | redis相关配置                                                |
> 可以进一步扩展一下，类似 per ip 这种，用于不可枚举场景的限流： limit_by_per_header limit_by_per_param
> 
> key 可以支持配置一个正则表达式，符合正则匹配的进行限制
key以regexp-开头的标识根据正则表达式匹配，示例如下：
rule_name: limit_by_param_x-ca-key
limit_by_header: x-ca-key
limit_keys:
- key: 102234
  query_per_second: 10
# 大于104000时触发限流
- key: regexp-1\d{5,}
  query_per_hour: 10

2024-06-11 05:52 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
limit_by_consumer 更好一些，目前通过header传递consumer信息的方式后续可能会调整，有了limit_by_consumer，用户就不感知这个调整

2024-06-11 05:54 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| redis                   | object          | 是                                                           | -                 | redis相关配置                                                |
regexp:\d+

用冒号分隔看上去自然一些

2024-06-11 09:39 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| limit_by_header         | string          | 否，`limit_by_header`,`limit_by_param`,`limit_by_per_ip` 中选填一项 | -                 | 配置获取限流键值的来源 http 请求头名称                       |
> limit_by_consumer 更好一些，目前通过header传递consumer信息的方式后续可能会调整，有了limit_by_consumer，用户就不感知这个调整

好的，limit_by_consumer实现的时候也会和limit_by_per_header、limit_by_per_param一样支持配置一个正则表达式

2024-06-12 06:51 UTC, johnlanni approved these changes
LGTM

2024-06-12 06:51 UTC, merged