add ai_statistics plugin for ai observability
alibaba/higress pull request #1011
Opened 2024-05-29 03:04 UTC by rinfx

插件提供LLM的可观测基础能力，用于构建metric、log等相关可观测能力

2024-05-29 11:44 UTC, johnlanni commented
cc @CH3CHO

2024-05-29 14:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/go.mod
> +	github.com/higress-group/proxy-wasm-go-sdk v0.0.0-20240327114451-d6b7174a84fc
这个要不要 replace 一下？

2024-05-29 14:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +	if !gjson.GetBytes(body, "model").Exists() {
把 `gjson.GetBytes(body, "model")` 和 `gjson.GetBytes(body, "stream")` 这些调用的返回值缓存下来再做判断效率更高

2024-05-29 14:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +	config.gptRegExp, _ = regexp.Compile("gpt.*")
还有一些其他的模型用的也是 OpenAI 的接口契约，这里是否需要支持一下配置？另外，用前缀匹配是否效率更高？

2024-06-17 02:57 UTC, johnlanni requested changes

2024-06-17 02:57 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-statistics/README.md
> +## Metrics
增加一下配置字段说明，说明一下如果要支持更多模型的统计，需要配合AI-Proxy插件使用，并说明下插件生效的阶段配置方式，AI-Stats插件的执行阶段要在AI-Proxy插件之前

2024-06-17 02:57 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +		if x_dashscope_sse != "enable" && accept != "text/event-stream" {
千问通过请求header来判断流式开启会有问题，因为 accept可能出现多个值，应该通过响应header来判断当前响应是否是流式的。

2024-06-18 09:52 UTC, johnlanni approved these changes
LGTM

2024-06-18 09:53 UTC, merged