add plugin: ai-token-consumer
alibaba/higress pull request #1016
Opened 2024-05-30 07:46 UTC by rinfx

消费者token限额

2024-06-02 08:56 UTC, 2456868764 commented
这里限制额度是否可以增加 1. 日期维度，比如每天，每周，每月，每年，和 总共等 2. token维度，可以不同token有不同限额 @johnlanni @rinfx

2024-06-02 09:07 UTC, 2456868764 commented
另外是否加 日志插件，记录日志写入网关日志中，或者写入到Redis，可以用于企业审计用？ @johnlanni

2024-06-03 01:58 UTC, johnlanni commented
@2456868764 这个插件就是做这个事情的：https://github.com/alibaba/higress/pull/1011


> 另外是否加 日志插件，记录日志写入网关日志中，或者写入到Redis，可以用于企业审计用？ @johnlanni

2024-06-17 02:58 UTC, johnlanni requested changes

2024-06-17 02:58 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-token-consumer/main.go
> +	case "ip":
对接redis统一使用FQDNCluster吧

2024-06-18 03:32 UTC, closed without merging