opt: optimize redundant code
alibaba/higress pull request #103
Opened 2022-12-07 07:32 UTC by Charlie17Li

Signed-off-by: charlie <qianglin98@qq.com>

### Ⅰ. Describe what this PR did

opt: optimize redundant code

### Ⅱ. Does this pull request fix one issue?

fixes #91 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-12-07 07:42 UTC, johnlanni commented
Could you add some UT for it？

2022-12-07 07:55 UTC, Charlie17Li commented
> Could you add some UT for it？

ok

2022-12-07 14:05 UTC, johnlanni requested changes

2022-12-08 07:49 UTC, Charlie17Li commented on pkg/ingress/mcp/generator_test.go
> +func Test_generate(t *testing.T) {
done.

2023-02-01 08:38 UTC, johnlanni approved these changes

2023-02-01 08:40 UTC, merged