feat: cluster key rate limit enhancement
alibaba/higress pull request #1036
Opened 2024-06-13 01:08 UTC by hanxiantao

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it
**1）、识别请求参数 apikey，进行区别限流**

wasmplugin.yam：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    rule_name: default_limit_by_param_apikey
    limit_by_param: apikey
    limit_keys:
    - key: 9a342114-ba8a-11ec-b1bf-00163e1250b5
      query_per_minute: 10
    - key: a6a6d7f2-ba8a-11ec-bec2-00163e1250b5
      query_per_hour: 100
    - key: "regexp:^b.*"
      query_per_hour: 1000
    - key: "*"
      query_per_hour: 10000
    redis:
      service_name: redis.static
    show_limit_quota_header: true
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.60
  imagePullSecret: aliyun
```

**1）根据第一个apikey进行限流**

一分钟内请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test?apikey=9a342114-ba8a-11ec-b1bf-00163e1250b5' \
-H 'Host: www.test.com'
```
![根据请求参数限流](https://github.com/alibaba/higress/assets/45159482/eb3fd98d-65fb-4814-b34f-aa1e65137b2d)

响应头中x-ratelimit-limit为10（限制的总请求数），x-ratelimit-remaining为7（剩余还可以发送的请求数）

触发限流后：

![根据请求参数限流触发限流后](https://github.com/alibaba/higress/assets/45159482/33b2f2a3-4b3a-4e57-94c2-325e53917739)

**2）根据第二个apikey限流**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test?apikey=a6a6d7f2-ba8a-11ec-bec2-00163e1250b5' \
-H 'Host: www.test.com'
```
![根据请求参数限流2](https://github.com/alibaba/higress/assets/45159482/e52f4167-0607-4ee5-b041-a714a83d315b)

redis中数据：

![根据请求参数限流 redis数据](https://github.com/alibaba/higress/assets/45159482/c2be6304-8a4c-46de-87b5-ebf5f6c1fdbc)

**3）正则表达式（规则为以b开头的任意字符串）**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test?apikey=b1234test' \
-H 'Host: www.test.com'
```
![根据请求参数限流3](https://github.com/alibaba/higress/assets/45159482/ff70bceb-8d30-4825-8f6a-54ebd97e25b7)

redis中数据：
![根据请求参数限流 redis数据2](https://github.com/alibaba/higress/assets/45159482/fad116e5-bf25-4db2-94c3-a0727f81189f)

**4）***

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test?apikey=20240613' \
-H 'Host: www.test.com'
```

![根据请求参数限流4](https://github.com/alibaba/higress/assets/45159482/a3367032-1617-40d3-bd26-2a5b87403417)

redis中数据：

![根据请求参数限流 redis数据3](https://github.com/alibaba/higress/assets/45159482/68ff91c1-c1e9-40d1-b1c6-466468e55678)

**2）、识别请求头 x-ca-key，进行区别限流**

wasmplugin.yam：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    rule_name: default_limit_by_param_x-ca-key
    limit_by_header: x-ca-key
    limit_keys:
    - key: 102234
      query_per_minute: 10
    - key: "regexp:^c.*"
      query_per_hour: 1000
    - key: "*"
      query_per_hour: 10000      
    redis:
      service_name: redis.static
    show_limit_quota_header: true
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.60
  imagePullSecret: aliyun
```

**1）根据第一个x-ca-key限流**

一分钟内请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-ca-key: 102234'
```
![根据请求头限流](https://github.com/alibaba/higress/assets/45159482/2542cc1d-0d07-43e7-beff-a0d9cb85355a)

响应头中x-ratelimit-limit为10（限制的总请求数），x-ratelimit-remaining为7（剩余还可以发送的请求数）

触发限流后：
![根据请求头触发限流后](https://github.com/alibaba/higress/assets/45159482/3f3df4f3-c816-4c46-adc4-48024ae4b07b)

**2）正则表达式（规则为以c开头的任意字符串）**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-ca-key: c1234test'
```

![根据请求头限流2](https://github.com/alibaba/higress/assets/45159482/dad9a909-b568-461a-87f6-5ac669399b4b)

redis中数据：

![根据请求头限流 redis数据](https://github.com/alibaba/higress/assets/45159482/75d61b09-08d6-405c-832b-f59045ff72e5)

**3）、根据请求头 x-forwarded-for 获取对端IP，进行区别限流**

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    limit_by_per_ip: from-header-x-forwarded-for
    rule_name: limit_by_per_ip
    redis:
      service_name: redis.static
    show_limit_quota_header: true
    limit_keys:
      - key: 1.1.1.1
        query_per_day: 10
      - key: 1.1.1.0/24
        query_per_day: 100
      - key: 0.0.0.0/0
        query_per_day: 1000
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.60
  imagePullSecret: aliyun
```

**1）命中1.1.1.1**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-forwarded-for: 1.1.1.1'
```

![根据客户端ip限流](https://github.com/alibaba/higress/assets/45159482/b27654b1-64e4-4df3-ba3f-51cf4f7702b9)

**2）命中1.1.1.0/24**

请求四次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-forwarded-for: 1.1.1.2'
```

![根据客户端ip限流2](https://github.com/alibaba/higress/assets/45159482/de804158-6079-456f-9e04-6a15f480026f)

redis中数据（key名称包含从x-forwarded-for中获取的IP 1.1.1.2）：

![根据客户端ip限流2 redis中数据](https://github.com/alibaba/higress/assets/45159482/5066b99f-e3ab-4b1b-a68f-1310f536c8a8)

**4）、识别consumer，进行区别限流**

wasmplugin.yam：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    rule_name: default_limit_by_consumer
    limit_by_consumer: 
    limit_keys:
    - key: consumer1
      query_per_hour: 10
    - key: "regexp:^d.*"
      query_per_hour: 1000
    - key: "*"
      query_per_hour: 10000
    redis:
      service_name: redis.static
    show_limit_quota_header: true
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.60
  imagePullSecret: aliyun
```

**1）consumer1**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-mse-consumer: consumer1'
```

![根据consumer限流](https://github.com/alibaba/higress/assets/45159482/39a29825-40b4-4759-a5a1-08b8ed582c2a)

redis中数据：

![根据consumer限流 redis中数据](https://github.com/alibaba/higress/assets/45159482/ca4df633-a224-4de4-8889-e2c45bd95bc8)

**3）正则表达式（规则为以d开头的任意字符串）**

请求三次：

```shell
curl -kvv -X GET 'http://localhost:8082/test' \
-H 'Host: www.test.com' \
-H 'x-mse-consumer: d1234test'
```

![根据consumer限流2](https://github.com/alibaba/higress/assets/45159482/0021f63f-5554-4502-8aba-088b6cc17d16)

redis中数据：

![根据consumer限流2 redis数据](https://github.com/alibaba/higress/assets/45159482/c4469c40-b5a1-4380-94f5-b88ae28acb8b)

### Ⅴ. Special notes for reviews

2024-06-13 02:00 UTC, johnlanni requested changes

2024-06-13 02:00 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +  # 正则表达式，以b开头的所有字符串
这里会有歧义，是匹配到的所有统一限制1000，还是匹配到的每一个分别限制1000。

所以我建议增加新的配置项: limit_by_per_header, limit_by_per_param

用来表示匹配到的每一个分别限制这一含义。

2024-06-13 02:05 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +  # 正则表达式，以b开头的所有字符串
> 这里会有歧义，是匹配到的所有统一限制1000，还是匹配到的每一个分别限制1000。
> 
> 所以我建议增加新的配置项: limit_by_per_header, limit_by_per_param
> 
> 用来表示匹配到的每一个分别限制这一含义。

好的，那应该就是limit_by_header和limit_by_param只支持精确匹配的，limit_by_per_header和limit_by_per_param只支持正则匹配和*的方式

2024-06-13 02:05 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +  # 正则表达式，以b开头的所有字符串
可以的

2024-06-14 01:57 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +  # 正则表达式，以b开头的所有字符串
> 可以的

已调整，目前支持以下几种方式：
limit_by_header、limit_by_param、limit_by_consumer、limit_by_cookie（匹配cookie中的key=value）  支持精准匹配
limit_by_per_ip 支持按照ip和ip段配置
limit_by_peer_header、limit_by_peer_param、limit_by_peer_consumer、limit_by_per_cookie  支持正则匹配和*

2024-06-14 06:21 UTC, johnlanni requested changes

2024-06-14 06:21 UTC, johnlanni commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| rule_name               | string | 是 | - | 限流规则名称，根据限流类型+限流规则名称+限流key对应的实际值来拼装redis key                                                                                |
支持下配置多个rule可以同时生效吧，现有的配置作为rules数组里的配置项

2024-06-15 08:13 UTC, hanxiantao commented on plugins/wasm-go/extensions/cluster-key-rate-limit/README.md
> +| rule_name               | string | 是 | - | 限流规则名称，根据限流类型+限流规则名称+限流key对应的实际值来拼装redis key                                                                                |
> 支持下配置多个rule可以同时生效吧，现有的配置作为rules数组里的配置项

将limit_by_*（共9种）和limit_keys调整到了rule_items中，拼接redis的key的方式调整为限流规则名称+限流类型+限流key对应的实际值，这样只需要外部配置一个rule_name即可

2024-06-17 02:36 UTC, johnlanni approved these changes
LGTM

2024-06-17 02:37 UTC, merged