ut: add unit test for pkg/ingress/mcp
alibaba/higress pull request #104
Opened 2022-12-08 11:37 UTC by Charlie17Li

Signed-off-by: charlie <qianglin98@qq.com>

### Ⅰ. Describe what this PR did

ut: add unit test for pkg/ingress/mcp

### Ⅱ. Does this pull request fix one issue?

fixes #91 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-12-08 11:43 UTC, johnlanni requested changes

2022-12-08 11:43 UTC, johnlanni commented on pkg/ingress/mcp/generator_test.go
> +func generate_VirtualService(proxy *model.Proxy, configs []config.Config, w *model.WatchedResource,
```suggestion
func generateVirtualService(proxy *model.Proxy, configs []config.Config, w *model.WatchedResource,
```

2022-12-08 12:40 UTC, Charlie17Li commented on pkg/ingress/mcp/generator_test.go
> +func generate_VirtualService(proxy *model.Proxy, configs []config.Config, w *model.WatchedResource,
done

2022-12-10 01:56 UTC, johnlanni requested changes

2022-12-10 01:56 UTC, johnlanni commented on pkg/ingress/mcp/generator_test.go
> +	if !c1.Body.Equal(c2.Body) {
Such a comparison seems meaningless

2022-12-10 01:56 UTC, johnlanni commented on pkg/ingress/mcp/generator_test.go
> +		Spec: &networking.VirtualService{
A meaningful test is to unmarshal the mcp.body obtained by marshal back to virtualservice and compare it with the original object

2022-12-10 01:56 UTC, johnlanni commented on pkg/ingress/mcp/generator_test.go
> +func TestMarshal(t *testing.T) {
These testing things can be done directly in the above TestGenerate func.

2023-02-01 06:48 UTC, johnlanni approved these changes
LGTM

2023-02-01 06:48 UTC, merged