feat: OIDC wasm plugin
alibaba/higress pull request #1049
Opened 2024-06-20 10:02 UTC by Jing-ze

### Ⅰ. Describe what this PR did
Fork the oauth2proxy(https://github.com/oauth2-proxy/oauth2-proxy) and modify it into a wasm plugin

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

Wasm Plugin Config Yaml:
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: oidc
  namespace: higress-system
spec:
  defaultConfig:
    redirect_url: 'http://foo.bar.com/oauth2/callback'
    oidc_issuer_url: 'https://dev-o43xb1mz7ya7ach4.us.auth0.com/'
    client_id: 'YagFqRD9tfNIaac5BamjhsSatjrAnsnZ'
    client_secret: 'ekqv5XoZuMFtYms1NszEqRx03qct6BPvGeJUeptNG4y09PrY16BKT9IWezTrrhJJ'
    scope: 'openid email offline_access'
    cookie_secret: 'nqavJrGvRmQxWwGNptLdyUVKcBNZ2b18Guc1n_8DCfY='
    cookie_secure: false
    service_domain: 'dev-o43xb1mz7ya7ach4.us.auth0.com'
    service_name: 'auth'
    service_port: 443
    service_source: 'dns'
    oidc_verifier_request_timeout: 2000
  url: oci://registry.cn-hangzhou.aliyuncs.com/jingze/wasm-plugin:1.0.0

### Ⅴ. Special notes for reviews

2024-06-20 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1049) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1049) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1049) it.</sub>

2024-06-20 11:57 UTC, johnlanni commented
@Jing-ze 把oauth2 proxy相关的代码独立出来吧啊，提交到这里：https://github.com/higress-group/oauth2-proxy

这样也能看到为了适配 wasm 场景，对 oauth2 proxy 做了哪些改动

2024-06-21 02:44 UTC, Jing-ze commented
> @Jing-ze 把oauth2 proxy相关的代码独立出来吧啊，提交到这里：https://github.com/higress-group/oauth2-proxy
> 
> 这样也能看到为了适配 wasm 场景，对 oauth2 proxy 做了哪些改动

https://github.com/higress-group/oauth2-proxy/pull/1

2024-06-22 08:21 UTC, johnlanni requested changes

2024-06-22 08:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +![keycloak_login](/assets/keycloak_login.png)
图片用[图床](https://content.alibaba-inc.com/work/internal-media-management/pic/upload)吧，方便后面文档同步到higress官网

2024-06-22 08:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +| service_source                | string       | source of registration for the OIDC service (dns or ip)      |                   |
可以用FQDNCluster，简化配置，不需要配置 service_source了，参考下：https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ai-cache

2024-06-22 08:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +#### OIDC 流程解析
流程的 curl 命令和响应介绍参考下这里的风格：https://github.com/Kong/kong-oauth2-hello-world?tab=readme-ov-file#testing-the-authorization-flow

2024-06-22 08:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +5. 利用授权交换ID Token和Access Token
交换的过程 发送的请求和响应也可以给个例子介绍下

2024-08-27 09:16 UTC, johnlanni approved these changes
LGTM

2024-08-27 09:17 UTC, merged