feat:add build-and-push-wasm-plugin-image.yaml
alibaba/higress pull request #1064
Opened 2024-06-27 04:07 UTC by Beatrueman

### Ⅰ. Describe what this PR did
功能：添加了利用 GitHub Actions 来自动完成相应的镜像构建和发布工作的Workflow。支持通过push tag和手动触发两种方式。同时也遵循使用oras打包工具。
特点：完全按照[Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec/)进行镜像打包。
### Ⅱ. Does this pull request fix one issue?

fixes #1052 

### Ⅳ. Describe how to verify it
1.准备工作
添加Repository Secrets和 Repository variables。
![img](https://gitee.com/beatrueman/images/raw/master/img/202406271200281.png)
![img](https://gitee.com/beatrueman/images/raw/master/img/202406271200505.png)
2.通过`push tag`触发，将特定的插件打包成镜像并推送至指定仓库
![image](https://gitee.com/beatrueman/images/raw/master/img/202406271203466.png)
![image](https://gitee.com/beatrueman/images/raw/master/img/202406271204700.png)
![image](https://github.com/alibaba/higress/assets/121592304/2f1dbd0b-3f0e-4719-a5ef-d842b067c3af)
3.人工触发，指定插件名和版本号
![51e1fc7ab267c66492ecbcfb43cd23d0](https://github.com/alibaba/higress/assets/121592304/1c8ebccf-e523-44bf-813d-5f082dd1b596)
![image](https://github.com/alibaba/higress/assets/121592304/25aeaa55-914b-4cbe-88b9-fb2951bb47c2)
### Ⅴ. Special notes for reviews
这是我第一次参与开源贡献，希望能有所帮助！

2024-06-27 04:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1064) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1064) it.</sub>

2024-06-28 12:57 UTC, CH3CHO requested changes

2024-06-28 12:57 UTC, CH3CHO commented on .github/workflows/build-and-push-wasm-plugin-image.yaml
> +              ./plugin.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
这几个文件不是每一个都有的，需要判断一下。

2024-06-28 12:57 UTC, CH3CHO commented on .github/workflows/build-and-push-wasm-plugin-image.yaml
> +          ORAS_VERSION: 1.0.0
这几个变量可以支持通过 env 来覆盖吗？

2024-06-28 12:57 UTC, CH3CHO commented on .github/workflows/build-and-push-wasm-plugin-image.yaml
> +          docker run -d --name builder -v ${{ github.workspace }}:/workspace -e PLUGIN_NAME=${{ env.PLUGIN_NAME }} --rm ${{ env.BUILDER_IMAGE }} sleep 99999
这里 sleep 的目的是什么呢？

2024-06-28 12:57 UTC, CH3CHO commented on .github/workflows/build-and-push-wasm-plugin-image.yaml
> +    - "wasm-go-*-*.*.*" # 匹配 wasm-go-{pluginName}-vX.Y.Z 格式的标签
是不是可以体现一下 v 这个关键字

2024-06-28 12:57 UTC, CH3CHO commented on .github/workflows/build-and-push-wasm-plugin-image.yaml
> +    branches: [ main ]
main 这里可以不构建

2024-06-28 12:58 UTC, CH3CHO commented
可以参考一下 https://github.com/alibaba/higress/pull/1063

2024-06-28 13:05 UTC, Beatrueman commented
> 可以参考一下#1063

感谢您的建议，我会做出修改🙏

2024-06-29 03:43 UTC, closed without merging