Feat: Add Spark llm support for plugins/ai-proxy
alibaba/higress pull request #1139
Opened 2024-07-20 18:02 UTC by urlyy

### Ⅰ. Describe what this PR did
Support DeepSeek ai model, api documentation: https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html

### Ⅱ. Does this pull request fix one issue?
fixes #949

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it
1. ai-proxy/docker-compose.yaml
```
version: '3.7'
services:
  envoy:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/gateway:v1.4.0-rc.1
    entrypoint: /usr/local/bin/envoy
    # 注意这里对wasm开启了debug级别日志，正式部署时则默认info级别
    command: -c /etc/envoy/envoy.yaml --component-log-level wasm:debug
    depends_on:
    - httpbin
    networks:
    - wasmtest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./plugin.wasm:/etc/envoy/plugin.wasm

  httpbin:
    image: kennethreitz/httpbin:latest
    networks:
    - wasmtest
    ports:
    - "12345:80"

networks:
  wasmtest: {}
```
2. ai-proxy/envoy.yaml
```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scheme_header_transformation:
                  scheme_to_overwrite: https
                stat_prefix: ingress_http
                # Output envoy logs to stdout
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                # Modify as required
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: spark
                            timeout: 300s
                http_filters:
                  - name: wasmtest
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: wasmtest
                          vm_config:
                            runtime: envoy.wasm.runtime.v8
                            code:
                              local:
                                filename: /etc/envoy/plugin.wasm
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              {
                               "provider": {
                                 "type": "spark",
                                 "sparkAuthKey": "your key",
                                 "sparkAuthSecret": "your secret",
                                 "apiTokens": [
                                    "not used"
                                  ],
                                 "timeout": 1200000,
                                 "modelMapping": {
                                   "gpt-4o": "Max",
                                   "*": "Lite"
                                 }
                               }
                              }
                  - name: envoy.filters.http.router
  clusters:
    - name: httpbin
      connect_timeout: 30s
      type: LOGICAL_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin
                      port_value: 80
    - name: spark
      connect_timeout: 30s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: spark
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: spark-api-open.xf-yun.com
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          "sni": "spark-api-open.xf-yun.com"
```
3. 编写并运行ai-proxy/build.sh
```shell
go mod tidy
tinygo build -o plugin.wasm -scheduler=none -target=wasi -gc=custom -tags="custommalloc nottinygc_finalizer" ./main.go
sudo docker compose up
```
4. 发送请求
- openai协议，非流式
```shell
curl --location 'http://127.0.0.1:10000/v1/chat/completions' \
--header 'Content-Type:  application/json' \
--data '{
    "model":"g-4o",
    "messages": [
        {
            "role": "system",
            "content": "你是一个名专业的开发人员！"
        },
        {
            "role": "user",
            "content": "你好，你是谁？"
        }
    ]
}'
```
回复
```json
{
    "id": "cha000c388a@dx190d0fca0f5b8f2532",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "您好，我是一名专业的开发人员，我可以帮助您解决各种编程和技术问题。"
            }
        }
    ],
    "created": 1721493136,
    "model": "Lite",
    "object": "chat.completion",
    "usage": {
        "prompt_tokens": 11,
        "completion_tokens": 14,
        "total_tokens": 25
    }
}
```
- openai协议，流式
```shell
curl --location 'http://127.0.0.1:10000/v1/chat/completions' \
--header 'Content-Type:  application/json' \
--data '{
    "model":"gpt-4o",
    "messages": [
        {
            "role": "system",
            "content": "你是一个名专业的开发人员！"
        },
        {
            "role": "user",
            "content": "你好，你是谁？"
        }
    ],
    "stream": true
}'
```
回复
```
data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"您好"}}],"created":1721493360,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"，我是"}}],"created":1721493361,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"您的虚拟助手"}}],"created":1721493361,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"，一个人工智能开发人员"}}],"created":1721493361,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"。"}}],"created":1721493361,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"我可以帮助您解决有关编程、软件开发和AI技术的问题。"}}],"created":1721493361,"model":"Max","object":"chat.completion","usage":{}}

data: {"id":"cha000b3762@dx190d1000f9cb8f3532","choices":[{"index":0,"message":{"role":"assistant","content":"请问有什么我可以帮助您的吗？"}}],"created":1721493362,"model":"Max","object":"chat.completion","usage":{"prompt_tokens":11,"completion_tokens":30,"total_tokens":41}}
```
- spark协议，非流式(需要在`envoy.yaml`的`provider`下添加`"protocol":"original"`，然后重新运行build.sh。注意model要为星火认知大模型的真实名称)
```shell
curl --location 'http://127 [...]

2024-07-20 18:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1139) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1139) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1139) it.</sub>

2024-07-22 08:45 UTC, cr7258 commented
> 我在envoy.yaml中设置了一个没有用到的apiTokens值，似乎不设置会报错。可能我可以把我新增的sparkAuthSecret替换为apiTokens[0]?

```
proxywasm.ReplaceHttpRequestHeader(authorizationKey, "Bearer "+p.config.sparkAuthKey+":"+p.config.sparkAuthSecret)
```
因为你是用 sparkAuthKey 和 sparkAuthSecret 来设置 Authorization Header 的，没有用到 apiTokens。
讯飞星火的 API Token 相当于是用 APIKey 和 APISecret 拼接起来的，所以我觉得你可以不用额外提供 APIKey 和 sparkAuthSecret 这两个字段，而是仍然用通用的 apiTokens 字段，只需要在你的示例中告诉用户 apiTokens 的值是 `APIKey:APISecret` 的形式即可。 这样有个好处是可以配置多个 apiTokens。

2024-07-22 09:14 UTC, urlyy commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		}
因为我看`insertContextMessage`的参数要求是`chatCompletionRequest`，而不是我自定义的`sparkRequest`

2024-07-22 09:57 UTC, urlyy commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		}
抱歉，`似乎没能成功添加system prompt`这个问题是模型自身的，`Lite`模型似乎不会使用到`system prompt`。仅将model改为`Max`后，模型能成功利用到`system prompt`。
```
"model":"Max",
    "messages": [
        {
            "role": "system",
            "content": "你是一个名专业的小丑！"
        },
```
回复：
```
"choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "你好，我是世界上最有名的小丑！人们称我为“欢乐的使者”和“笑容的创造者”。我以我的搞笑表演、滑稽动作和独特的妆容带给人们欢笑。你有什么问题想问我吗？"
            }
        }
    ],
```
而Lite：
```
 "model":"Lite",
    "messages": [
        {
            "role": "system",
            "content": "你是一个名专业的小丑！"
        },
```
回复：
```
 "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "您好，我是科大讯飞研发的认知智能大模型，我的名字叫讯飞星火认知大模型。我可以和人类进行自然交流，解答问题，高效完成各领域认知智能需求。"
            }
        }
    ],
```

2024-07-22 10:17 UTC, urlyy commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		}
抱歉，`似乎没能成功添加system prompt`这个问题似乎是星火的`Lite`模型没有利用到`system prompt`，我刚试出来`openai`和`spark`两种协议下`Lite`模型都没有变成`system prompt`中设置的角色，改为`Max`模型就成功变了。

2024-07-22 10:36 UTC, urlyy commented
我重新修改了一下，移除了spark的authKey和authSecret。但我在本地如果不重新`go mod tidy`，会出现`"github.com/higress-group/proxy-wasm-go-sdk/proxywasm/types"`这个依赖爆红，我不知道其他人有没有这个情况。我这次commit把两个`go.sum`的更改也提交了，如果不应该改的话，我可以把`go.sum`改回去。

2024-07-22 16:35 UTC, urlyy commented
请问`OnResponseBody`中，如果是`spark`协议，还需要将`sparkResponse`转为`chatCompletionResponse`吗

2024-07-25 14:41 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +	sparkChatCompletionPath = "/v1/chat/completions"
这个变量没有用到

2024-07-25 14:41 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +}
好像只有 websocket 的 url 路径对于不同的模型才不一样？HTTP 的请求路径始终是 `v1/chat/completions`。
```bash
curl -i -k -X POST 'https://spark-api-open.xf-yun.com/v1/chat/completions' \
--header 'Authorization: Bearer <APIKEY>:<APISECERT>' \
--header 'Content-Type: application/json' \
--data '{
    "model":"pro-128k",
    "messages": [
        {
            "role": "user",
            "content": "你是什么模型？"
        }
    ]
}'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 409
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Date: Thu, 25 Jul 2024 14:27:16 GMT
X-Kong-Upstream-Latency: 1038
X-Kong-Proxy-Latency: 0
Via: kong/1.3.0

{"code":0,"message":"Success","sid":"cha000b5a0b@dx190ea49fbccb8f3532","choices":[{"message":{"role":"assistant","content":"您好，我是科大讯飞研发的认知智能大模型，我的名字叫讯飞星火认知大模型。我可以和人类进行自然交流，解答问题，高效完成各领域认知智能需求。"},"index":0}],"usage":{"prompt_tokens":4,"completion_tokens":40,"total_tokens":44}}



---------------------------

curl -i -k -X POST 'https://spark-api-open.xf-yun.com/v1/chat/completions' \
--header 'Authorization: Bearer <APIKEY>:<APISECERT>' \
--header 'Content-Type: application/json' \
--data '{
    "model":"generalv3.5",
    "messages": [
        {
            "role": "user",
            "content": "你是什么模型？"
        }
    ]
}'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 409
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Date: Thu, 25 Jul 2024 14:27:42 GMT
X-Kong-Upstream-Latency: 1446
X-Kong-Proxy-Latency: 0
Via: kong/1.3.0

{"code":0,"message":"Success","sid":"cha000b5ab3@dx190ea4a5d8fb8f3532","choices":[{"message":{"role":"assistant","content":"您好，我是科大讯飞研发的认知智能大模型，我的名字叫讯飞星火认知大模型。我可以和人类进行自然交流，解答问题，高效完成各领域认知智能需求。"},"index":0}],"usage":{"prompt_tokens":4,"completion_tokens":40,"total_tokens":44}}
```

2024-07-25 14:41 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +			Message: &chatMessage{Role: c.Delta.Role, Content: c.Delta.Content},
```suggestion
			Delta: &chatMessage{Role: c.Delta.Role, Content: c.Delta.Content},
```

2024-07-25 14:41 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +			Message: &chatMessage{Role: c.Delta.Role, Content: c.Delta.Content},
流式的时候这里应该是 delta

```
data: {"id":"cha000c6af7@dx190ea507009b8f2532","choices":[{"index":0,"delta":{"role":"assistant","content":"科大讯"}}],"created":1721918059,"model":"Max","object":"chat.completion","usage":{}}
```

2024-07-26 00:01 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		_ = util.OverwriteRequestPath(path)
这个方法最终调用 `proxywasm.ReplaceHttpRequestHeader`，只在 `OnRequestHeaders` 阶段才有效，你是放在 `OnRequestBody` 里面，所以实际上也不会去修改请求路径。
https://pkg.go.dev/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm#ReplaceHttpRequestHeader

2024-07-26 00:24 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		action, err := p.insertSparkContext(request, &log)
使用 spark 协议的话应该是不需要对请求进行改写的，只有当我们使用 openai 协议的时候，才需要把 openai 的请求体改成 spark 的请求体。

2024-07-26 01:09 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		}
光从回答的内容看不出 system role是不是成功设置了，就算是使用 max，有时候回答也看不出来。
```
curl -i -k -X POST 'https://spark-api-open.xf-yun.com/v1/chat/completions' \
--header 'Authorization: Bearer <APIKEY>:<APISECERT>' \
--header 'Content-Type: application/json' \
--data '{
    "model":"generalv3.5",
    "messages": [
        {
            "role": "system",
            "content": "你是一名专业的翻译！"
        },
        {
            "role": "user",
            "content": "你是谁？"
        }
    ]
}'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 588
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Date: Fri, 26 Jul 2024 00:42:58 GMT
X-Kong-Upstream-Latency: 6252
X-Kong-Proxy-Latency: 1
Via: kong/1.3.0

{"code":0,"message":"Success","sid":"cha000c7216@dx190ec7d9771b8f2532","choices":[{"message":{"role":"assistant","content":"您好，我是讯飞星火认知大模型，由科大讯飞构建。\n作为一款先进的认知智能大模型，我的设计宗旨在于模仿人类的认知过程，以便更自然地与人交流、解决问题，并在各种领域内提供智能支持。我的能力覆盖了从语言理解到复杂问题解答的广泛范围，旨在帮助用户高效完成各类任务。"},"index":0}],"usage":{"prompt_tokens":8,"completion_tokens":76,"total_tokens":84}}%                                                                                                                                                                                                                 
```

2024-07-26 02:39 UTC, urlyy commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +		_ = util.OverwriteRequestPath(path)
这个我是参考了baidu.go里的OnRequestBody的逻辑，然后我看minimax.go里也是这么做的

2024-07-26 03:16 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +	}, *log)
insertContextMessage 只有当需要从文件中获取内容时才需要，例如通义千问：https://help.aliyun.com/zh/dashscope/developer-reference/openai-file-interface
`contextCache.GetContent` 函数会去读取内容，然后 insertContextMessage 设置 role system。
```
{"role": "system", "content": f"fileid://{file_object.id}"},
```
所以如果星火不支持根据文件提问的话，这部分就应该是不需要的，并且你 copy 的那部分代码就也不需要了。

2024-07-26 13:05 UTC, urlyy commented
@cr7258  非常感谢您的耐心review！根据您的建议我进行了修改
1. 将请求路径换成固定的那个了，并在`OnRequestHeaders`中设置路径
2. 将模型从需要`Lite`这种改为需要`general`这种，将`modelMapping`之外的模型名映射删掉了
3. 移除了`insertXXContext`，因为星火的`completions`接口不支持上传文件
4. 在流式内改为设置`Delta`
5. 将上方pr里的内容和README.md同步修改了


除此之外，虽然是否返回调用的模型名是大模型厂商应该做的，我还是根据用户的`model`参数设置了response里的`model`字段值。但我发现星火如果用`original`协议，且请求的模型名不存在的话，也会调用`generalv3`，这可能会导致`higress`使用`protocol : original`，同时`request { model : qwer }`，higress返回的是`response { model : qwer }`，但实际是`generalv3`被调用了。不知道这里是否要处理一下

2024-07-27 14:25 UTC, cr7258 commented
<img width="870" alt="image" src="https://github.com/user-attachments/assets/3bcb6d44-1464-47cb-9a58-687593a2c0ca">
使用 NextChat 验证了一下，可以正常使用。

2024-07-27 14:29 UTC, cr7258 commented
> 除此之外，虽然是否返回调用的模型名是大模型厂商应该做的，我还是根据用户的model参数设置了response里的model字段值。但我发现星火如果用original协议，且请求的模型名不存在的话，也会调用generalv3，这可能会导致higress使用protocol : original，同时request { model : qwer }，higress返回的是response { model : qwer }，但实际是generalv3被调用了。不知道这里是否要处理一下

这个我觉得可以不用处理，因为星火的原始响应里面没有包含 model 信息，所以我们只能根据用户设置的 model参数来设置响应的 model。

2024-07-27 14:29 UTC, cr7258 approved these changes
🐉 LGTM

2024-07-30 11:57 UTC, johnlanni requested changes

2024-07-30 11:57 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/spark.go
> +	_ = proxywasm.ReplaceHttpRequestHeader(authorizationKey, "Bearer "+p.config.GetRandomToken())
这块有调整，参考下其他模型的最新实现，需要用util下的overwrite

2024-08-08 07:16 UTC, johnlanni approved these changes
LGTM

2024-08-08 07:16 UTC, merged