fix:ext-auth wasm plugin bug
alibaba/higress pull request #1152
Opened 2024-07-24 12:43 UTC by hanxiantao

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?
修复ext-auth wasm plugin中的bug：
1）http_service默认超时时间调整为1秒
2）修复判断是否有requestBody的逻辑 新增chunked的情况
3）修复service_source为k8s和nacos 相关配置不生效的问题
4）修复request_method不生效的问题

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-07-25 01:39 UTC, johnlanni commented
这个插件使用 proxy wasm 0.2.100 这个ABI，需要在目录下放这个文件指明：
https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-cache/.buildrc

2024-07-25 01:43 UTC, johnlanni requested changes

2024-07-25 01:43 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/README.md
> +| `service_source` | string   | 是   | -      | 类型固定为 `k8s` , `nacos` , `ip` 或 `dns`，输入授权服务的注册来源 |
服务配置我倾向于后续插件都统一到这种配置方式：https://github.com/alibaba/higress/blob/10569f49aeebbf3bdd9c391a69119854547ad65d/plugins/wasm-go/extensions/ai-cache/main.go#L72-L76
这样不用配置 service_source 字段，都用 FQDNCluster

2024-07-25 01:43 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
> +	"strings"
import 排序似乎有问题

2024-07-25 01:43 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
>  	if config.httpService.authorizationRequest.withRequestBody {
这里可以记一个TODO，要支持 buffer limit size 设置，这个下个版本会支持

2024-07-25 01:45 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
>  	if config.httpService.authorizationRequest.withRequestBody {
这个是后续onHttpRequestBody阶段这里会支持配置buffer limit size对吧

2024-07-25 01:47 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
>  	if config.httpService.authorizationRequest.withRequestBody {
> 这里可以记一个TODO，要支持 buffer limit size 设置，这个下个版本会支持

这个是buffer limit size的需求，这个是后续onHttpRequestBody阶段这里会支持配置buffer limit size吗，还是这边[]byte要自己截取size

2024-07-25 05:11 UTC, jaggerwang commented
示例中 namespace 需要放到跟 endpoint 同级，并且配置说明里也需要加一下 k8s 方式相关的配置项和取值说明。

2024-07-25 12:45 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
>  	if config.httpService.authorizationRequest.withRequestBody {
已经支持了，这个插件也可以支持下：https://github.com/alibaba/higress/blob/29079f4e2a6089bbb5c7a79a222fb1df1e00c4a0/plugins/wasm-go/pkg/wrapper/plugin_wrapper.go#L56

2024-07-25 12:49 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
>  	if config.httpService.authorizationRequest.withRequestBody {
> 已经支持了，这个插件也可以支持下：
> 
> https://github.com/alibaba/higress/blob/29079f4e2a6089bbb5c7a79a222fb1df1e00c4a0/plugins/wasm-go/pkg/wrapper/plugin_wrapper.go#L56

好的

2024-07-26 01:00 UTC, jaggerwang commented on plugins/wasm-go/extensions/ext-auth/README.md
> +| `namespace` | string   | 否   | -      | 当类型为k8s和nacos时必须填写，输入 `ext-auth` 服务的namespace    |
namespace 到底是放在 endpoint 同级还是放在其下？之前给的测试版本说是要放在 endpoint 同级。

2024-07-26 01:11 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/README.md
> +| `namespace` | string   | 否   | -      | 当类型为k8s和nacos时必须填写，输入 `ext-auth` 服务的namespace    |
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/cc81a2dd-6104-4036-adb0-198ba50e6703">
修复后的版本会和cluster-key-rate-limit插件中redis配置方式相同，后续插件都会统一成这种方式，预计本周末我会修复下这个问题

2024-07-26 01:15 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/README.md
> +| `namespace` | string   | 否   | -      | 当类型为k8s和nacos时必须填写，输入 `ext-auth` 服务的namespace    |
> namespace 到底是放在 endpoint 同级还是放在其下？之前给的测试版本说是要放在 endpoint 同级。

![WX20240726-091351@2x](https://github.com/user-attachments/assets/05dad20d-3e13-4745-94c7-258c6c202b99)
之前的版本是在配置解析namespace的时候有点问题，这里应该是endpointConfig.Get("namespace")

2024-07-28 02:01 UTC, jaggerwang approved these changes

2024-07-29 02:38 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/utils.go
> +func hasRequestBody() bool {
可以考虑把这段逻辑放到通用逻辑里作为通用的util函数

2024-07-29 02:45 UTC, johnlanni requested changes

2024-07-29 02:45 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
> +		ctx.SetRequestBodyBufferLimit(DefaultMaxBodyBytes)
这个是否应该支持用户配置，类似 envoy 原生的ext authz的做法：https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-buffersettings

2024-07-29 02:47 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/utils.go
> +func hasRequestBody() bool {
好的，目前看来添加到[plugins/wasm-go/pkg/wrapper/request_wrapper.go](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/pkg/wrapper/request_wrapper.go)中比较合适

2024-07-29 02:53 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
> +		ctx.SetRequestBodyBufferLimit(DefaultMaxBodyBytes)
好的，这个我在开发的时候也做了下验证，我发现如果设置了ctx.SetRequestBodyBufferLimit(maxBodyBytes)，当maxBodyBytes设置过小时，会直接拒绝请求，返回HTTP 413
这种方式实现，目前的话只能先支持设置max_request_bytes，暂无法支持allow_partial_message=true的场景

2024-07-30 12:22 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
> +		ctx.SetRequestBodyBufferLimit(DefaultMaxBodyBytes)
> 这个是否应该支持用户配置，类似 envoy 原生的ext authz的做法：https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-buffersettings

已调整，麻烦帮忙再review下

2024-07-31 07:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/config.go
>  	if !requestMethodConfig.Exists() {
这个的默认行为我建议跟envoy的ext authz逻辑保持一致，就是用跟原请求一样的Method

2024-07-31 07:39 UTC, johnlanni requested changes

2024-07-31 07:39 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/config.go
>  	requestMethodConfig := endpointConfig.Get("request_method")
这个的默认行为我建议跟envoy的ext authz逻辑保持一致，就是用跟原请求一样的Method

2024-07-31 07:41 UTC, johnlanni requested changes

2024-07-31 07:41 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
> +	err := httpServiceConfig.client.Call(httpServiceConfig.requestMethod, httpServiceConfig.path, reconvertHeaders(extAuthReqHeaders), body,
这个请求path的默认行为也建议尽量跟envoy ext authz的逻辑保持一致，应该是配置一个前缀，然后把原始请求的path（包含url参数）拼接在前缀后面发给鉴权服务

2024-07-31 07:41 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/main.go
> +	err := httpServiceConfig.client.Call(httpServiceConfig.requestMethod, httpServiceConfig.path, reconvertHeaders(extAuthReqHeaders), body,
![image](https://github.com/user-attachments/assets/76e0c80e-bb49-4b94-9047-dc5477d5fa1f)

2024-07-31 08:59 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/main.go
> +	err := httpServiceConfig.client.Call(httpServiceConfig.requestMethod, httpServiceConfig.path, reconvertHeaders(extAuthReqHeaders), body,
如线下沟通，我会在最外层加一个endpoint_mode的配置，支持配置envoy（默认值）和forward_auth两种模式
如果是envoy就按照envoy原生的方式，只需要配置path_prefix
如果是forward_auth的话，就按照目前的方式，需要配置request_method和request_path

2024-07-31 09:08 UTC, hanxiantao commented
regexp要改成regexp "github.com/wasilibs/go-re2" 
https://github.com/alibaba/higress/issues/674

2024-08-01 03:12 UTC, johnlanni commented on plugins/wasm-go/extensions/ext-auth/config.go
> +		httpService.pathPrefix = pathPrefixConfig.String()
如果配置了 request_method 应该有个warning提示，在envoy mode下，会被忽略

2024-08-05 03:04 UTC, johnlanni approved these changes
LGTM

2024-08-05 03:04 UTC, merged

2024-08-05 06:06 UTC, jaggerwang commented
看代码已经合到 main，请问相关的 WASM 镜像及版本更新了吗？还是说等到下次版本发布才会更新。

2024-08-05 06:17 UTC, hanxiantao commented
@CH3CHO 麻烦帮忙，把ext-auth插件打个新的镜像吧

2024-08-05 06:57 UTC, CH3CHO commented
> @CH3CHO 麻烦帮忙，把ext-auth插件打个新的镜像吧

好的。我现在处理一下。

2024-08-05 07:01 UTC, CH3CHO commented
> > @CH3CHO 麻烦帮忙，把ext-auth插件打个新的镜像吧
> 
> 好的。我现在处理一下。

higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ext-auth:1.0.0 @hanxiantao

2024-08-06 00:46 UTC, jaggerwang commented
版本号没有升吗，之前已经拉取过的如何强制获取最新镜像？

2024-08-06 02:51 UTC, CH3CHO commented
> 版本号没有升吗，之前已经拉取过的如何强制获取最新镜像？

现在重启 gateway 容器就可以触发强制重新拉取镜像了

2024-08-06 02:52 UTC, johnlanni commented
不用重启，开关插件，或者修过插件配置就可以了，注意下现在配置跟之前的不兼容

2024-08-06 03:59 UTC, jaggerwang commented
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/9750e4ab-2a64-496e-acb9-d8f8c357d94d">
forward_auth 模式下无法获取从请求头里到原始请求的 Path（Authorization 可以获取到），也无法通过 allowed_headers 来添加，因为原始请求里也没有 Path 这个头，另外使用 headers_to_add 也不行，因为原始请求路径不是一个固定值，我们需要依赖原始请求的路径来做权限检查。

2024-08-06 12:17 UTC, hanxiantao commented
> <img alt="image" width="1168" src="https://private-user-images.githubusercontent.com/1255011/355306068-9750e4ab-2a64-496e-acb9-d8f8c357d94d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDY2NDAsIm5iZiI6MTcyMjk0NjM0MCwicGF0aCI6Ii8xMjU1MDExLzM1NTMwNjA2OC05NzUwZTRhYi0yYTY0LTQ5NmUtYWNiOS1kOGY4YzM1N2Q5NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTIxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRjMTYzYjIxMGQzMjZiNmZkOWZmOTJkNTBhZWZiYTcxZDBjN2E2NGIzMzJlMmJmMTJlOWExMjQyNTA0NDE5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d_7LKImrfB_pleDH1Z8x6KK0whfypPllDFGMRa-nq2M"> <img alt="image" width="1169" src="https://private-user-images.githubusercontent.com/1255011/355308083-a6b2c9b0-6ce7-427b-b290-65a285a9304a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDY2NDAsIm5iZiI6MTcyMjk0NjM0MCwicGF0aCI6Ii8xMjU1MDExLzM1NTMwODA4My1hNmIyYzliMC02Y2U3LTQyN2ItYjI5MC02NWEyODVhOTMwNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTIxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjlkNzc2MzY2YzhlZTJkNjZiMzEwZWU2YjgwZTA1OWYwNmMzNDI1NTM0YWM5MDEyNWIwODdlYjBlYmYwNzBmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eYAEtvpJx6YmIfztvqhO2qo37zhI5ELAMk7fUZ4t9aE"> forward_auth 模式下无法从请求头里获取到原始请求的 Path（Authorization 可以获取到），也无法通过 allowed_headers 来添加，因为原始请求里也没有 Path 这个头，另外使用 headers_to_add 也不行，因为原始请求路径不是一个固定值，我们需要依赖原始请求的路径来做权限检查。

感谢建议，因为envoy和forward_auth两种endpoint_mode，envoy这种endpoint_mode目前是能拿到原始的requestMethod和requestPath，但forward_auth这种endpoint_mode暂不支持，考虑到鉴权（认证场景不一定）大部分都会涉及requestMethod和requestPath，endpoint_mode为forward_auth时我会添加下X-Original-Method和X-Original-URI两个请求头
示例如下：
X-Original-Method: POST
X-Original-URI: /path/to/resource?query=param

2024-08-07 01:30 UTC, jaggerwang commented
非常感谢！能尽快合并一下这个 PR 吗，或者先给一个测试版本的镜像，我们现在卡在这里了，之前看文档以为原始请求路径会通过 Path 头传递过来，但后面调试时才发现取不到。

2024-08-07 01:32 UTC, hanxiantao commented
> 非常感谢！能尽快合并一下这个 PR 吗，或者先给一个测试版本的镜像，我们现在卡在这里了，之前看文档以为原始请求路径会通过 Path 头传递过来，但后面调试时才发现取不到。

#1180 PR里有写 是我之前提供给你的我个人仓库里的
registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:ext-auth-0.0.85

2024-08-07 01:39 UTC, hanxiantao commented
@jaggerwang 验证ok的话，帮忙在#1180 的PR下帮忙回复下，感谢