add plugin gw-error-format
alibaba/higress pull request #116
Opened 2022-12-29 10:51 UTC by zhangjiahaol

### Ⅰ. Describe what this PR did
Implement a plugin that can replace the response body according to the configuration

### Ⅱ. Does this pull request fix one issue?

fixes #62

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
No unit tests yet

### Ⅳ. Describe how to verify it
If you deployed higress as a K8S cluster, you can use this yaml to test replace-responsebody.yaml

### Ⅴ. Special notes for reviews
Check out README.md

2023-01-04 03:10 UTC, johnlanni requested changes

2023-01-04 03:10 UTC, johnlanni commented on plugins/wasm-go/extensions/gw-error-format/main.go
> +			DontReadResponseBody = true
Is it also unnecessary to read the response body when the `x-envoy-upstream-service-time` header is present?

2023-01-04 12:05 UTC, johnlanni requested changes

2023-01-04 12:05 UTC, johnlanni commented on plugins/wasm-go/extensions/gw-error-format/main.go
> +	if DontReadResponseBody == true {
This bool here will never be false.

2023-01-17 09:42 UTC, Xunzhuo commented on plugins/wasm-go/extensions/gw-error-format/VERSION
> +1.0.0
nit: missing space at end

2023-02-15 02:07 UTC, johnlanni commented
@zhangjiahaol Hello, do you have time to do some more optimizations on the code?

2023-02-16 06:45 UTC, zhangjiahaol commented
> @zhangjiahaol Hello, do you have time to do some more optimizations on the code?

under fix.

2023-02-17 06:00 UTC, CH3CHO requested changes

2023-02-17 06:00 UTC, CH3CHO commented on plugins/wasm-go/extensions/gw-error-format/main.go
> +				proxywasm.RemoveHttpResponseHeader("content-length")
Do we need to handle errors returned by response header manipulating functions above?

2023-02-17 06:00 UTC, CH3CHO commented on plugins/wasm-go/extensions/gw-error-format/main.go
> +					log.Critical("failed ReplaceHttpResponseHeader :status")
Should we log the error itself?

2023-04-28 09:46 UTC, zhangjiahaol commented on plugins/wasm-go/extensions/gw-error-format/main.go
> +		current_statuscode, err := proxywasm.GetHttpResponseHeader(":status")
fix

2023-04-28 12:56 UTC, CH3CHO approved these changes
LGTM

2023-05-04 01:42 UTC, merged