Feat: Add ai-geoip wasm plugin to search the client's geographic information depending on the client ip address
alibaba/higress pull request #1172
Opened 2024-08-02 17:39 UTC by ranxuxin001

### Ⅰ. Describe what this PR did
This PR describes the implementation principle and functionality of the ai-geoip wasm plugin. When Higress starts and parses the configuration of ai-geoip plugin, it transfers rows of the ip segment and related world geographic data into a two-dimension array. It uses the first two bytes of the ip address as the two indexes of the array to get the element. After that, it appends the geoip data to an one-dimension array of the element. This one-dimension array contains several ip segments in ascendant order because the geoip rows are originally in ascendant order.   

When a client sends a question to Higress, the ai-geoip plugin retrives the client ip address using the X-Forwarded-For request header or the connection remote address. And then it indexes the element of the two-dimension array according to the first two bytes of the client ip. Finally, it uses binary search to find the ip segment which includes the client ip in the one-dimension array of the element. 

After that, it gets geographic data in the data structure of the ip segment. Then it delivers the geoip data structure to latter wasm plugins.  using proxywasm.SetProperty(). And the latter plugin calls proxywasm.GetProperty() to take client's geoip data structure.     

This plugin is able to supply the client's geographic data as the system prompt to the ai-proxy plugin which sends request to the LLVM chat api server. It helps Higress to send more accurate and localize response to the client. 

### Ⅳ. Describe how to verify it
This plugin is verified in SAE of Alibaba cloud. Write proxywasm.GetProperty() in the latter plugin. The postman sends request to Higress with X-Forwarded-For header. The latter plugin's log indicates the geographic data of the client ip.

2024-08-05 03:01 UTC, johnlanni requested changes
这个实现的数据结构对空间浪费比较大，需要用 radix tree 实现，具体可以参考： https://github.com/zmap/go-iptree
你的原始ip data数据需要先做处理，把ip范围转换为ip段，然后通过radix tree做存储，这样可以节省大量的内存。
另外你不要把原始data数据放到go文件里，应该用embedfs等工具编译进去，并在go代码里读取文件内容。

2024-08-06 08:44 UTC, ranxuxin001 commented
> 这个实现的数据结构对空间浪费比较大，需要用 radix tree 实现，具体可以参考： https://github.com/zmap/go-iptree 你的原始ip data数据需要先做处理，把ip范围转换为ip段，然后通过radix tree做存储，这样可以节省大量的内存。 另外你不要把原始data数据放到go文件里，应该用embedfs等工具编译进去，并在go代码里读取文件内容。

@johnlanni  非常感谢对我的实现提出宝贵意见。新的commit里是重新实现的ai-geoip-radixtree插件。我首先把ip网段转换成了cidr 和地址位置信息 一起放入 txt文件。然后用embed 直接使用该文件的字符串。然后把cidr 做为key， 地址位置信息做value 加入radixtree里。查询时候调用iptree的GetByString(client_ip) 获取value的地理位置信息。最后把第地址信息通过 proxywasm.SetProperty() 传给后续插件。

2024-08-08 02:07 UTC, johnlanni requested changes

2024-08-08 02:07 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-geoip-radixtree/main.go
> +		"ai-geoip",
插件目录名字和插件名保持一致，就叫geo-ip吧，非AI场景下也能使用。

后面可以给[ai-prompt-decorator](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ai-prompt-decorator)插件增加个功能，获取地理位置信息，自动加一个system prompt：

当前用户的地理位置信息是xxxxx

2024-08-10 17:16 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/ai-geoip-radixtree/main.go
> +//go:embed geoCidr.txt
@johnlanni   辛苦审核代码。新的commit使用set property 分别把country，city，province，isp设置进请求属性里。README.txt 说明了插件功能，配置和cidr列表的生成方式。generateCidr 目录里的程序是转换ip2region 的网段格式的geoip库成为cidr 格式。另外加入了geo-ip插件的测试用例。

2024-08-13 07:07 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-geoip-radixtree/main.go
> +//go:embed geoCidr.txt
> README.txt 说明了插件功能

README请用英文写，参考下其他插件的格式

> generateCidr 目录里的程序是转换ip2region 的网段格式的geoip库成为cidr 格式

请在REAMDE中说明这一点，并给出生成geoCidr.txt文件的完整命令

2024-08-13 07:17 UTC, johnlanni requested changes

2024-08-13 07:17 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/generateCidr/main.go
> +func main() {
需要增加单元测试，主要是测试这里将一个IP Range转换为cidr网段表示的准确性，我理解一个IP Range有时候可能是一个cidr网段没法完整表示的，需要用多个cidr网段，但我看这里都一对一转换了，是否有问题？

可以看下这个工具，可以验证下你的功能：
http://netasst.com/tools/ipcvt.html

2024-08-13 07:17 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-geo-ip.go
> +
只检查200状态码无法验证插件的功能，可以设置property的同时，给请求增加额外的请求头，例如：
X-Higress-Geo-City: xxx
X-Higress-Geo-Province: xxx

这样可以用这里ExpectedRequest功能来验证，参考：

https://github.com/alibaba/higress/blob/6b9dabb4890c59c6424d604342ffa6479a019be2/test/e2e/conformance/tests/httproute-request-header-control.go#L47-L56

2024-08-14 12:08 UTC, johnlanni requested changes

2024-08-14 12:08 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/generateCidr/main.go
> +func range2cidrList(startIp string, endIp string, country string, province string, city string, isp string, f *os.File) {
需要增加 ip range 到 cidr 的单元测试

2024-08-14 12:08 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-geo-ip.go
> +								"X-Higress-Geo-City":     "0",
为什么是 0？没有city的话，是不是应该是空字符串呢

2024-08-16 06:13 UTC, johnlanni requested changes

2024-08-16 06:13 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/testIpSegmentToCidr/main_test.go
> +func range2cidrList(startIp string, endIp string, country string, province string, city string, isp string, f *os.File) {
为什么在测试文件里重复定义这个函数呢？而且test文件为什么不跟源文件放在一个目录下？

你应该把 range2cidr 这个核心流程独立一个函数，然后只测试这个函数的功能，即ip范围到cidr的生成是否准确。

测试case需要丰富一些，我看你目前的case里没有覆盖一个range导出多个cidr的情况

2024-08-16 10:53 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/testIpSegmentToCidr/main_test.go
> +func range2cidrList(startIp string, endIp string, country string, province string, city string, isp string, f *os.File) {
新的提交独立出range2cidr ( )函数 专门做ip网段转换cidr列表。 专门对range2cidr ( )函数做了单元测试，并且单元测试程序和转换程序放在了同一个目录下。丰富了单元测试的case，加入了转出多个cidr 的case，和一些特殊ip网段的case。请review一下。多谢

2024-08-18 06:37 UTC, johnlanni approved these changes
LGTM

2024-08-22 05:48 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Errorf("ipv6 and will be implemented in the future.%s %s", clientIp, config.IpProtocol)
"ipv6 and" 为啥有个 and？

看上去 config.IpProtocol 理论上是可以为空的。这里输出他有什么必要性吗？

2024-08-22 05:48 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Errorf("xff header: %s", xffHdr)
为啥这儿是 Errorf？

2024-08-22 05:48 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +			log.Errorf("client ip:%s", clientIp)
为啥这儿是 Errorf？

2024-08-22 05:48 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	xffHdr, err := proxywasm.GetHttpRequestHeader("x-forwarded-for")
请求里一定会有 xff 吗？

2024-08-25 08:57 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/main.go
> +			log.Errorf("client ip:%s", clientIp)
https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ip-restriction

参考下这个插件的配置和实现方式，支持下用户自己设置IP的获取方式

2024-08-25 08:59 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	proxywasm.AddHttpRequestHeader("X-Higress-Geo-Isp", geoIpData.Isp)
做一下urlencode吧

2024-08-26 05:48 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	xffHdr, err := proxywasm.GetHttpRequestHeader("x-forwarded-for")
插件里做了判断，如果xff 请求头不存在就取remote_address 对端ip。

https://github.com/alibaba/higress/blob/d5b49b8cd6fc812a08f2dc518b5e478497e91dec/plugins/wasm-go/extensions/geo-ip/main.go#L117-L132

2024-08-27 03:38 UTC, johnlanni commented on plugins/wasm-go/extensions/geo-ip/README.md
> +|  ip_protocol    |  string     |  否     |   ipv4             |  ip协议版本，不区分大小写。可填写的值：ipv4 或者 ipv6                     |
这个不用让用户配置了，解析ip的时候发现不是ipv4地址的时候，代码里打个warn日志就可以了

2024-08-27 06:29 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-geo-ip.go
> +						Path:             "/info",
```suggestion
						Path:             "/get",
```

2024-08-27 06:40 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-geo-ip.go
> +					ExpectedResponseNoRequest: true,
```suggestion
					ExpectedResponseNoRequest: false,
```

2024-08-27 06:41 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-geo-ip.go
> +					ExpectedResponseNoRequest: true,
```suggestion
					ExpectedResponseNoRequest: false,
```

2024-08-28 02:26 UTC, CH3CHO requested changes

2024-08-28 02:26 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Infof("added geoip data into radixtree: %v", *geoIpData)
这个日志量会不会有点大？

2024-08-28 02:26 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +			Cidr:     "",
这里感觉可以返回对应“内网”的 CIDR 吧？虽然其实这个 Internal 也不全是内网。

2024-08-30 08:57 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	IpProtocol   string `json:"ip_protocol"`
你好，是的。但是我想在代码里保留它是为了以后扩展通过ipv6地址查询用户地理位置信息。

2024-08-30 09:07 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	IpProtocol   string `json:"ip_protocol"`
可以是可以的，不过有必要单独加个配置让用户去选择。如果用户配置了 IpProtocol = ipv6，那么插件是只处理 IPV6 的 IP 吗？

2024-08-30 09:11 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +var internalIpCidr []string = []string{"0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/11", "100.96.0.0/12",
您好，代码里列出的内网cidr是根据ip2region 项目https://gitee.com/lionsoul/ip2region里ip.merge.txt ip地理位置数据库的内网ip网段，经过我写的ip网段转换多个cidr的程序 geo-ip/generateCidr/ipRange2Cidr.go   转换成的cidr地址。这个转换程序通过了test case 测试用例。

2024-08-30 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +var internalIpCidr []string = []string{"0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/11", "100.96.0.0/12",
嗯，这里我保留意见吧。

2024-08-30 09:18 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	IpProtocol   string `json:"ip_protocol"`
目前如果用户配置了IpProtocol = ipv6，插件会打印日志”以后将会现实ipv6查找地理位置信息“，然后让请求经过后续插件。 好的。之前是让用户通过配置参数IpProtocol  选择ip协议，后来感觉目前没必要就给删除了。我再加上。

2024-08-30 09:21 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	IpProtocol   string `json:"ip_protocol"`
问题就是这个配置的描述不清楚。我配成 ipv6，那就不支持 ipv4 了吗？

2024-08-30 09:22 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Infof("added geoip data into radixtree: %v", *geoIpData)
这个日志虽然会给每个cidr行解析时候打印一行日志，但是通过插件里的全局变量标志，只有第一次开启geo-ip插件时候会读入并且解析cidr地理位置信息到radixtree内存里和打印日志。 不过为了减少日志量，我在代码里注释掉它。

2024-08-30 09:24 UTC, CH3CHO commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Infof("added geoip data into radixtree: %v", *geoIpData)
因为 Wasm 插件是线程粒度的，会输出好几份的。要做的话最好也是搞个开关，默认不输出，或者Debug级别。

2024-08-30 09:27 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +			Cidr:     "",
好的。我当时想着只要说明是内网就行，不过写cidr更精确，我加到代码里。

2024-08-30 09:31 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +		log.Infof("added geoip data into radixtree: %v", *geoIpData)
明白了，higress以后是多线程，每个线程会加载插件和处理请求，类似traffic server缓存服务。那我注释掉它。

2024-08-30 09:35 UTC, ranxuxin001 commented on plugins/wasm-go/extensions/geo-ip/main.go
> +	IpProtocol   string `json:"ip_protocol"`
之前在README写了IpProtocol 的配置描述，后来删除了。我再加回来。如果用配置了ipv6，那么以后实现ipv6查找地理信息后，只会把ipv6的用户请求查找出地理信息，传递给后续插件。

2024-08-31 08:07 UTC, CH3CHO approved these changes

2024-09-01 01:04 UTC, merged