feat: support wasm-assemblyscript sdk
alibaba/higress pull request #1175
Opened 2024-08-05 09:55 UTC by Jing-ze

### Ⅰ. Describe what this PR did
加入wasm-assemblyscript sdk让开发者可以通过AssemblyScript语言写wasm插件

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-05 11:45 UTC, johnlanni commented
cc @heimanba

2024-08-12 05:46 UTC, johnlanni requested changes
整理一下目前sdk和wasm-go的能力差异，把TODO项整理一个issue吧

2024-08-12 05:46 UTC, johnlanni commented on plugins/wasm-assemblyscript/assembly/rule_matcher.ts
> +
https://github.com/alibaba/higress/blob/04a91040628ae725916119bb133e80131cd62c33/plugins/wasm-go/pkg/matcher/rule_matcher.go#L48-L49

匹配服务生效，以及匹配路由名前缀生效也得实现下

2024-08-12 05:46 UTC, johnlanni commented on plugins/wasm-assemblyscript/extensions/custom-response/index.html
> +<!DOCTYPE html>
这个html文件是必须的吗，不是必须的话可以去掉

2024-08-12 05:46 UTC, johnlanni commented on plugins/wasm-assemblyscript/assembly/plugin_wrapper.ts
> +  SetContext(key: string, value: usize): void;
value只能是usize类型吗，使用场景很有限

2024-08-12 09:17 UTC, Jing-ze commented
> 整理一下目前sdk和wasm-go的能力差异，把TODO项整理一个issue吧
issue #1199

2024-08-13 07:31 UTC, johnlanni approved these changes
LGTM

2024-08-13 07:31 UTC, merged