feat: ai敏感词拦截插件
alibaba/higress pull request #1190
Opened 2024-08-08 09:19 UTC by 007gzs

### Ⅰ. Describe what this PR did
ai敏感词拦截插件 

### Ⅱ. Does this pull request fix one issue?

#1182

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-08 09:33 UTC, johnlanni requested changes

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                if message.contains(deny_word) {
敏感词过滤仅用contain是不够的，需要用DFA算法

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                return self.deny();
response header阶段已经返回响应码了，这里再send local response会有问题，直接中断返回就好了

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +        if self.stream {
这个json让用户自己配是不是就可以了，这样就可以兼容非ai场景了

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/Cargo.toml
> +name = "ai-data-masking"
插件名字是否改成 data-masking，非ai场景也可以使用

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/README.md
> +| -------- | --------  | -------- | -------- |
扩展两个配置字段，分别支持JSON Path的方式提取请求 or 响应body里的某个字段进行处理。如果不配置，则对整个body进行处理

2024-08-08 09:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +    fn on_http_response_body_ok(&mut self, res_body: &Bytes) -> Action {
这个是缓存body进行处理，需要支持流式masking的能力

2024-08-08 09:42 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                if message.contains(deny_word) {
大字典使用jieba里的tiretree匹配的，这里处理的是配置文件的少部分敏感词

2024-08-08 09:51 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +    fn on_http_response_body_ok(&mut self, res_body: &Bytes) -> Action {
这个stream:true场景我可以做成先返回，内存里缓存body，如果从缓存的body里解析出需要拦截就直接断开，但是可能一部分已经返回给用户了

2024-08-08 09:51 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/README.md
> +| -------- | --------  | -------- | -------- |
stream:true这种场景没想好怎么配置

2024-08-08 09:53 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                return self.deny();
done

2024-08-08 09:54 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                if message.contains(deny_word) {
配置文件目前有大小限制么？如果配置文件可以到比较大的话这里我也可以直接加到jieba里

2024-08-08 10:20 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +    fn on_http_response_body_ok(&mut self, res_body: &Bytes) -> Action {
还有替换恢复的场景如果一个词分在两个chunk里的话也没法恢复了

2024-08-09 03:33 UTC, johnlanni requested changes

2024-08-09 03:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/README.md
> +| -------- | --------  | -------- | -------- |
stream场景可以不支持json path提取

2024-08-09 03:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                if message.contains(deny_word) {
配置文件大小没有限制，但总内存有1g限制。

2024-08-09 03:33 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +    fn on_http_response_body_ok(&mut self, res_body: &Bytes) -> Action {
先返回，再缓存body这个我觉得可以的。恢复这个可以文档里说明下，对于流式masking场景可能恢复失败

2024-08-12 03:45 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +                if message.contains(deny_word) {
done

2024-08-12 03:46 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +        if self.stream {
done

2024-08-12 03:46 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/README.md
> +| -------- | --------  | -------- | -------- |
done, 支持openai, jsonpath, rawbody三种模式

2024-08-12 03:46 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/src/lib.rs
> +    fn on_http_response_body_ok(&mut self, res_body: &Bytes) -> Action {
down

2024-08-12 03:50 UTC, 007gzs commented on plugins/wasm-rust/extensions/ai-data-masking/Cargo.toml
> +name = "ai-data-masking"
目前拦截模式单独有一个openai，这个名字还需要改么？需要的话我改下

2024-08-13 07:36 UTC, johnlanni requested changes
麻烦再补一个e2e测试用例，可以用custom-response插件来定义响应，来验证响应的masking效果

2024-08-15 12:32 UTC, 007gzs commented
> 麻烦再补一个e2e测试用例，可以用custom-response插件来自定义响应，来验证响应的masking效果

done

2024-08-16 06:19 UTC, johnlanni requested changes

2024-08-16 06:19 UTC, johnlanni commented on plugins/wasm-rust/extensions/ai-data-masking/README.md
> +# 替换测试
文档建议再优化一下，让用户更容易直观理解这个插件的作用，最好有个概括的说明，有时序图就最好了（mermaid）

2024-08-16 09:24 UTC, johnlanni approved these changes
LGTM, Thanks!

2024-08-16 09:24 UTC, merged