feat: add ai-agent plugin
alibaba/higress pull request #1192
Opened 2024-08-09 07:49 UTC by xingyunyang01

### Ⅰ. Describe what this PR did
Add ai-agent plugin，the first version only supports APIs where the http method is configured as GET.

### Ⅱ. Does this pull request fix one issue?

#1174 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-09 07:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1192) it.</sub>

2024-08-13 07:28 UTC, johnlanni requested changes

2024-08-13 07:28 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-agent/main.go
> +						"/compatible-mode/v1/chat/completions",
这里直接写死dashcopeclient，直接用qwen不太好。
我建议可以让用户自己指定服务，以及路径，这样用户甚至可以把网关自身（localhost）作为一个服务，然后复用网关的AI Proxy能力，对接不同的模型

2024-08-13 08:20 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +						"/compatible-mode/v1/chat/completions",
已修改将dashscope改成了llm，增加了path和model两个字段

2024-08-13 09:14 UTC, hanxiantao requested changes

2024-08-13 09:14 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/README.md
> +一个可定制化的API AI Agent，目前第一版本只支持配置http method类型为GET的API。agent流程图如下：
README的格式可以参考下ai-proxy的方便后续放到官网上

2024-08-13 09:14 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/README.md
> +
帮忙补充下本插件目前仅支持非流式模式

2024-08-13 09:14 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/dashscope/message.go
> +	MessageStore = make(ChatMessages, 0)
MessageStore这个目前是存在内存里的，如果网关部署两个实例的话，就会有问题，可以在README里说明下目前只支持单机，后续会支持通过redis存储回话记录

2024-08-13 09:14 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/main.go
> +		apiClient := wrapper.NewClusterClient(wrapper.DnsCluster{
目前插件的HttpClient这块都建议使用wrapper.FQDNCluster，这样可以兼容各种服务来源的配置，配置名称可以从serviceName调整为serviceFQDN

2024-08-13 09:14 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/main.go
> +	log.Info("onHttpRequestHeaders start")
调试的相关日志可以调整为debug级别

2024-08-13 12:39 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/README.md
> +一个可定制化的API AI Agent，目前第一版本只支持配置http method类型为GET的API。agent流程图如下：
已修改

2024-08-13 12:39 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/README.md
> +
已修改

2024-08-13 12:39 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/dashscope/message.go
> +	MessageStore = make(ChatMessages, 0)
已修改

2024-08-13 12:39 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +		apiClient := wrapper.NewClusterClient(wrapper.DnsCluster{
已修改

2024-08-13 12:39 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +	log.Info("onHttpRequestHeaders start")
已修改

2024-08-13 13:22 UTC, hanxiantao requested changes

2024-08-13 13:22 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/main.go
> +func firstreq(config PluginConfig, prompt string, rawRequest Request, log wrapper.Log) types.Action {
firstReq吧

2024-08-13 13:22 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/main.go
> +func parseConfig(gjson gjson.Result, c *PluginConfig, log wrapper.Log) error {
这个文件里目前代码有点多，可以考虑把配置解析的方法搞个config.go文件来处理，可以参考下ai-token-ratelimit插件里的处理

2024-08-13 13:22 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-agent/main.go
> +					// for _, v := range dashscope.MessageStore {
多余的代码可以删掉

2024-08-14 01:20 UTC, hanxiantao commented
@xingyunyang01 代码调整好了可以这里点下Re-request review
![image](https://github.com/user-attachments/assets/2fc01bb6-06dc-4f42-a542-26ea27c62b4c)

2024-08-14 01:35 UTC, hanxiantao commented
LGTM

2024-08-14 12:05 UTC, johnlanni requested changes

2024-08-14 12:05 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-agent/main.go
> +	return types.HeaderStopIteration
这里的注释是从ai cache插件copy过来的吗？
ai cache插件在header阶段返回 types.HeaderStopIteration 是因为需要停止header的处理，避免将header发给后端服务，要等到完整body收到后判断之后再继续后续处理。
这个插件应该没有这个需求？

2024-08-14 12:33 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +	return types.HeaderStopIteration
对 是直接copy的，已经参考别的插件改成直接返回types.ActionContinue了

2024-08-15 09:05 UTC, merged