feat: add Ai quota plugin
alibaba/higress pull request #1200
Opened 2024-08-12 10:05 UTC by 2456868764

### Ⅰ. Describe what this PR did
add ai-quota plugin

### Ⅱ. Does this pull request fix one issue?

fixes #1154

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-12 12:31 UTC, johnlanni requested changes

2024-08-12 12:31 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-quota/README.md
> +- credential: "Bearer credential1"
不用配置 credential 和 key，这里的 consumer 识别可以直接复用 key-auth 等认证插件认证后设置的请求header: x-mse-consumer

2024-08-12 12:31 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-quota/main.go
> +	return types.ActionPause
使用了proxy_wasm_0_2_100之后，如果想同时停止请求头和请求body处理，直到callback返回，这里不能返回 ActionPause，而是应该返回 types.HeaderStopAllIterationAndWatermark

2024-08-12 12:31 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-quota/main.go
> +
获取token可以参考这段代码，直接复用ai statistics插件计算出的token：
https://github.com/alibaba/higress/blob/6b9dabb4890c59c6424d604342ffa6479a019be2/plugins/wasm-go/extensions/ai-token-ratelimit/main.go#L140-L150

2024-08-13 08:24 UTC, 2456868764 commented on plugins/wasm-go/extensions/ai-quota/main.go
> +	return types.ActionPause
这里正常的 chat completion 逻辑，传递到下个插件前，检查 quota是否还有余额，如何没有余额，就直接返回，这里用 types.ActionPause 是 OK的。

2024-08-13 08:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-quota/main.go
> +	return types.ActionPause
还是会进当前插件的body阶段，我觉得可能对未来扩展会留坑，还是建议改成 types.HeaderStopAllIterationAndWatermark

2024-08-13 08:36 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-quota/main.go
> +	return types.ActionPause
进了body阶段之后，如果body阶段返回continue，就自动resume了，也不会等callback返回

2024-08-14 05:40 UTC, johnlanni approved these changes
LGTM

2024-08-14 05:43 UTC, merged