feat(plugin) add ai-history plugin
alibaba/higress pull request #1224
Opened 2024-08-18 12:05 UTC by yuemingming

### Ⅰ. Describe what this PR did
实现 ai-history 插件，支持自动填充历史对话，以及查询历史对话。

### Ⅱ. Does this pull request fix one issue?

fixes #1193 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-18 12:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1224) before we can accept your contribution.<br/><hr/>**sakura** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1224) it.</sub>

2024-08-19 13:38 UTC, hanxiantao requested changes

2024-08-19 13:38 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/README.md
> +> 需要数据面的proxy wasm版本大于等于0.2.100
这个插件使用 proxy wasm 0.2.100 这个ABI，需要在目录下放这个文件指明，参考：
https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-cache/.buildrc

2024-08-19 13:38 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/README.md
> +| cacheKeyPrefix    | string  | optional    | "higress-ai-history:" | Redis缓存Key的前缀                                                             |
会话历史的缓存可以考虑加下过期时间的设置

2024-08-19 13:38 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/README.md
> +## 简介
README的格式可以参考下ai-proxy的方便后续放到官网上

2024-08-19 13:38 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/main.go
> +		wrapper.ProcessStreamingResponseBodyBy(onHttpResponseBody),
这里是不是少了非流式请求的处理 wrapper.ProcessResponseBodyBy

2024-08-19 13:49 UTC, hanxiantao requested changes

2024-08-19 13:49 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/main.go
> +	"encoding/json"
调整下go import的顺序吧，代码编辑器一般都有这个设置
goland的话可以参考下这个：https://blog.csdn.net/t949500898/article/details/123330231

2024-08-19 13:56 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +		wrapper.ProcessStreamingResponseBodyBy(onHttpResponseBody),
37行。流式和非流式使用同一个方法。

2024-08-19 14:38 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +		wrapper.ProcessStreamingResponseBodyBy(onHttpResponseBody),
新增了 ProcessResponseBodyBy，但是走不到对应的逻辑。这个需要再看一下。

2024-08-19 14:46 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/README.md
> +> 需要数据面的proxy wasm版本大于等于0.2.100
已更新

2024-08-19 14:47 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/README.md
> +| cacheKeyPrefix    | string  | optional    | "higress-ai-history:" | Redis缓存Key的前缀                                                             |
已增加可选项，默认不过期，可配置。

2024-08-19 14:47 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/README.md
> +## 简介
已修改

2024-08-19 15:10 UTC, yuemingming commented
> > [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/alibaba/higress?pullRequest=1224) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1224) before we can accept your contribution.
> > **sakura** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1224) it.
> 
> @yuemingming 这个记得处理下

已处理

2024-08-20 03:00 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-history/README.md
> +
帮忙补充下填充历史后的requestBody效果吧

2024-08-20 09:46 UTC, johnlanni requested changes

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
response阶段应该不能直接通过 ctx.Path 取到请求路径的，需要自己在header阶段获取后存到ctx里

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/README.md
> +**获取历史数据示例：**
这个是用于debug的对吧，文档要说明清楚一些

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	return strings.Contains(path, "ai-history/query")
不要hardcode这个path，要支持让用户可以自己配置

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +			} else {
这个debug接口没必要支持stream方式返回吧？

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +// @Example
这段example不对吧？

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	MaxHistoryCnt            = 100
这个最大上下文历史为什么不直接基于fillHistoryCnt呢，否则存进去的也用不到，似乎没有意义？

2024-08-20 09:46 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +		finalChat := append(chat, currMessage...)
是否应该判断下message是否有重复，因为用户可能开了history插件后，仍然请求时带了上下文，这样会有重复的message

2024-08-20 09:46 UTC, johnlanni commented
@yuemingming 加一下我钉钉：chengtanzty

2024-08-20 09:53 UTC, hanxiantao commented
可能还需要考虑下如何兼容OpenAI的多模态的协议

```shell
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What'\''s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }'
```

请求里content字段是数组 可以参考下 #1221 里的处理 

或者后续我这边完善下这块也可以

2024-08-20 13:49 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
从实际结果看是可以拿到的。

2024-08-20 13:50 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/README.md
> +**获取历史数据示例：**
用户也可以选择用来做对话上下文的恢复，看一下需不需要提供这个能力。

2024-08-20 13:51 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	return strings.Contains(path, "ai-history/query")
这个配置的场景感觉比较少，担心和用户路径冲突？

2024-08-20 13:52 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +			} else {
对，这个应该不需要。

2024-08-22 03:42 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	return strings.Contains(path, "ai-history/query")
hardcode也可以，文档里要说明清楚，现在文档里只给了个请求例子

2024-08-22 03:50 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
哦 请求header阶段返回了header stop iteration，这样确实可以拿到

2024-08-22 03:52 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +	MaxHistoryCnt            = 100
但是存了不使用，浪费redis内存

2024-08-22 03:53 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +		for len(chat) >= 2 && len(currMessage) >= 3 {
为什么是历史对话数至少两条，当前message数至少3条的时候进行判断？另外这个需要补充单测

2024-08-22 13:24 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	MaxHistoryCnt            = 100
可以，那可以按照 FillHistoryCnt 为基准。

2024-08-22 13:26 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	return strings.Contains(path, "ai-history/query")
功能说明那一段给了说明。
「路径后缀匹配 `ai-history/query` 时，会返回历史对话」

2024-08-22 13:27 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +		for len(chat) >= 2 && len(currMessage) >= 3 {
逻辑是历史缓存的对话一定是一问一答，如果提交的消息中包含之前的对话信息，也一定存在至少历史的一问一答。

2024-08-25 08:53 UTC, johnlanni requested changes

2024-08-25 08:53 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-history/main.go
> +func DistinctChat(chat []ChatHistory, currMessage []ChatHistory) []ChatHistory {
这段逻辑，如果用户用了提示词修饰插件，可能会导致序号对不上。我建议改成简单处理，在currmesage里找是否有了 chathistory，有就不添加

2024-08-26 08:58 UTC, CH3CHO requested changes

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +			log.Errorf("redis get question:%s failed, err:%v", question, err)
这里建议把 question 换一行输出，万一 question 很长，这个日志就没法看了。

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		log.Error("redis access failed")
这里把 error 和 key 都输出出来吧

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +func getIntQueryParameter(defaultValue int, path string, name string) int {
你这个参数的顺序设定有点东西

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		log.Infof("start to replace request body, parameter:%s", string(parameterJson))
这个输出 Info 级别会不会有点长？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		parameterJson, _ := json.Marshal(parameter)
这里确定不会报错么。。。

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		_ = json.Unmarshal([]byte(chatHistories), &chat)
这里确定不会报错吗？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +	log.Infof("start to Set history, identityKey:%s, chat:%s", identityKey, string(str))
这里输出 Info 会不会太长？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +	str, _ := json.Marshal(chat)
这里确定不会报错吗？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		chat = chat[len(chat)-config.FillHistoryCnt*2:]
这里的意思是说用户不可以通过参数指定比 `config.FillHistoryCnt` 的填充量？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +		ctx.SetContext(StreamContextKey, struct{}{})
如果返回的不是 stream，是不还是 buffer response body 之后整体处理更简单？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
如果判断是 QueryHistory 请求，是不是可以直接不读 body 了？

2024-08-26 08:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +func fillHistory(chat []ChatHistory, currMessage []ChatHistory, fillHistoryCnt int) []ChatHistory {
我觉得这段去重的逻辑需要调整一下。比如以下对话：

U：请介绍一下XXX。
A：Blah Blah Blah
U：请展开一下
A：Blah Blah Blah
U：请展开一下
A：Blah Blah Blah

直接把后面两个 U 给去重了可能不是一个合适的操作吧。

2024-08-26 11:04 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/README.md
> +返回三个历史对话,如果未传入 cnt 默认返回所有缓存历史对话。
默认返回所有，但是存储的上限不会超过 fillHistoryCnt.

2024-08-26 11:07 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +		chat = chat[len(chat)-config.FillHistoryCnt*2:]
是的，不能超过 FillHistoryCnt

2024-08-26 11:17 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +func fillHistory(chat []ChatHistory, currMessage []ChatHistory, fillHistoryCnt int) []ChatHistory {
我觉得去重这个逻辑可以简化成如果存在超过一个 user 的输入，那么认为用户在自己控制上下文。就无需填充。毕竟只是一个兜底，不要做的太难理解。

2024-08-26 11:24 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
理论上是的，因为都是需要获取 Redis 中的数据，所以两个的处理统一写到了 Body 的处理阶段。

2024-08-26 12:06 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-history/main.go
> +func fillHistory(chat []ChatHistory, currMessage []ChatHistory, fillHistoryCnt int) []ChatHistory {
可以的，简单一点。

2024-08-26 12:20 UTC, yuemingming commented on plugins/wasm-go/extensions/ai-history/main.go
> +	if isQueryHistory(ctx.Path()) {
> > 理论上是的，因为都是需要获取 Redis 中的数据，所以两个的处理统一写到了 Body 的处理阶段。
> 
> 我的意思是，是不是可以不用读ResponseBody了。

是的，已修改

2024-08-27 11:24 UTC, johnlanni approved these changes
LGTM

2024-08-27 11:24 UTC, merged