feat: add ai-workflow plugin
alibaba/higress pull request #1229
Opened 2024-08-19 13:47 UTC by lixf311

### Ⅰ. Describe what this PR did
Add ai-workflow plugin，the first version only supports tools.

### Ⅱ. Does this pull request fix one issue?

fixes #1225 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-19 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1229) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1229) before we can accept your contribution.<br/><hr/>**lixf311** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1229) it.</sub>

2024-08-20 08:19 UTC, johnlanni commented
@lixf311 上面的CLA要签署一下

2024-08-20 09:08 UTC, johnlanni requested changes

2024-08-20 09:08 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +        - "check-cache-input||@all"
这里我没看懂，service_body_tmpl 里指定了从 embedding tool 的输出里解析，这里为什么又从 check-cache 的输入里获取去覆盖呢？

2024-08-20 09:11 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +				for _, serviceBodyReplaceKey := range serviceBodyReplaceKeys.Array() {
replace key里依赖的如果是自己的output，或者后置tool的input是否可以做配置检查和报错？

2024-08-20 09:12 UTC, johnlanni commented
@lixf311 加一下我钉钉吧：chengtanzty

2024-08-21 10:21 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +// 通过正泽表达式寻找模板中的 ｛｛foo｝｝ 字符串foo
重新写了readme

2024-08-21 10:22 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +| service_headers | 二维array | 选填   |     | 请求的头               |                     |
已修改为object

2024-08-21 10:22 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +外部工具，封装了httpCall，所以外部工具提供http的访问能力，获取各种api的能力。request body支持模板。
更新了文档，重新做了设计

2024-08-21 10:23 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +| service_body_tmpl   | string        | 选填 |     | 请求的body模板          |               |
更新了文档， 为空的时候直接发送模板，不进行替换，方便那种固定请求的情况。

2024-08-21 10:23 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +| service_body_replace_keys|二维 string array| 选填|   请求body模板替换键值对  |   用来构造请求。前面一个表示填充的位置，后面一个标识数据从哪里|               |
已经修改

2024-08-21 10:23 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +在模板里使用变量来代表数据和过滤。变量使用`{{str1||str2}}`包裹，使用`||`分隔，str1代表使用前面命名为name的操作(tool/model)。`name-input`或者`name-output` 代表它的输入和输出，str2代表如何取数据，过滤表达式基于 [GJSON PATH](https://github.com/tidwall/gjson/blob/master/S
更新了文档

2024-08-21 10:24 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +#### workflow.input 和 workflow.output
更新了文档，重新做了设计。

2024-08-21 10:33 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +        - "check-cache-input||@all"
这个地方重新做了设计，更新了代码。

2024-08-22 08:02 UTC, hanxiantao requested changes

2024-08-22 08:02 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/go.mod
> +module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow
module名称叫ai-workflow即可

2024-08-22 08:02 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +)
调整下go import的顺序吧，代码编辑器一般都有这个设置
goland的话可以参考下这个：https://blog.csdn.net/t949500898/article/details/123330231

2024-08-22 08:10 UTC, johnlanni requested changes

2024-08-22 08:10 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +	"eq": func(a, b float64) bool { return a == b },
只支持数值类型的比较吗？这种场景下字符串的比较可能更常见一些

2024-08-22 08:22 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +)
学习了，已经设置，感谢。

2024-08-22 08:24 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +	"eq": func(a, b float64) bool { return a == b },
可以加，应该没啥问题，我来想想增加哪些

2024-08-22 08:39 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +| service_type    | string                             | 必填 |     | 请求的类型                         | static，domain                 |
原来是这样，是我理解的不对，感谢指点，我来改下

2024-09-21 09:47 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/README.md
> +## 功能说明
已修改

2024-09-21 09:48 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	//初始化运行状态
已修改

2024-09-21 09:48 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	workflowExecStatus, err := initWorkflowExecStatus(config)
已放到了parseConfig里

2024-09-21 09:48 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	log.Errorf("init status : %v", workflowExecStatus)
已修改

2024-09-21 09:49 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	}, uint32(maxDepth)*5000)
这部分已经调整了，在config里加了一个timeout的配置项

2024-09-21 09:49 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/workflow/workflow.go
> +		}
已修改

2024-09-21 09:49 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/go.mod
> +module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow
已修改

2024-09-21 09:50 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +	"eq": func(a, b float64) bool { return a == b },
已经添加了字符串的比较

2024-09-21 09:50 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +var operators = map[string]interface{}{
我想了想，加上了and or这种能力，别的还在考虑ing

2024-09-23 05:16 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/go.mod
> +module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow
这里好像还是github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow，改成ai-workflow即可

2024-09-23 05:21 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +)
这里go import的顺序好像还是没有调整

2024-09-23 05:21 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	maxDepth           uint   = 100
建议maxDepth也参考timeout放到env中支持可配置，默认值为100

2024-09-23 05:21 UTC, hanxiantao commented on plugins/wasm-go/extensions/ai-workflow/go.mod
> +module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow
这里好像还是module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow，改成ai-workflow即可

2024-09-23 07:05 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +	maxDepth           uint   = 100
sry，import的顺序和go.mod的module名称都改了，这个地方也修改为可配置了

2024-09-23 07:23 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/main.go
> +)
已经修改

2024-09-23 07:23 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/go.mod
> +module github.com/alibaba/higress/plugins/wasm-go/extensions/ai-workflow
sry，我理解错了，已经修改

2024-09-23 08:04 UTC, hanxiantao approved these changes

2024-09-23 08:05 UTC, hanxiantao commented
LGTW

2024-09-25 08:39 UTC, hanxiantao commented
@johnlanni 有时间的话，也帮忙再看下

2024-10-08 05:36 UTC, johnlanni requested changes

2024-10-09 10:28 UTC, lixf311 commented on plugins/wasm-go/extensions/ai-workflow/utils/conditional.go
> +	},
抱歉，才看到，考虑有eq就不用ne了，删除了readme里的相关描述

2024-10-09 11:52 UTC, merged