[ai-json-resp] Extract JSON from LLM, Validate with Schema, Ensure Valid JSON, Auto-Retry
alibaba/higress pull request #1236
Opened 2024-08-21 02:56 UTC by Suchun-sv

### Ⅰ. Describe what this PR did
[ai-json-resp] LLM响应结构化插件，用于根据默认或用户配置的Json Schema对AI的响应进行结构化。和ai proxy插件协作，除自定义的json schema和网关服务外无需额外配置参数。

### Ⅱ. Does this pull request fix one issue?

fixes #1214

2024-08-21 03:35 UTC, johnlanni requested changes

2024-08-21 03:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| serviceName | str |  required | - | 网关服务名称 |
这里应该是任意支持 openai 的服务。然后可以给个操作说明，如何用网关自己的 ai proxy 能力对接其他不支持 openai 协议的服务，包括创建一个固定IP指向127.0.0.1的服务等。

2024-08-21 03:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| servicePort | int |  required | - | 网关服务端口 |
支持一下配置请求openai服务时用的url吧，包含域名和路径，当使用网关自己做这个服务时，也是需要的。可以创建一条特定域名和路径的路由，然后给这个路由配置上IP白名单，只允许127.0.0.1来访问

2024-08-21 03:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		sendResponse(ctx, log, nil, "")
这里不应该返回200了，应该返回500，并给出失败原因，在README里也说明下这个插件失败时的返回码

2024-08-21 03:35 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		sendResponse(ctx, log, nil, "")
另外建议用 sendHttpResponseWithDetail，这样可以增加跟响应码相关的状态信息，可以用于日志分析

2024-08-21 03:36 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +				recursiveRefineJson(ctx, config, log, retryCount, bufferRB)
validate 失败进行重试的时候打个info日志吧

2024-08-21 03:37 UTC, johnlanni requested changes

2024-08-21 03:37 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	err = compile.Validate(strings.NewReader(jsonStr))
重试时应该带上这个validate失败的信息，让LLM可以根据这个失败信息进行优化

2024-08-21 03:43 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	jsonSchemaBytes, _ := json.Marshal(config.jsonSchema)
jsonSchema是否允许配置为空，配置为空时，只校验是否是合法的json就可以

2024-08-21 03:52 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| serviceName | str |  required | - | 网关服务名称 |
应该不久局限于使用网关自己，可以配置任意支持openai协议的服务。只是对于用网关自身127.0.0.1的情况，文档里可以展开说一下如何配置的细节，比如创建固定IP指向127.0.0.1的服务等。

另外还应该支持配置 serviceUrl，可以提取出域名和路径，来拼接到 HTTP 请求的域名和path中去。因为即使是用网关做这个service，也需要支持用户创建一条特定路径的路由，并可能要给路由配置IP白名单策略只允许127.0.0.1来源的请求。

2024-08-23 03:18 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	rejStruct      RejStruct
rej 是 reject 吗？就差 4 个字母，我觉得是不是没必要省略。。。

2024-08-26 10:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| rejectOnDepthExceed | bool |  optional | false | 若为 true，当 JSON Schema 的深度超过 maxJsonSchemaDepth 时，插件将直接返回错误；若为 false，则将仍将Json Schema用于LLM提示构造并继续执行 |
exceeded？

2024-08-26 10:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +func (r RejectStruct) Byte() []byte {
Bytes？

2024-08-26 10:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +func (r RejectStruct) GetShortMsg() string {
为啥上面那个没有 Get 这个就有 Get 了？

2024-08-26 10:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	validJsonSchema bool
这个valid是什么词性。。

2024-08-26 13:25 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		sendResponse(ctx, log, nil, "")
已更改

2024-08-26 13:25 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +				recursiveRefineJson(ctx, config, log, retryCount, bufferRB)
已添加

2024-08-26 13:30 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	err = compile.Validate(strings.NewReader(jsonStr))
在ReplayBuffer结构中添加了HisMsg []chatMessage 成员变量, SaveHisStr 方法，若遇到错误时，会将错误作为str添加到HisMsg中 （role为system)。

```go
func (r *ReplayBuffer) SaveHisStr(log wrapper.Log, errMsg string) {
	r.HisMsg = append(r.HisMsg, chatMessage{
		Role:    "system",
		Content: errMsg,
	})
}
```

2024-08-26 13:33 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| serviceName | str |  required | - | 网关服务名称 |
已添加

2024-08-26 13:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	rejStruct      RejStruct
已修改

2024-08-26 13:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| rejectOnDepthExceed | bool |  optional | false | 若为 true，当 JSON Schema 的深度超过 maxJsonSchemaDepth 时，插件将直接返回错误；若为 false，则将仍将Json Schema用于LLM提示构造并继续执行 |
已修改

2024-08-26 13:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +func (r RejectStruct) Byte() []byte {
已修改为 `GetBytes()`

2024-08-26 13:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +func (r RejectStruct) GetShortMsg() string {
已修改为 GetBytes()

2024-08-26 13:35 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +			log.Infof("Json Schema depth exceed: %d, do not valid json schema", maxDepth)
修改为 `"Json Schema depth exceeded: %d from %d , not using Json schema for validation"`

2024-08-26 13:36 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		proxywasm.SendHttpResponseWithDetail(uint32(500), config.rejectStruct.GetShortMsg(), nil, config.rejectStruct.Byte(), -1)
定义了常量为：
```go
	httpStatusOK                  = uint32(200)
	httpStatusBadRequest          = uint32(400)
	httpStatusInternalServerError = uint32(500)
```

2024-08-26 13:36 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	log.Infof("Final send: Code %d, Message %s, Body: %s %s", config.rejectStruct.RejectCode, config.rejectStruct.RejectMsg, string(body))
已删除最后一个%s

2024-08-26 13:36 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/util.go
> +func MaxDepthIterative(data interface{}) int {
已修改

2024-08-27 03:36 UTC, CH3CHO requested changes

2024-08-27 03:36 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	useJSinVal    bool
这个 `useJSinVal` 是啥意思？是不是可以换一个命名？看不懂

2024-08-27 05:01 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	validJsonSchema bool
useJsinVal 展开是什么怎么个拼写？感觉还是很抽象啊

2024-08-27 06:36 UTC, CH3CHO commented
![image](https://github.com/user-attachments/assets/cb3bfca6-9ac1-40cd-a324-52203057da17)

2024-08-27 07:24 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	ReturnContentisEmpytCode     = 1004
已将常量的首字母改为小写

2024-08-27 07:24 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	ReturnJsonMisMatchSchemaCode = 1005
已修改

2024-08-27 07:25 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	ReachMeaxRetryCountCode      = 1006
已修改

2024-08-27 07:25 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	ServiceConfigNotValidCode    = 1008
已修改

2024-08-27 07:31 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		proxywasm.SendHttpResponseWithDetail(httpStatusInternalServerError, config.rejectStruct.GetShortMsg(), nil, config.rejectStruct.GetBytes(), -1)
是需要把现在的details全部转换为这个给定的list里的吗？比如”response body does not contain the valid json“这个是不是保留现在的解释会不会更清楚点呢？

2024-08-27 07:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		header = append(header, [2]string{"Content-Disposition", "attachment; filename=\"response.json\""})
因为返回的是json格式的响应，往往需要用于后续的下游任务。在浏览器里触发下载可以直接用于任务，不用再手动复制。

2024-08-27 07:34 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	// if retry count exceed max retry count, return the response
已修改

2024-08-27 07:38 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		config.rejectStruct = RejectStruct{ReachMeaxRetryCountCode, "retry count exceed max retry count:" + config.rejectStruct.RejectMsg}
但是这里的Msg主要是想通过response把错误返回给用户，其实还是response body。对应返回的Detail会通过split的方式只返回 ":"前面的部分，是需要单独写Detail比较好吗？
```go
proxywasm.SendHttpResponseWithDetail(httpStatusInternalServerError, config.rejectStruct.GetShortMsg(), nil, config.rejectStruct.GetBytes(), -1)

func (r RejectStruct) GetShortMsg() string {
	return "ai-json-resp." + strings.Split(r.RejectMsg, ":")[0]
}
```

2024-08-27 07:44 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		proxywasm.ResumeHttpRequest()
哦哦，和types.ActionContinue重复了。已删除这一行

2024-08-27 07:44 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	header, err := proxywasm.GetHttpRequestHeaders()
已修改

2024-08-27 07:46 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		header = append(header, [2]string{"Authorization", "Bearer " + config.apiKey})
前面做了检测header中是否有Authorization，若有则先删除

```go
apiKey, _ := proxywasm.GetHttpRequestHeader("Authorization")
if apiKey != "" {
// remove the Authorization header
proxywasm.RemoveHttpRequestHeader("Authorization")
}
```

2024-08-27 07:49 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	if url == "" {
这里的url是在处理header的时候存的，想处理的是不带路径的请求，可能改成path会更好理解一点？

```go
url, _ := proxywasm.GetHttpRequestHeader(":path")
ctx.SetContext("url", url)
```

2024-08-27 07:57 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	url        string
已修改

2024-08-27 08:02 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		config.servicePort = 443
这个地方要加上协议的判断吗？只有serviceUrl可以判断，但是serviceUrl并不是必输项，这里主要是想和README.md里的默认值匹配

2024-08-27 09:24 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		proxywasm.SendHttpResponseWithDetail(httpStatusInternalServerError, config.rejectStruct.GetShortMsg(), nil, config.rejectStruct.GetBytes(), -1)
因为details是会出现在access-log里的，建议是精简一点，尤其是accesslog可能会被用在grafana等看板上，太长不便于观看。

2024-08-27 09:25 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +		header = append(header, [2]string{"Authorization", "Bearer " + config.apiKey})
这里我的意思是 header 这个变量里如果有两个 Authorization，会不会有问题？

2024-08-27 10:13 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	contentisEmpytCode           = 1004
已修改

2024-08-27 10:31 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	jsonSchemaNotValidCode       = 1001
已修改

2024-08-27 23:01 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	header := ctx.GetContext("headers").([][2]string)
已修改

2024-08-27 23:02 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	path := ctx.GetContext("path").(string)
已修改

2024-08-27 23:05 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	config.serviceClient.Post(bufferRB.Path, bufferRB.ReqHeader, bufferRB.ReqBody,
这里有点没明白，您是指Post失败吗？那还会进入回调函数吗？如果会进入那应该已经写了处理？如果不会进入，那好像没法子处理r？

2024-08-27 23:07 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	isBuffer, err := proxywasm.GetHttpRequestHeader("isBuffer")
修改成了"[ai-json-resp]isBuffer”

2024-08-27 23:09 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	if isBuffer == "true" {
已修改

2024-08-30 09:41 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +				bufferRB.SaveHisStr(log, err.Error())
已修改为 `SaveStrToHistMsg` 和 `SaveBodyToHistMsg`

2024-08-30 09:42 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	isBuffer, err := proxywasm.GetHttpRequestHeader("isBuffer")
使用常量定义了extendHeaderKey，并在代码中调用
```go
extendHeaderKey               = "X-HIGRESS-AI-JSON-RESP"
```

2024-08-30 10:35 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/main.go
> +	contentisEmpytCode           = 1004
已添加开关 "enableContentDisposition", 默认为true

2024-08-30 13:30 UTC, CH3CHO approved these changes
LGTM

2024-08-31 09:25 UTC, johnlanni requested changes
配置需要做一些精简

2024-08-31 09:25 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| rejectOnDepthExceeded | bool |  optional | false | 若为 true，当 JSON Schema 的深度超过 maxJsonSchemaDepth 时，插件将直接返回错误；若为 false，则将仍将 Json Schema 用于LLM提示构造并继续执行 |
jsonSchemaMaxDepth 和 rejectOnDepthExceeded 这两个配置我建议去掉，最大深度在代码里有个默认值就行，文档里提示一下即可，默认行为就是超过最大深度，不用进行校验，但会生成提示词

2024-09-01 17:47 UTC, Suchun-sv commented on plugins/wasm-go/extensions/ai-json-resp/README.md
> +| rejectOnDepthExceeded | bool |  optional | false | 若为 true，当 JSON Schema 的深度超过 maxJsonSchemaDepth 时，插件将直接返回错误；若为 false，则将仍将 Json Schema 用于LLM提示构造并继续执行 |
ok，我修改一下代码和文档

2024-09-03 03:09 UTC, johnlanni approved these changes
LGTM

2024-09-03 03:10 UTC, merged