feature: add ai-intent plugin
alibaba/higress pull request #1237
Opened 2024-08-21 08:49 UTC by lizhou0

### Ⅰ. Describe what this PR did
实现LLM 意图识别插件，能够智能判断用户请求与某个领域或agent的功能契合度，从而提升不同模型的应用效果和用户体验

### Ⅱ. Does this pull request fix one issue?

fixes #1201 .

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-08-21 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1237) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1237) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1237) it.</sub>

2024-08-22 03:14 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/README.md
> +| `DashScope.Url`         | string          | 非必填     | /intent/api/v1/services/aigc/text-generation/generation      | 新建一条higress的大模型路由，供该插件使用,路由以/intent作为前缀 |
为啥是dashscope？而且还是qwen的url，用higress不应该用openai协议吗，配置字段名称也跟dashscope不应该有关系

2024-08-22 03:22 UTC, johnlanni requested changes

2024-08-22 03:22 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/main.go
> +	log.Info("Init ai intent's components successfully.")
类似的日志等级都调整成debug

2024-08-22 03:22 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/main.go
> +		}, 10000)
超时时间要支持配置

2024-08-22 03:22 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/main.go
> +	return types.ActionContinue
应该使用 types.HeaderStopIteration，停止 header 处理，接收 body，否则请求已经发给后端了。
注意使用这个功能需要参考这个issue编译：
https://github.com/alibaba/higress/issues/1232#issuecomment-2300544065
另外，注意项目下增加这个文件：
https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-proxy/.buildrc

2024-08-22 03:22 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/main.go
> +					category := DashScopeResponseBody.Choices[0].Message.Content
直接用这个content，不能确保取值一定是枚举值

2024-08-22 05:52 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-intent/README.md
> +| `DashScope.Url`         | string          | 非必填     | /intent/api/v1/services/aigc/text-generation/generation      | 新建一条higress的大模型路由，供该插件使用,路由以/intent作为前缀 |
字段名字是不应该小写开头？

2024-08-22 05:52 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-intent/README.md
> +| `Scene.Category`         | string          | 必填     | -      | 预设场景类别 |
这个category配成一个数组是不是更便于使用？

2024-08-22 05:52 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-intent/main.go
> +func DashScopeResponseHandle(ctx wrapper.HttpContext, responseBody []byte, log wrapper.Log) (*DashScopeResponse, error) {
用Handle的话就要放前面，放后面的话就要叫Handler

2024-08-22 10:06 UTC, lizhou0 commented
@johnlanni @CH3CHO 代码已更新，相关内容整理如下：
1.为啥是dashscope？而且还是qwen的url，用higress不应该用openai协议吗，配置字段名称也跟dashscope不应该有关系。
readme中的url值当时未更新，现在统一调整了配置的字段名称，与dashscope无关。
2.类似的日志等级都调整成debug。
已修改
3.超时时间要支持配置。
已修改
4.应该使用 types.HeaderStopIteration，停止 header 处理，接收 body，否则请求已经发给后端了。
已修改
5.直接用这个content，不能确保取值一定是枚举值。
在给大模型的提问中明确指出了“直接返回一种具体类别，如果没有找到就返回'NotFound'。”，并且添加了返回结果是否包含在category中。
6.字段名字是不应该小写开头？
已修改
7.这个category配成一个数组是不是更便于使用？
category该字段的值会直接拼装在向大模型提问的 Prompt 预设问题中
8.用Handle的话就要放前面，放后面的话就要叫Handler。
已修改
9.新增[.buildrc](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-proxy/.buildrc)文件。
已修改

2024-08-22 10:27 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-intent/README.md
> +> 3.需新建一个固定地址的服务（如：intent-service），服务指向127.0.0.1:80 （即自身网关实例+端口），ai-intent插件内部需要该服务进行调用，以访问上述新增的路由,对应 DashScope.DashScopeServiceName
这儿还是 dashscope 啊

2024-08-22 10:27 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-intent/README.md
> +  proxyServiceName: "intent-service"
这里测试过吗，Higress 上配出来的 service name 应该不长这样吧？

2024-08-22 10:29 UTC, CH3CHO commented
> category该字段的值会直接拼装在向大模型提问的 Prompt 预设问题中

这个是内部的实现细节，我们是否需要对用户暴露？

2024-08-22 10:36 UTC, lizhou0 commented on plugins/wasm-go/extensions/ai-intent/README.md
> +  proxyServiceName: "intent-service"
这个测试过的，也是根据 https://github.com/alibaba/higress/issues/1201  中的建议：可以不用配置dasahcope字段，只需定义服务即可，可以把网关自身作为一个服务（127.0.0.1）,然后复用网关的AI Proxy能力，统一用openai协议对接多个不同大模型。相当于这里添加了一个服务。

2024-08-22 10:38 UTC, lizhou0 commented
> > category该字段的值会直接拼装在向大模型提问的 Prompt 预设问题中
> 
> 这个是内部的实现细节，我们是否需要对用户暴露？

https://github.com/alibaba/higress/issues/1201#issuecomment-2285491096

2024-08-22 10:40 UTC, CH3CHO commented
> > > category该字段的值会直接拼装在向大模型提问的 Prompt 预设问题中
> > 
> > 
> > 这个是内部的实现细节，我们是否需要对用户暴露？
> 
> [#1201 (comment)](https://github.com/alibaba/higress/issues/1201#issuecomment-2285491096)

Fine.

2024-08-22 10:46 UTC, lizhou0 commented on plugins/wasm-go/extensions/ai-intent/README.md
> +> 3.需新建一个固定地址的服务（如：intent-service），服务指向127.0.0.1:80 （即自身网关实例+端口），ai-intent插件内部需要该服务进行调用，以访问上述新增的路由,对应 DashScope.DashScopeServiceName
抱歉，这里漏掉了，已更新

2024-08-23 13:59 UTC, lizhou0 commented
@johnlanni  Build and Test Plugins 失败，报错：unknown directive: toolchain。在go.mod初始化的时候go版本较高 ，已提交修改go版本为1.19(之前版本写的1.21)且删除了toolchain部分

2024-08-25 08:33 UTC, johnlanni requested changes

2024-08-25 08:33 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/README.md
> +| `llm.proxyUrl`         | string          | 非必填     | /intent/compatible-mode/v1/chat/completions      | 新建一条higress的大模型路由，供该插件使用,默认路由以/intent作为前缀 |
url的格式应该是类似：http://www.openai.com/v1/chat/completion
这样你可以从用户的配置里去同时解析出域名和path

2024-08-25 08:33 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/README.md
> +  proxyServiceName: "intent-service"
但是我看你的实现只支持了 static 类型的服务，实际上也可以让用户配 Dns cluster，直接访问到 openai 等服务。这里建议参考下其他插件，用FQDNCluster

2024-08-25 08:33 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-intent/main.go
> +					category := proxyResponseBody.Choices[0].Message.Content
这个实现是否应该判断 content 中是否包含 category 枚举值？因为有时候LLM可能有废话，不是正好content就只返回这个category值

2024-08-27 11:25 UTC, merged