ai-statistics插件新增自定义扩展指标上传功能，issue：1234
alibaba/higress pull request #1240
Opened 2024-08-21 11:16 UTC by shalldid

### Ⅰ. Describe what this PR did
ai-statistics插件新增自定义扩展指标上传功能

### Ⅱ. Does this pull request fix one issue?

fixes #1234

2024-08-21 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1240) before we can accept your contribution.<br/><hr/>**shalldid** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1240) it.</sub>

2024-08-21 11:18 UTC, shalldid commented
proxywasm.hostcall.go新增方法：
func (m MetricGauge) SetValue(value int64) {
    if err := internal.StatusToError(internal.ProxyRecordMetric(uint32(m), uint64(value))); err != nil {
        panic(fmt.Sprintf("set metric of %d: %v", uint32(m), err))
    }
}

2024-08-22 03:27 UTC, johnlanni commented
@shalldid CLA需要签署一下

2024-08-22 03:30 UTC, johnlanni requested changes

2024-08-22 03:30 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +		config.responseMetricConfig[i].path = TraceTagArray.Get("path").String()
实现的有问题，参考issue里的评论，先把issue调整好，达成一致再提交PR吧

2024-08-22 03:31 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +	return types.HeaderStopIteration
统计插件是旁路的，不需要阻塞请求header

2024-08-22 05:54 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/go.mod
> -replace github.com/alibaba/higress/plugins/wasm-go => ../..
这个 replace 为什么要删掉呢？

2024-08-22 07:46 UTC, shalldid commented on plugins/wasm-go/extensions/ai-statistics/go.mod
> -replace github.com/alibaba/higress/plugins/wasm-go => ../..
误删除。。。。

2024-08-22 07:48 UTC, shalldid commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +	return types.HeaderStopIteration
这里是因为之前想要在header里面加上请求开始时间，后来发现请求头里有时间统计实现了，这里的onHttpRequestHeaders()可以启用了，我这边修改后删除这个方法。

2024-08-22 07:49 UTC, shalldid commented on plugins/wasm-go/extensions/ai-statistics/go.mod
> -replace github.com/alibaba/higress/plugins/wasm-go => ../..
修改后还原go.mod

2024-08-23 09:56 UTC, closed without merging