Add x-forwarded-xxx for ext-auth
alibaba/higress pull request #1244
Opened 2024-08-22 12:08 UTC by SpecialYang

2024-08-22 12:18 UTC, hanxiantao requested changes

2024-08-22 12:18 UTC, hanxiantao commented on plugins/wasm-go/extensions/ext-auth/README.md
> +在endpoint_mode为envoy时，higress会自动生成并发送以下header至鉴权服务。
应该是endpoint_mode为forward_auth

2024-08-23 02:03 UTC, SpecialYang commented on plugins/wasm-go/extensions/ext-auth/README.md
> +在endpoint_mode为envoy时，higress会自动生成并发送以下header至鉴权服务。
done

2024-08-23 02:05 UTC, hanxiantao commented
LGTM

2024-08-23 02:57 UTC, hanxiantao approved these changes

2024-08-23 06:49 UTC, merged