feat: Add Chroma vector database support to ai-cache WASM Plugin
alibaba/higress pull request #1248
Opened 2024-08-25 06:46 UTC by EnableAsync

### Ⅰ. Describe what this PR did
This PR adds support for the Chroma vector database to the ai-cache WASM plugin. The primary goal is to enhance the plugin's capabilities for storing and retrieving vector data efficiently.

### Ⅱ. Does this pull request fix one issue?

Please refer to issue #1041.

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Test cases will be added later.

### Ⅳ. Describe how to verify it
After filling in the `apikey` and `ChromaCollectionID` in `docker-compose-test/envoy.yaml`, execute the following code:
```bash
cd docker-compose-test/
docker compose up
```
Then test it by accessing the LLM via cURL:
```bash
curl http://172.17.0.1:10000/v1/chat/completions -X POST -d '{"model":"gpt-4o-mini","messages":[{"content":"今天中午吃什么","role":"user"}]}' -H "Content-Type: application/json"
```

### Ⅴ. Special notes for reviews

2024-08-25 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1248) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: johnlanni<br/>:white_check_mark: Suchun-sv<br/>:x: EnableAsync<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1248) it.</sub>

2024-09-08 08:09 UTC, CH3CHO requested changes

2024-09-12 07:10 UTC, johnlanni requested changes
vector 和 embeding 部分代码比较通用，建议从 ai-cache 目录下挪出来，放到 wasm-go 的 ai-utils 目录下

2024-10-20 02:13 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-cache/vector/chroma.go
> +	return errors.New("[Chroma] QueryEmbedding Not implemented")
？？

2024-11-08 04:14 UTC, CH3CHO approved these changes
LGTM

2024-11-08 04:23 UTC, CH3CHO requested changes

2024-11-08 04:23 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-cache/vector/weaviate.go
> +	err = d.client.Post(
SaaS 版本的 Weaviate 似乎需要一个 API Key 才能访问。

2024-11-19 03:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-cache/README.md
> +需要提前创建 Collection。需要注意的是 Weaviate 会设置首字母自动大写，在填写配置 `collectionID` 的时候需要将首字母设置为大写。
这个 Weaviate 里好像是叫 class，不叫 collection。

2024-11-19 03:35 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-cache/README.md
> +需要提前创建 Collection。需要注意的是 Weaviate 会设置首字母自动大写，在填写配置 `collectionID` 的时候需要将首字母设置为大写。
其他几个 provider 的对应描述也调整一下吧。需要告知用户实际创建的是什么，需要把什么填入 collectionId 配置里。

2024-11-20 01:14 UTC, CH3CHO approved these changes
LGTM

2024-11-21 08:57 UTC, johnlanni approved these changes
LGTM

2024-11-21 08:57 UTC, merged