Update ai security guard
alibaba/higress pull request #1261
Opened 2024-08-29 11:47 UTC by rinfx

更新内容安全插件：
- 配置更新：用户可以选择只在request/response阶段检测，或者都检测。如果被内容安全拦截，根据请求是否为流式返回流式/非流式响应。如果response阶段进行检测，虽然响应是流式的，但是需要缓存所有的chunk提取大模型的完整回答进行检测，所以在前端页面上表现为非流式。
- 增加metrics以及span attributes供用户排查问题使用。

2024-08-31 01:20 UTC, CH3CHO requested changes

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README-en.md
> +| `checkresponse` | bool | optional | - | check if the output is leagal |
请标注默认值

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README-en.md
> +## 配置示例
应为英文

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README-en.md
> +| `serviceName` | string | requried | - | service name |
这里可以考虑直接用 serviceName + FQDNCluster，这样就不用配 serviceSource 了

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README-en.md
> +## observability
所有标题首字母应大写

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/go.mod
> +module ai-security-guard
go.mod 内容建议参考现有的插件配置：

https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-proxy/go.mod
![image](https://github.com/user-attachments/assets/277c6c25-33a8-4133-93f0-6d4606a65042)

2024-08-31 01:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +							jsonData = []byte(fmt.Sprintf(NormalResponseFormat, "很抱歉，我不能对您的问题做出回答。"))
这个默认回答抽个常量出来吧

2024-09-08 05:36 UTC, CH3CHO requested changes

2024-09-08 05:36 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
>  type StandardResponse struct {
这个 struct 没有用到了吗？

2024-09-09 08:20 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +| `checkResponse` | bool | optional | false | 检查大模型的回答内容是否合规，生效时会使流式响应变为非流式 |
这个倒不是技术上的问题，如果要流式返回的话，一个响应要调很多次阿里云内容安全服务了，成本太高了

2024-09-09 08:20 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README-en.md
> +| `checkResponse` | bool | optional | false | check if the output is leagal |
感谢董老师捉虫

2024-09-09 08:20 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +		config.client.Post(fmt.Sprintf("/?%s", reqParams.Encode()), [][2]string{{"User-Agent", "CIPFrom/AIGateway"}}, nil,
这个是阿里云内容安全要求添加的，用来标记从网关过去的调用

2024-09-09 08:21 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +							jsonData := []byte(fmt.Sprintf(NormalResponseFormat, respAdvice.Array()[0].Get("Answer").String()))
不会，一般就是 “作为一名人工智能助手，我不能提供涉及色情、暴力、政治等敏感话题的内容。如果您有其他相关问题，欢迎您提问。” 这种文本

2024-09-09 08:29 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
>  type StandardResponse struct {
这个确实没再用到了，我删除一下

2024-09-09 08:33 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +| `checkResponse` | bool | optional | false | 检查大模型的回答内容是否合规，生效时会使流式响应变为非流式 |
哦，技术上其实也有问题，stream里面发起http请求时，不能够返回actionpause等待请求执行完

2024-09-24 11:42 UTC, johnlanni approved these changes
LGTM

2024-09-24 11:42 UTC, merged