[frontend-gray] Increase gray types according to the ratio-weight gray
alibaba/higress pull request #1291
Opened 2024-09-09 16:34 UTC by heimanba

### Ⅰ. Describe what this PR did
1. 增加按照比例灰度的能力,YAML配置如下：
灰度规则 `beta-user`的灰度范围为 50%
```
baseDeployment: 
  version: "dev"
grayDeployments: 
- name: "beta-user"
  version: "0.0.1"
  enabled: "true"
  weight: "50"
```
2. 添加往首页注入脚本的能力
可以分别在 header，body的首部`first`和尾部`last`注入相关代码。
```
---
injection: 
  header: 
  - "<script>console.log('Header')</script>"
  body: 
    first: 
    - "<script>console.log('hello world before')</script>"
    - "<script>console.log('hello world before1')</script>"
    last: 
    - "<script>console.log('hello world after')</script>"
    - "<script>console.log('hello world after2')</script>"
```

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-09-10 12:17 UTC, CH3CHO requested changes

2024-09-10 12:17 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
debug情况就不做用户粘滞咯？

2024-09-10 13:02 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
> debug情况就不做用户粘滞咯？

是的是的，所以这个debug，命名为 `debugGrayWeight`了

2024-09-10 13:32 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `debugGrayWeight`     | boolean    | 非必填  | -   | 开启安比例灰度的Debug模式，用于观测按比例灰度效果 |
> `安比例` 错别字

done

2024-09-10 13:32 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `header`  | array of string | 非必填   | -   | 注入header信息，比如`<link rel="stylesheet" href="https://cdn.example.com/styles.css">` |
> 那个tag是head不是header吧？

fixed

2024-09-10 13:32 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `body`  | map of string to string | 非必填   | -   | 注入Body |
> 这个其实是个 object 吧？

fixed

2024-09-11 02:37 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
> 不是太理解什么时候应该用这个功能。。。

这个不算是功能，只是让用户进行观测效果。看不出按比率灰度的效果

2024-09-12 01:51 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
要不你加一下我钉钉 CH3CHO，我们单独沟通一下。

2024-09-12 03:36 UTC, CH3CHO requested changes

2024-09-12 03:36 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/config/config.go
>  	IsIndex        = "is-index"
isIndex这个名字是不是换一下，改成isPageRequest之类的？

2024-09-12 03:41 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
让用户进行观测效果：观测什么的效果呢？

- 如果是灰度真实用户，不做粘滞可能会导致用户体验不一致。
- 如果是开发人员去验证灰度版本，那他自己种一个灰度Cookie就可以了吧？

2024-09-12 06:08 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +		// 确保每个用户每次访问的都是走同一版本
> CH3CHO
好的好，这个debug模式 确实可以删除的，已经删除哈

2024-09-18 12:50 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if os.Getenv("TEST_MODE") != "" {
> * 是不是可以在外面把 env get 好并做好判定设置为 bool，这样就不需要每次单独读取和判定了？
> * 如果不是 TEST_MODE，上面的 Sprintf 是不是也没必要调用了？

是的，这个 debug模式也删除了哈

2024-09-18 12:50 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils_test.go
> +			reslut := FilterGrayWeight(grayConfig, []string{"base", "1.0.1"}, "192.168.1.1")
> result 拼写错误

fixed

2024-09-18 13:19 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/config/config.go
>  	IsIndex        = "is-index"
> isIndex这个名字是不是换一下，改成isPageRequest之类的？

fixed

2024-09-18 13:20 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/config/config.go
> +	MaxAgeCookie = "172800"
> 这个就是让灰度的粘滞保持多长时间吧？是不是最好支持用户配置？

通过配置 `userStickyMaxAge` 字段支持，默认为172800，2天

2024-09-20 11:19 UTC, CH3CHO requested changes

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +func GetIsPageRequest(fetchMode string, p string) bool {
建议是把 Get 去掉，直接就叫 IsPageRequest。另外这个 p 的参数名不太好理解。如果是怕和包名冲突的话，可以考虑把 import 那个 path 起个别名叫 gopath。这个变量还是叫 path。

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +			if deployment.Version == strings.Trim(preVersions[0], " ") {
Trim操作做一次是不是就行了？

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if len(preVersions) > 1 && preVersions[1] != "" && uniqueClientId == preVersions[1] {
preversion的生成和解析建议抽一个方法并返回一个有语义的结构，现在写Cookie、读Cookie和用这个值分散在不同的地方，不便于理解和管理。

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `userStickyMaxAge`         | string       | 非必填 | 172800   | 用户粘滞的时长：单位为秒，默认为`172800`，2天时间 |
这个字段是不是用 int 类型更好一点？

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +	ctx.SetContext(config.XUniqueClient, uniqueClientId)
存的是ID，这个常量是不是也叫XUniqueClientId好一点？

2024-09-20 11:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +	isPageRequest := ctx.GetContext(config.IsPageRequest).(bool)
这些地方建议都用两个返回值的 cast 方式，避免 panic。

2024-09-22 06:42 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +	ctx.SetContext(config.XUniqueClient, uniqueClientId)
> 存的是ID，这个常量是不是也叫XUniqueClientId好一点？

已修改

2024-09-22 06:43 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +	isPageRequest := ctx.GetContext(config.IsPageRequest).(bool)
> 这些地方建议都用两个返回值的 cast 方式，避免 panic。

相关转换，已经修改

2024-09-22 06:46 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `userStickyMaxAge`         | string       | 非必填 | 172800   | 用户粘滞的时长：单位为秒，默认为`172800`，2天时间 |
> 这个字段是不是用 int 类型更好一点？

已修改

2024-09-22 06:48 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if len(preVersions) > 1 && preVersions[1] != "" && uniqueClientId == preVersions[1] {
> preversion的生成和解析建议抽一个方法并返回一个有语义的结构，现在写Cookie、读Cookie和用这个值分散在不同的地方，不便于理解和管理。

已单独抽出方法进行管理

2024-09-22 06:49 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +			if deployment.Version == strings.Trim(preVersions[0], " ") {
> Trim操作做一次是不是就行了？

抽离出 方法进行管理，使用的时候就不需要Trim了

2024-09-22 06:49 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +func GetIsPageRequest(fetchMode string, p string) bool {
> 建议是把 Get 去掉，直接就叫 IsPageRequest。另外这个 p 的参数名不太好理解。如果是怕和包名冲突的话，可以考虑把 import 那个 path 起个别名叫 gopath。这个变量还是叫 path。

已修复

2024-09-22 08:23 UTC, CH3CHO approved these changes
LGTM

2024-09-22 08:49 UTC, merged