Update ai statistics
alibaba/higress pull request #1303
Opened 2024-09-12 07:48 UTC by rinfx

增加用户扩展 log & span attribute 机制

2024-09-20 13:57 UTC, CH3CHO requested changes

2024-09-20 13:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
>  	// Set infomations about this request
这个拼写错误顺手改一下把：information（这个单词是不可数的）

https://dictionary.cambridge.org/dictionary/english/information
![image](https://github.com/user-attachments/assets/6272e8de-5aa4-4ae9-a8b2-9a3d96b6a0e0)

2024-09-20 13:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
>  		// Record Log Attributes
这个注释是不是最好也改一下？

2024-09-20 13:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +		config.incrementCounter(generateMetricName(route, cluster, attributes["model"], "llm_duration_count"), 1)
这堆字段名字还是整个常量吧，不然哪一不小心拼错了都很难发现。

2024-09-20 13:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +		config.incrementCounter(generateMetricName(route, cluster, attributes["model"], "llm_duration_count"), 1)
另外，这堆逻辑 streambody 和 body 里都有，是不是可以抽个函数出来？

2024-09-23 01:42 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				raw := gjson.GetBytes(body, logAttribute.Value).Raw
Raw取的是序列化后的数据，用.String()的话，打印日志的时候会有格式问题

2024-09-23 01:52 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				return data
拿不到数据的情况下，无法从中解析出来日志中需记录的字段

2024-09-23 01:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				raw := gjson.GetBytes(body, logAttribute.Value).Raw
具体是什么格式问题呢，能举个例子吗？

2024-09-23 02:30 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +			raw := gjson.GetBytes(chunk, jsonPath).Raw
这是为了能拿到序列化后的数据，因为大模型的返回结果可能包含一些特殊字符，如果取.String()的话，在打印日志的时候会有问题

2024-09-23 06:18 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				raw := gjson.GetBytes(body, logAttribute.Value).Raw
{"ai_log":"{\"consumer\":\"21321r9fncsb2dq\",\"question\":\"用三行python实现求和函数\",\"answer\":\"在Python中，你可以使用内置的`sum()`函数来计算一个数字列表的总和。这是一个简单的实现：\\n\\n```python\\ndef sum_function(numbers):\\n    return sum(numbers)\\n\\n# 测试函数\\nnumbers = [1, 2, 3, 4, 5]\\nprint(sum_function(numbers))  # 输出：15\\n```\\n\\n如果你想要自己手动实现一个求和函数，可以使用以下代码：\\n\\n```python\\ndef sum_function(numbers):\\n    total = 0\\n    for number in numbers:\\n        total += number\\n    return total\\n\\n# 测试函数\\nnumbers = [1, 2, 3, 4, 5]\\nprint(sum_function(numbers))  # 输出：15\\n```\\n\\n在这两个例子中，我们定义了一个名为`sum_function`的函数，它接受一个数字列表作为参数，并返回该列表中所有数字的总和。\",\"output_token\":\"188\",\"llm_first_token_duration\":\"237\",\"llm_service_duration\":\"4341\",\"model\":\"qwen-turbo\",\"input_token\":\"16\"}"}

2024-09-23 06:19 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				raw := gjson.GetBytes(body, logAttribute.Value).Raw
上面这个是一个例子，如果LLM返回的内容中有换行符之类的，容易有问题，我直接复制粘贴被github打印了。。原始的是这样的：
![image](https://github.com/user-attachments/assets/58a7c5c9-da1c-46ac-a20a-066ab1eb3054)

2024-09-23 06:25 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +			setLogAttributeValueBySource(ctx, config, "response_streaming_body", streamingBodyBuffer, log)
流式和非流式对响应的处理是有区别的

2024-09-23 06:30 UTC, rinfx commented on plugins/wasm-go/extensions/ai-statistics/main.go
> +				raw := gjson.GetBytes(body, logAttribute.Value).Raw
```json
{"ai_log":"{\"consumer\":\"21321r9fncsb2dq\",\"question\":\"用三行python实现求和函数\",\"answer\":\"在Python中，你可以使用内置的`sum()`函数来计算一个数字列表的总和。这是一个简单的实现：\\n\\n```python\\ndef sum_function(numbers):\\n    return sum(numbers)\\n\\n# 测试函数\\nnumbers = [1, 2, 3, 4, 5]\\nprint(sum_function(numbers))  # 输出：15\\n```\\n\\n如果你想要自己手动实现一个求和函数，可以使用以下代码：\\n\\n```python\\ndef sum_function(numbers):\\n    total = 0\\n    for number in numbers:\\n        total += number\\n    return total\\n\\n# 测试函数\\nnumbers = [1, 2, 3, 4, 5]\\nprint(sum_function(numbers))  # 输出：15\\n```\\n\\n在这两个例子中，我们定义了一个名为`sum_function`的函数，它接受一个数字列表作为参数，并返回该列表中所有数字的总和。\",\"output_token\":\"188\",\"llm_first_token_duration\":\"237\",\"llm_service_duration\":\"4341\",\"model\":\"qwen-turbo\",\"input_token\":\"16\"}"}
```

2024-09-24 11:42 UTC, johnlanni approved these changes
LGTM

2024-09-24 11:42 UTC, merged