ai-agent插件新版本
alibaba/higress pull request #1311
Opened 2024-09-13 12:49 UTC by xingyunyang01

…g mode support #1309

### Ⅰ. Describe what this PR did
fix #1309 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-09-14 09:14 UTC, CH3CHO requested changes

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/config.go
>  	Domin string `required:"true" yaml:"domain" json:"domain"`
字段名拼写错误

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/config.go
> +type Tools_Param struct {
struct 命名不可以带下划线

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/config.go
> +type APIsParam struct {
这个复数是说有多个 API 吗？

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/config.go
> +	Tools_Param      []Tools_Param `yaml:"tools_Param"`
字段名不应包含下划线。配置名的格式也应与其他的配置名称保持对齐。

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/config.go
> +type APIsParam struct {
配置结构更新后，请同步更新 README 文档。此外，请重新评估有默认值的字段是否是必填。

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +		log.Debugf("[onHttpRequestBody] newRequestBody: %s\n", string(newbody))
所有的日志都不用加换行

2024-09-14 09:14 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				history += "human: " + rawRequest.Messages[i].Content + "AI: " + rawRequest.Messages[i+1].Content
`AI:` 前面是不是应该加个空格或者什么的分隔符？

2024-09-14 13:03 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/config.go
> +type APIsParam struct {
> 这个复数是说有多个 API 吗？

是的 有多个 比如可以同时有高德地图，deepl翻译等等

2024-09-18 02:05 UTC, CH3CHO requested changes

2024-09-18 02:05 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/README.md
> +| `in`              | string  | 非必填     | header | 在访问外部 API 服务时进行认证的令牌是放在 header 中还是放在 query 中，如果API没有令牌，填None。
header、query 的比较区分大小写吗？如果前面两个都是小写，那么是不是“None”也应该全小写呢？

2024-09-18 02:05 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/README_EN.md
> +A customizable API AI Agent that supports configuring HTTP method types as GET and POST APIs. Supports multiple dialogue rounds, streaming and non-streaming modes
结尾要有句号

2024-09-18 02:05 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/README.md
> +| `in`              | string  | 非必填     | header | 在访问外部 API 服务时进行认证的令牌是放在 header 中还是放在 query 中，如果API没有令牌，填None。
这个参数的英文版文档似乎没有更新？

2024-09-18 02:28 UTC, CH3CHO approved these changes
LGTM

2024-09-18 02:52 UTC, merged