fix: when there is a non-ip IPAddr in Eureka, delete it to avoid a failure in EDS
alibaba/higress pull request #1322
Opened 2024-09-18 12:05 UTC by lcfang

### Ⅰ. Describe what this PR did
当eureka中注册的服务IPAddr为域名而非ip时，会导致其他EDS下发失败，故打印waring并忽略该应用

### Ⅱ. Does this pull request fix one issue?

fixes #1284 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it
在启动higress之前往eureka注册中心注册一个服务，ipaddr为域名而非ip，修复前查看配置下发是失败的，修复后不报错，controller中有waring日志

### Ⅴ. Special notes for reviews

2024-09-18 12:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1322) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1322) it.</sub>

2024-09-19 01:31 UTC, lcfang commented
@johnlanni @NameHaibinZhang

2024-09-19 03:59 UTC, CH3CHO requested changes

2024-09-19 03:59 UTC, CH3CHO commented on registry/eureka/client/http_client.go
> +				break
这里逻辑感觉有点问题。delete 之后还要继续 parse 吗？还是说只是忽略非 IP 实例就行了？

2024-09-20 11:52 UTC, lcfang commented on registry/eureka/client/http_client.go
> +				break
这里应该忽略该app（这里都用域名了，应该不会域名和ip混用），删除后不应该继续parse了，我改一下

2024-09-20 13:14 UTC, CH3CHO requested changes

2024-09-20 13:14 UTC, CH3CHO commented on registry/eureka/client/http_client.go
> +		shouldDelete bool
这个变量是不是没必要放这么外面呀，留在for里面就行了

2024-09-20 13:14 UTC, CH3CHO commented on registry/eureka/client/http_client.go
> +		for _, instant := range app.Instances {
instant？

2024-09-20 13:14 UTC, CH3CHO commented on registry/eureka/client/http_client.go
>  		apps[app.Name] = app
看了一下，是不是直接把下面的逻辑放到这个循环里就行了。。。

2024-09-24 01:23 UTC, lcfang commented on registry/eureka/client/http_client.go
> +		if shouldDelete == true {
这个确实不需要了。。

2024-09-24 01:25 UTC, lcfang commented on registry/eureka/client/http_client.go
> +		shouldDelete bool
这个要在for循环外面使用，要放在外面吧

2024-09-24 06:27 UTC, lcfang commented on registry/eureka/client/http_client.go
> +		for _, instant := range app.Instances {
instance，我改一下

2024-09-24 07:06 UTC, lcfang commented on registry/eureka/client/http_client.go
>  		apps[app.Name] = app
对！

2024-09-26 01:16 UTC, CH3CHO commented on registry/eureka/client/http_client.go
> +		shouldDelete bool
我是说 `shouldDelete`。。。

2024-09-27 07:30 UTC, CH3CHO approved these changes
LGTM

2024-10-08 02:49 UTC, CH3CHO approved these changes
LGTM

2024-10-08 06:00 UTC, johnlanni approved these changes
LGTM

2024-10-08 06:00 UTC, merged