support ai proxy for cohere (#960)
alibaba/higress pull request #1328
Opened 2024-09-19 12:58 UTC by jk-tonycui

### Ⅰ. Describe what this PR did
最近 Higress 上线了一个新的 Wasm 插件，AI 代理（ai-proxy），支持对接各类 AI 大模型服务提供商，并以统一的 OpenAI 接口契约对外提供服务。目前已支持 OpenAI、Azure OpenAI、通义千问（Qwen）和月之暗面（Moonshot）。

为了进一步扩展该插件的功能，我们需要对接更多的 AI 大模型服务提供商，本次增强了 Cohere。

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-09-19 12:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1328) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1328) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1328) it.</sub>

2024-09-19 14:19 UTC, CH3CHO requested changes

2024-09-19 14:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +Mistral 所对应的 `type` 为 `cohere`。它并无特有的配置字段。
Mistral？

2024-09-19 14:19 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/cohere.go
> +		Message:          fmt.Sprintf("%v", origin.Messages[0].Content),
如果 Content 不是个 string，这里会不会有问题？

2024-09-19 14:49 UTC, jk-tonycui commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +Mistral 所对应的 `type` 为 `cohere`。它并无特有的配置字段。
修正了

2024-09-19 14:50 UTC, jk-tonycui commented on plugins/wasm-go/extensions/ai-proxy/provider/cohere.go
> +		Message:          fmt.Sprintf("%v", origin.Messages[0].Content),
修正了

2024-09-20 12:32 UTC, CH3CHO commented
@jk-tonycui 麻烦签一下上面的 CLA~

2024-09-20 12:34 UTC, jk-tonycui commented
Done

2024-09-20 12:34 UTC, CH3CHO approved these changes
LGTM. Thanks.

2024-09-20 13:15 UTC, merged