feat: Support configuring a global provider list in ai-proxy plugin
alibaba/higress pull request #1334
Opened 2024-09-23 13:54 UTC by CH3CHO

### Ⅰ. Describe what this PR did

Support configuring a global provider list in ai-proxy plugin. Meanwhile, the old-style configurations are also supported.

**New config style:**

```yaml
provider: my-azure
providers:
  - id: my-azure
    type: azure
    apiTokens:
      - "YOUR_AZURE_OPENAI_API_TOKEN"
    azureServiceUrl: "https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=2024-02-15-preview",
  - id: my-qwen
    type: qwen
    apiTokens:
      - "YOUR_QWEN_API_TOKEN"
    modelMapping:
      'gpt-3': "qwen-turbo"
      'gpt-35-turbo': "qwen-plus"
      'gpt-4-turbo': "qwen-max"
      'gpt-4-*': "qwen-max"
      'gpt-4o': "qwen-vl-plus"
      'text-embedding-v1': 'text-embedding-v1'
      '*': "qwen-turbo"
```

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-09-24 01:47 UTC, johnlanni requested changes

2024-09-24 01:47 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
README_EN.md 请同步更新一下

2024-09-24 01:47 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 实例配置
这部分是否不需要单独拎出来，也放到全局配置的字段说明表里就可以。因为全局、路由、域名、服务都可以配置这个，只是描述里特殊说明一下，全局配置时该项非必填。相应的“providers”在路由、域名、服务粒度非必填。

此外，字段名是否叫"activeProvider"更容易理解一些，现在跟 providers 单复数形式，容易配错。

2024-09-26 01:16 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
Done

2024-09-26 03:27 UTC, johnlanni approved these changes
LGTM

2024-09-26 03:27 UTC, merged