Standardize the data structure returned by the AI security security a…
alibaba/higress pull request #1344
Opened 2024-09-25 10:27 UTC by mrhaoji

…nd add the ability to customize model name

### Ⅰ. Describe what this PR did
规范接口返回结构，包括：随机 id，自定义 model 参数、规范流式输出结束标记 data: [DONE]

### Ⅱ. Does this pull request fix one issue?
No.

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Easy to understand

### Ⅳ. Describe how to verify it
开启 AI 内容安全插件后，利用敏感数据请求，观察返回的结构体 id 由 chatcmpl-123 变为随机；model 由 gpt-4o-mini 变成阿里云 AI 内容安全服务名 ai_art_detection（或者您在 responseModelName 参数中自行指定的模型名）；最后增加了流式输出结束标记 data: [DONE]。

### Ⅴ. Special notes for reviews

2024-09-25 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1344) it.</sub>

2024-09-25 11:39 UTC, CH3CHO requested changes

2024-09-25 11:39 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +| `responseModelName` | string | optional | ai_art_detection | 指定内容非法时返回的响应内容中的模型名 |
是不是应该默认返回请求里的 model？

2024-09-25 11:39 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README_EN.md
>  ## Examples of configuration
如果真的需要配置的话，麻烦更新一下英文的配置示例

2024-09-25 11:39 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +	responseModelName			  string
![image](https://github.com/user-attachments/assets/862cad04-e055-458c-a7d6-d82bc59416cf)

这里建议格式化一下，统一用空格。

2024-09-25 11:39 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +		b[i] = charset[rand.Intn(len(charset))]
这里漏了 import

2024-09-26 02:01 UTC, johnlanni commented
cc @rinfx

2024-09-26 03:06 UTC, rinfx approved these changes

2024-09-26 03:07 UTC, merged