add default deny message
alibaba/higress pull request #1347
Opened 2024-09-26 03:33 UTC by rinfx

### Ⅰ. Describe what this PR did
如果阿里云内容安全未返回建议的回答，允许用户使用兜底回答进行回复

### Ⅱ. Does this pull request fix one issue?

fixes #1344

2024-09-26 03:45 UTC, CH3CHO requested changes

2024-09-26 03:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
这里写个original我们怎么知道它到底是什么协议呢？

2024-09-26 03:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
感觉还不如叫 raw，并说明用这个 protocol 的时候，denymessage 会直接被返回。

2024-09-26 03:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
考虑到用户需求，protocol改动是不是可以单独拆个 PR 提交？

2024-09-26 03:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = DefaultDenyMessage
这里需要做个 JSON 序列化。另外这两段回写响应的逻辑能不能抽出来做个方法，太重复了

![image](https://github.com/user-attachments/assets/cc32b453-8da7-4ad7-96d0-78de66d72a5e)

2024-09-26 03:47 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
original 就是不管用户是什么协议了，搭配requestContentJsonPath和responseContentJsonPath使用，由用户指定需要检测的内容

2024-09-26 03:49 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
之前的设计是如果用户使用非openai的协议，需要配置denyMessage，代码中会检测denyMessage来判断如何回复，现在由于单纯依靠denyMessage无法判断，所以加了这个配置项

2024-09-26 05:29 UTC, CH3CHO requested changes

2024-09-26 05:29 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
original的时候就不用加引号了吧？

2024-09-26 05:29 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
另外，用户配的denyMessage现在完全没有用了？是否可以移除？

2024-09-26 05:29 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
> original 就是不管用户是什么协议了，搭配requestContentJsonPath和responseContentJsonPath使用，由用户指定需要检测的内容

问题是那两个JsonPath和original不original毫无关系，我配openai，他俩也能正常工作。

2024-09-27 01:55 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
> 这里写个original我们怎么知道它到底是什么协议呢？

这个配置我是跟ai-proxy里面保持一致的，ai-proxy里面protocol设置为original的时候就是非openai，保持协议格式不动

2024-09-27 01:56 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
> 另外，用户配的denyMessage现在完全没有用了？是否可以移除？

有用，用户可以根据业务需求，在denyMessage里面设置一个json、text来保持接口返回形式一致

2024-09-27 01:59 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/README.md
> +protocol: original
> > original 就是不管用户是什么协议了，搭配requestContentJsonPath和responseContentJsonPath使用，由用户指定需要检测的内容
> 
> 问题是那两个JsonPath和original不original毫无关系，我配openai，他俩也能正常工作。

是的，因为要检测的内容可能并不总是最后一条message，如果用户做了prompt的修改，就不适用了，把这个开放给用户也有这方面的考虑。此外，用户如果没有特殊需求，不填用默认值就好了

2024-09-27 02:20 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
但这里统一用的是 DefaultDenyMessage 诶...

![image](https://github.com/user-attachments/assets/24284867-67fc-4bf1-aad6-13a2357141ee)

2024-09-27 02:24 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
> 但这里统一用的是 DefaultDenyMessage 诶...
> 
> ![image](https://private-user-images.githubusercontent.com/2909796/371369708-24284867-67fc-4bf1-aad6-13a2357141ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDM5NjIsIm5iZiI6MTcyNzQwMzY2MiwicGF0aCI6Ii8yOTA5Nzk2LzM3MTM2OTcwOC0yNDI4NDg2Ny02N2ZjLTRiZjEtYWFkNi0xM2EyMzU3MTQxZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMDIyMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJkYmUxNjIwMmQwMmZiMWNjNzJmZGQ2M2FmYzgzZTQwNzUwYjRjNDBkODg2M2MxZmZhNWYwYzBjOTMyMDRhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxgHnXTVFjIsfZwKiSdXYXb6Tg-Wi32Ha3aX89un2TY)

我改一下😂

2024-09-27 02:28 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
Done

2024-09-27 02:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
现在又变成 `DefaultDenyMessage` 没用上了。

![image](https://github.com/user-attachments/assets/fde344ab-163d-4edc-ae64-bf3f97f00d1d)

2024-09-27 02:46 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
另外，文档也说一下这个 denyMessage 是用在什么情况下吧。

2024-09-27 03:14 UTC, rinfx commented on plugins/wasm-go/extensions/ai-security-guard/main.go
> +						denyMessage = fmt.Sprintf(`"%s"`, DefaultDenyMessage)
Done

2024-09-27 04:07 UTC, CH3CHO approved these changes
LGTM

2024-09-27 05:25 UTC, merged