AI Agent增加json格式化输出功能
alibaba/higress pull request #1374
Opened 2024-10-09 12:01 UTC by xingyunyang01

### Ⅰ. Describe what this PR did
fix #1373 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-10-09 12:06 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-agent/main.go
> +		log.Debug("[onHttpResponseBody] response替换成功")
日志打印统一用英文吧

2024-10-11 07:37 UTC, CH3CHO requested changes

2024-10-11 07:37 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				url = strings.Join(urlParts, "/")
这里会不会需要做url encode？

2024-10-11 07:37 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				}
这一段总觉的有点问题，先插个眼，后面我再想想。

2024-10-11 07:37 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +						}
这两段是不是可以抽个出来？

2024-10-11 07:37 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +			}
感觉应该是这一坨抽个函数出来

2024-10-11 08:06 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				}
替换那个参数进去不用看 {} 中间的内容吗？

2024-10-14 12:04 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				}
value, ok := data[param] 这行就是对比参数和{}里面的参数是不是相同

2024-10-14 12:21 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				}
> value, ok := data[param] 这行就是对比参数和{}里面的参数是不是相同

param 是从 part 里读的吗？没太看懂。。。

2024-10-15 06:28 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				}
我想错了 代码已修改

2024-10-15 06:29 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				url = strings.Join(urlParts, "/")
我感觉不需要 没有什么特殊字符

2024-10-25 09:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				url = strings.Join(urlParts, "/")
中文字符呢？

2024-10-25 09:45 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				url = strings.Join(urlParts, "/")
安全第一，建议encode一下

2024-10-31 11:07 UTC, johnlanni requested changes

2024-10-31 14:08 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +						urlStr += "&" + strings.Join(queryParams, "&")
如果 API Key 不在 query string 里，这句话会不会有问题诶？

2024-10-31 14:08 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				log.Infof("url: %s", urlStr)
这句是不是 debug 就够了？

2024-11-02 13:47 UTC, xingyunyang01 commented on plugins/wasm-go/extensions/ai-agent/main.go
>  func toolsCallResult(ctx wrapper.HttpContext, config PluginConfig, content string, rawResponse Response, log wrapper.Log, statusCode int, responseBody []byte) {
这段改了改 尽量少传了一点参数

2024-11-05 10:01 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-agent/main.go
> +				urlStr += key
URL拼接的逻辑可以优化一下，你看看我这种写法行不（未测试）：

![image](https://github.com/user-attachments/assets/962237ea-a94b-4e9b-98a1-6e6fcfe765c9)

2024-11-11 01:54 UTC, CH3CHO approved these changes
LGTM

2024-11-11 03:10 UTC, johnlanni approved these changes
LGTM

2024-11-11 03:11 UTC, merged