feat: 【frontend-gray】添加 skipedRoutes以及skipedByHeaders 配置
alibaba/higress pull request #1409
Opened 2024-10-20 10:08 UTC by heimanba

### Ⅰ. 添加 skipedRoutes以及skipedByHeaders 配置，忽略某些请求进入灰度插件处理
比如请求接口为`/api/xx`,这个路由需要配置单独的后端服务。同时这部分请求可以不经过当前插件处理。用户可以通过配置请求路由 skipedRoutes，或者 匹配请求头header `skipedByHeaders`进行忽略

2024-10-20 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=1409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=1409) before we can accept your contribution.<br/><hr/>**丹坤** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=1409) it.</sub>

2024-10-20 10:27 UTC, CH3CHO requested changes

2024-10-20 10:27 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
skipped

2024-10-20 10:27 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
另外，这里既然是排除路径，是不是叫 `skippedPathPrefixes` 更好？

2024-10-20 10:27 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
按 header 跳过的逻辑需要判断 header 的值吗，还是只判断有没有值就行？

2024-10-20 10:34 UTC, CH3CHO requested changes

2024-10-20 10:34 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
所以header跳过逻辑对pageRequest是不生效的，这个文档里是否应该注明？

2024-10-20 10:34 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	secfetchMode, _ := proxywasm.GetHttpRequestHeader("sec-fetch-mode")
f应该大写

2024-10-20 10:34 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
这里需要判断 `secfetchMode` 和 `upgrade` 吗？

2024-10-20 15:20 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
> 按 header 跳过的逻辑需要判断 header 的值吗，还是只判断有没有值就行？

done

2024-10-20 15:23 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
> 按 header 跳过的逻辑需要判断 header 的值吗，还是只判断有没有值就行？

有些特殊情况，比如微前端的方式：同样的请求路径，在微应用是 `<script>`请求，在主应用是`ajax`请求。通过header判断

2024-10-20 15:26 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	secfetchMode, _ := proxywasm.GetHttpRequestHeader("sec-fetch-mode")
> f应该大写

fixed

2024-10-20 15:27 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
> 这里需要判断 `secfetchMode` 和 `upgrade` 吗？

这里其实想默认的 xhr/fetch/websokect 等请求都不经过插件处理

2024-10-20 15:39 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
> 所以header跳过逻辑对pageRequest是不生效的，这个文档里是否应该注明？

  已声明哈:(是不是没有描述清楚)
| `skippedByHeaders` | array of string   | 非必填  | -   | 用于通过请求头过滤，指定哪些请求不被当前插件处理。`skippedPathPrefixes` 的优先级高于当前插件的配置。 |

2024-10-21 01:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
> 用于通过请求头过滤，指定哪些请求不被当前插件处理

假如是个页面请求，也带了请求头，能过滤吗？

2024-10-21 01:58 UTC, CH3CHO commented
修正一下 commit tree 吧，CLA 匹配不上了。

2024-10-21 02:00 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
那就是说如果用户配了 `SkippedByHeaders`，那就不看 `secFetchMode`，CORS 和 WS 请求也会走插件咯？

2024-10-21 04:34 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
> 那就是说如果用户配了 `SkippedByHeaders`，那就不看 `secFetchMode`，CORS 和 WS 请求也会走插件咯？

是的哈，用户配置，就看 用户自定义header 来确认

2024-10-21 04:36 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
> > 用于通过请求头过滤，指定哪些请求不被当前插件处理
> 
> 假如是个页面请求，也带了请求头，能过滤吗？

不会，页面请求会优先判断
```
//  如果是首页，进入插件逻辑
	if IsPageRequest(requestPath) {
		return true
	}
	// 检查header标识，判断是否需要跳过
	if IsRequestSkippedByHeaders(grayConfig) {
		return false
	}
```

2024-10-21 04:53 UTC, heimanba commented
> 修正一下 commit tree 吧，CLA 匹配不上了。

已经整理哈

2024-10-21 05:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
所以描述是不是不太准确，页面会被跳过的逻辑没有说。

另外，`skippedPathPrefixes 的优先级高于当前插件的配置`，啥叫“当前插件的配置”，是不是“当前配置”？

2024-10-21 05:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
好吧，感觉是个隐含逻辑

2024-10-21 05:29 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
所以用户只能配出按 header name 跳过的配置，配不出同时匹配 name 和 value 的逻辑？

2024-10-21 05:53 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	return false
> 好吧，感觉是个隐含逻辑

文档已经补充

2024-10-21 05:53 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/util/utils.go
> +	if IsRequestSkipedByHeaders(grayConfig) {
> 所以描述是不是不太准确，页面会被跳过的逻辑没有说。
> 
> 另外，`skippedPathPrefixes 的优先级高于当前插件的配置`，啥叫“当前插件的配置”，是不是“当前配置”？

好的，文档已经补充

2024-10-21 05:54 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/README.md
> +| `skipedByHeaders` | array of string   | 非必填  | -   | 通过请求头过滤某些请求，不走当前插件逻辑，`skipedRoutes`优先级大于当前插件的配置 |
> 所以用户只能配出按 header name 跳过的配置，配不出同时匹配 name 和 value 的逻辑？

这里想着header匹配不太多，所以没有写成匹配name 和 value 的逻辑，我改成 `map of string to string`格式比较好一些。已经提交哈

2024-10-22 14:05 UTC, CH3CHO reviewed
LGTM

2024-10-22 14:05 UTC, CH3CHO approved these changes

2024-10-23 01:34 UTC, merged