support custom log extension
alibaba/higress pull request #1451
Opened 2024-10-29 11:08 UTC by rinfx

扩展SDK，支持在插件中向access_log中增加自定义的扩展字段，字段值为`custom_log`，可以跨插件调用接口对访问日志进行扩展，附加使用demo。

2024-10-31 08:50 UTC, CH3CHO requested changes
看没看完，先标注这些

2024-10-31 08:50 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +		// e.g. {"feild1":"value1","feild2":"value2"}
field 拼写错误

2024-10-31 08:50 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +	preMarshaledJsonLogStr, _ := proxywasm.GetProperty([]string{CustomLogKey})
marshalled 应该是两个 l

2024-10-31 08:50 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +	preMarshaledJsonLogStr, _ := proxywasm.GetProperty([]string{CustomLogKey})
其他地方的相同拼写问题不再重复标注

2024-10-31 08:50 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +		// e.g. {"feild1":"value1","feild2":"value2"}
其他地方的相同拼写问题不再重复标注

2024-10-31 08:50 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +			proxywasm.LogErrorf("failed to unmarshal custom_log, will overwrite old custom_log")
建议把 err 输出出来

2024-10-31 14:01 UTC, CH3CHO requested changes

2024-10-31 14:01 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +			proxywasm.LogErrorf("failed to unmarshal custom_log, will overwrite old custom_log")
下同

2024-11-05 06:53 UTC, johnlanni requested changes
可以ctx下增加一个 addAccessLogField 的函数，支持用户将自定义日志字段存到 ctx 里，然后在 onDone 阶段统一通过 setProperty 设置进去。这样用户使用简单，整体性能也是最优的。

2024-12-04 02:49 UTC, rinfx commented on plugins/wasm-go/extensions/custom-logs/main.go
> +func onHttpRequestHeaders(ctx wrapper.HttpContext, config CustomLogConfig, log wrapper.Log) types.Action {
嗯，我看到extensions目录下有一些其他的demo代码，我把这些统一放到examples目录下了

2024-12-04 02:53 UTC, rinfx commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +func UnmarshalStr(marshaledJsonStr string) string {
之前考虑到可能会在其他插件里面也可能对json字符串做处理

2024-12-04 02:58 UTC, rinfx commented on plugins/wasm-go/pkg/wrapper/property_wrapper.go
> +		preJsonLogStr := UnmarshalStr(fmt.Sprintf(`"%s"`, string(preMarshaledJsonLogStr)))
日志的format里面每个字段都会有一个""，所以当某个字段是一个序列化的json字符串的时候，把首位的""去掉让打印到控制台的日志格式是一个合法的json。所以实际上filter_state里面保存的不是一个完整的序列化后的json字符串，在使用`json.Unmarshal`进行反序列化时需要再把""加上

2024-12-04 02:59 UTC, rinfx commented
> 可以ctx下增加一个 addAccessLogField 的函数，支持用户将自定义日志字段存到 ctx 里，然后在 onDone 阶段统一通过 setProperty 设置进去。这样用户使用简单，整体性能也是最优的。

验证了下，onStreamDone里面setProperty不生效

2024-12-05 09:29 UTC, johnlanni requested changes
https://higress.cn/docs/ebook/wasm16/#3-envoy-%E5%B1%9E%E6%80%A7attributes

需要同步更新一下sdk文档，另外 attribute 可能跟 envoy 的 attribute 混淆，叫 userAttribute 可能好一些

2024-12-05 09:35 UTC, johnlanni approved these changes
LGTM

2024-12-05 09:54 UTC, CH3CHO approved these changes
OK

2024-12-05 10:39 UTC, merged