feat: support custom log
alibaba/higress pull request #1521
Opened 2024-11-19 03:43 UTC by pepesi

支持自定义日志组件
issue: https://github.com/alibaba/higress/issues/1520

允许通过 SetCtxWithLoger 方法启动时修改默认的log

2024-11-19 03:44 UTC, CH3CHO commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +func SetCtxWithLoger[PluginConfig any](pluginName string, log Log, setFuncs ...SetPluginFunc[PluginConfig]) {
Logger

2024-11-19 07:24 UTC, johnlanni requested changes

2024-11-19 07:24 UTC, johnlanni commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +func NewCommonVmCtxWithLogger[PluginConfig any](pluginName string, logger Log, setFuncs ...SetPluginFunc[PluginConfig]) *CommonVmCtx[PluginConfig] {
是否可以实现一个 NewCommonVmCtxWithOptions(pluginName string, logger Log, options ...CtxOption[PluginConfig])，logger 设置作为一种特殊的 CtxOption 的设置进来，这样避免未来出现更多 NewCommonVmCtxWithXXX

2024-11-19 07:25 UTC, johnlanni commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +func NewCommonVmCtxWithLogger[PluginConfig any](pluginName string, logger Log, setFuncs ...SetPluginFunc[PluginConfig]) *CommonVmCtx[PluginConfig] {
相应的 setFunc 操作也需要做为一种特殊的 CtxOption 进行设置

2024-11-19 07:28 UTC, johnlanni requested changes

2024-11-19 07:28 UTC, johnlanni commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
>  type SetPluginFunc[PluginConfig any] func(*CommonVmCtx[PluginConfig])
看上去可以直接把这个函数类型改名为 CtxOption

2024-11-25 07:32 UTC, johnlanni requested changes

2024-11-25 09:45 UTC, pepesi commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +func WithName[PluginConfig any](name string) CtxOption[PluginConfig] {
我之前的想法是想在某些自定义的部分和社区插件区分开的，例如 ai-proxy 和 ai-proxy-custom这样。
但是似乎这儿确实没啥用，而且直接通过第一个参数传递就可以了，我稍后删除掉这段没用的代码吧。

2024-11-27 12:11 UTC, johnlanni approved these changes
LGTM

2024-11-27 12:11 UTC, merged