feat: migrate baidu provider to v2 api
alibaba/higress pull request #1527
Opened 2024-11-20 05:00 UTC by cr7258

### Ⅰ. Describe what this PR did
迁移 baidu api 至 v2 版本，完全兼容 openai 协议格式，处理请求的逻辑更简单。
另外 v2 版本的 bearer token (apiToken) 其实还是有过期时间的，最长时间是 24 小时。 https://cloud.baidu.com/doc/IAM/s/Mm2x80phi
为了处理 apiToken 的刷新问题，新增 TickFuncHandler 接口，provider 如果有定时任务的需求（例如定时刷新 token）可以选择实现该接口。
用户应该在 baiduAccessKeyAndSecret 以 `<access-key>:<access-secret>` 的格式填写 access key 和 access secret，每隔 1 小时会用这个凭证去刷新 apiToken。

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/alibaba/higress/issues/1504

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

以下是完整的配置示例：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: baidu-v2
  namespace: higress-system
spec:
  matchRules:
  - config:
      provider:
        type: baidu
        baiduAccessKeyAndSecret:
          - "<access-key>:<access-secret>"
        baiduApiTokenServiceName: baidubce.dns
        modelMapping:
          "*": "ernie-3.5-8k"
    service:
    - baidu.dns
  url: oci://cr7258/ai-proxy-baidu-v2:21
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
     higress.io/destination: |
      100% baidu.dns
  labels:
    higress.io/resource-definer: higress
  name: test-ai
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
  - host: test-ai.com
    http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /
        pathType: Prefix
---
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: api.groq.com
    name: groq
    port: 443
    type: dns
    protocol: https
    sni: api.groq.com
  - domain: qianfan.baidubce.com
    name: baidu
    port: 443
    type: dns
    protocol: https
    sni: qianfan.baidubce.com
  - domain: iam.bj.baidubce.com
    name: baidubce
    port: 443
    type: dns
    protocol: https
    sni: iam.bj.baidubce.com
```

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-11-20 07:04 UTC, CH3CHO commented
粗看了一下，这个改动似乎对用户不透明啊。

2024-11-21 12:22 UTC, cr7258 commented
@CH3CHO 对用户来说是对这个改动基本无感的，迁移到 baidu v2 API 是为了简化内部 baidu provider 的处理逻辑。
另外一个比较主要的改动是定时刷新 apiToken，不管是 v1 和 v2 API 的 token 都是有过期时间的，这个问题不管迁不迁移到 v2 都需要修复。

2024-11-22 09:59 UTC, johnlanni requested changes

2024-11-22 09:59 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
这个authorizationString为什么是30分钟过期时间，另外看baidu的文档貌似没看到要带这个串来生成bearer token，没搞懂这个串的作用是什么

2024-11-22 10:12 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
文档：[步骤三. 获取BearerToken值](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Um2wxbaps#%E6%AD%A5%E9%AA%A4%E4%B8%89-%E8%8E%B7%E5%8F%96bearertoken%E5%80%BC)

authorizationString 是根据请求的方法、路径、参数、时间戳等因素进行签名得到的。

![CleanShot 2024-11-22 at 18 09 46@2x](https://github.com/user-attachments/assets/2f09e1be-ccd7-4f46-9046-01d7e79d363b)

生成 bearer token 的时候要在 Authorization header 带上这个 authorizationString。
![CleanShot 2024-11-22 at 18 05 56@2x](https://github.com/user-attachments/assets/7d693048-71b0-4952-9166-4db3eb1a927a)

请求后会得到类似这样的结果，其中 token 就是 bearer token：
```bash
{
  "userId": "b538846f482a4a3a85fce4b91cd3258f",
  "token": "bce-v3/ALTAK-YTbpRIr8YtqsTQn43x9lf/75995431bdddff9e462d4787e488f675c1d036da",
  "status": "enable",
  "createTime": "2024-11-17T12:59:38.000Z",
  "expireTime": "2024-11-18T12:59:38.000Z"
}
```
1800s 是 authorizationString 的有效期，也就是 1800s  内可以用这个 authorizationString 来生成多个 bearer token。每个 bearer token 默认的有效期是 24 小时。

2024-11-22 10:16 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
明白了，那现在这个签名串的过期时间其实没有用到，每次生成token时都是重新签名的

2024-11-22 10:16 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
authorizationString 参数是必填的，文档示例中是用 1800s，所以我就用了 1800s。

2024-11-22 10:17 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
authorizationString 只用了一次，其实可以设置一个比较小的过期时间。

2024-11-22 10:17 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/baidu.go
> +	baiduAuthorizationStringExpirationSeconds = 1800
好的，这个API设计的可真臃肿。。

2024-11-26 09:35 UTC, johnlanni requested changes

2024-11-27 12:11 UTC, johnlanni approved these changes
LGTM

2024-11-27 12:12 UTC, merged