feat: allow cover api-version when use ai-proxy azure provider
alibaba/higress pull request #1535
Opened 2024-11-21 09:29 UTC by pepesi

### Ⅰ. Describe what this PR did
允许覆盖azure的 api-version

### Ⅱ. Does this pull request fix one issue?

https://github.com/alibaba/higress/issues/1534

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-11-22 03:49 UTC, johnlanni requested changes

2024-11-22 03:49 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/azure.go
> +			q := m.serviceUrl.Query()
这里应该是 u.Query？
另外，变量名注意一下，u->url, e->err

2024-11-22 07:53 UTC, pepesi commented on plugins/wasm-go/extensions/ai-proxy/provider/azure.go
> +			q := m.serviceUrl.Query()
我只是想修改 api-version 这一个参数的，没想到这样都还引入了一个新bug。 😂

2024-12-05 05:40 UTC, johnlanni approved these changes
LGTM

2024-12-05 05:41 UTC, merged