fix: 🐛 frontend-grayurl 解析不正确导致路由失败
alibaba/higress pull request #1550
Opened 2024-11-28 07:31 UTC by heimanba

### fix: 修复 url 解析不正确导致路由失败
refer: https://github.com/alibaba/higress/issues/1548

2024-11-28 07:38 UTC, CH3CHO requested changes

2024-11-28 07:38 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +		requestPath = parsedURL.Path
如果有错误的话，是不是应该记录个日志以便排查？

2024-11-28 08:17 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +		requestPath = parsedURL.Path
> 如果有错误的话，是不是应该记录个日志以便排查？

done

2024-11-28 08:28 UTC, CH3CHO requested changes

2024-11-28 08:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +		requestPath = parsedURL.Path
是不是把解析失败的path也打出来？

2024-11-29 00:34 UTC, heimanba commented on plugins/wasm-go/extensions/frontend-gray/main.go
> +		requestPath = parsedURL.Path
> 是不是把解析失败的path也打出来？

好的，已经修改

2024-11-29 03:06 UTC, CH3CHO approved these changes
LGTM

2024-11-29 05:09 UTC, merged