feat: ai-proxy support dashscope-finance
alibaba/higress pull request #1554
Opened 2024-11-28 14:56 UTC by pepesi

### Ⅰ. Describe what this PR did
解决 issue https://github.com/alibaba/higress/issues/1553

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-12-03 16:52 UTC, johnlanni requested changes

2024-12-03 16:52 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/provider/provider.go
> +	qwenFinanceDomain bool `required:"false" yaml:"qwenFinanceDomain" json:"qwenFinanceDomain"`
建议通过自定义域名的配置来设置，这样更灵活一些

2024-12-04 02:56 UTC, pepesi commented on plugins/wasm-go/extensions/ai-proxy/provider/provider.go
> +	qwenFinanceDomain bool `required:"false" yaml:"qwenFinanceDomain" json:"qwenFinanceDomain"`
ok

2024-12-05 03:47 UTC, johnlanni approved these changes
LGTM

2024-12-05 03:48 UTC, merged