feat: retry failed request
alibaba/higress pull request #1590
Opened 2024-12-12 14:12 UTC by cr7258

### Ⅰ. Describe what this PR did
允许对失败的请求立即进行重试，以提升用户体验。当前只支持非流式请求进行重试。几个重要改动：
- 新增 `TransformResponseHeadersHandler` 和 `TransformResponseBodyHandler` 接口，provider 实现该接口对响应头和响应体进行修改。
-  移除 `ResponseHeadersHandler` 和  `ResponseBodyHandler` 接口，改为在 main.go 中调用 `TransformResponseHeadersHandler` 和 `TransformResponseBodyHandler` 统一进行处理。
- 新增 retry.go 处理重试的逻辑。

失败请求重试的日志如下：

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a9dd921a-6df6-4701-9c73-37e0e1744009" />

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-12-13 01:28 UTC, CH3CHO requested changes

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/request_helper.go
> +func ReplaceHttpJsonResponseBody(body []byte, log wrapper.Log) error {
建议把名字里的Json去掉。现在的实现已经不在乎是Json还不是Json了

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/qwen.go
> -	if apiName == ApiNameEmbeddings {
这里是不最好还是判断一下Embedding的Api？

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/failover.go
> +	if c.isRetryOnFailureEnabled() {
没有注意到哪里判断了当前请求不是流式请求而跳过重试。能告知相关逻辑的位置吗？

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +	}
这几个配置要考虑小于0的情况吗？

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +	log.Debugf("Sending retry request: %d/%d", retryCount, c.retryOnFailure.maxRetries)
这个地方已经不是sending状态了吧，响应都拿到了

2024-12-13 01:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +		host = ctx.GetContext(ctxRequestHost).(string)
什么情况下会走到这个分支啊？

2024-12-19 13:17 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +	}
不需要：
- retryTimeout 如果小于 0 的话，会被设置成默认的  500ms：https://github.com/alibaba/higress/blob/748bcb083ad1134505582c40f4cd628eb83c818c/plugins/wasm-go/pkg/wrapper/http_wrapper.go#L105-L107
- maxRetries 如果小于 0 的话，`retryCount <= int(c.retryOnFailure.maxRetries)` 不成立，不会进行重试。

2024-12-19 13:18 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +	log.Debugf("Sending retry request: %d/%d", retryCount, c.retryOnFailure.maxRetries)
改成 "sended" 了

2024-12-19 13:19 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/request_helper.go
> +func ReplaceHttpJsonResponseBody(body []byte, log wrapper.Log) error {
已去掉

2024-12-19 13:22 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +		host = ctx.GetContext(ctxRequestHost).(string)
如果设置从外部 url 获取 context，会发起一次请求，这时候 host 会被覆盖，需要将原始的请求 host 存在 `ctxRequestHost` 中。

https://github.com/alibaba/higress/blob/748bcb083ad1134505582c40f4cd628eb83c818c/plugins/wasm-go/extensions/ai-proxy/provider/context.go#L110-L113

2024-12-19 13:46 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/failover.go
> +	if c.isRetryOnFailureEnabled() {
加上了跳过流式重试：https://github.com/alibaba/higress/pull/1590/commits/2b00fc0e2bf2c3429817aa1db90daa80a95e8306

2024-12-21 06:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/failover.go
> +	if c.isRetryOnFailureEnabled() && !ctx.GetContext(ctxKeyIsStreaming).(bool) {
建议这里的类型转换还是防一手，避免后面实现的时候漏设 ctxKeyIsStreaming 导致 panic

2024-12-21 06:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/main.go
> +	ctx.DisableReroute()
为啥要加这个呢？

2024-12-21 06:58 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +		host = ctx.GetContext(ctxRequestHost).(string)
但 retry 的请求和获取 context 的请求不太一样吧？这里的用法感觉怪怪的。

2024-12-21 11:39 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/main.go
> +	ctx.DisableReroute()
这行代码是这个 PR 新引入的：https://github.com/alibaba/higress/pull/1603，我 rebase 了 main 分支新提交的代码

2024-12-21 11:43 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +		host = ctx.GetContext(ctxRequestHost).(string)
这里是在做 context 的请求之前，先保存原始请求的 host，比如 `dashscope.aliyuncs.com`。
当发起 context 之后，wrapper.GetRequestHost() 就拿不到原始的 host 的了，返回是 `""`，这时候需要去 ctxRequestHost 才能获取原始的 host。

2024-12-21 11:50 UTC, cr7258 commented on plugins/wasm-go/extensions/ai-proxy/provider/failover.go
> +	if c.isRetryOnFailureEnabled() && !ctx.GetContext(ctxKeyIsStreaming).(bool) {
增加了判空的逻辑：https://github.com/alibaba/higress/pull/1590/commits/8399b4199f43be5cd9c6b82389cdeb95521a66b8

2024-12-21 11:55 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/provider/retry.go
> +		host = ctx.GetContext(ctxRequestHost).(string)
明白了

2024-12-21 11:56 UTC, CH3CHO approved these changes
LGTM

2024-12-26 10:30 UTC, merged