feat: add try-paths plugins
alibaba/higress pull request #1598
Opened 2024-12-17 15:30 UTC by haifzhu

### Ⅰ. Describe what this PR did
add try-paths wasm go plugin to implement try_files function of nginx。

### Ⅱ. Does this pull request fix one issue?
Fix the issue: Add support of try_files usage #840 .

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
test cases be added in codes.

### Ⅳ. Describe how to verify it
enable the plugin on the route, and check its retry function on envoy log or request response.

### Ⅴ. Special notes for reviews
no

2024-12-18 01:49 UTC, johnlanni requested changes

2024-12-18 01:49 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/README.md
> +| serviceSource  | string           | 必填    | -          | 支持k8s,nacos,ip,dns                                 |
只支持FQDN格式的serviceName就可以了，这样能简化下配置，不需要配serviceSource

2024-12-18 01:49 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/main.go
> +	requestPath := strings.Replace(config.tryPaths[index], VariableReplacedStr, path, -1)
tryPath 里面存在 $uri 这样的变量，应该需要解析出来吧？

2024-12-18 02:35 UTC, haifzhu commented on plugins/wasm-go/extensions/try-paths/main.go
> +	requestPath := strings.Replace(config.tryPaths[index], VariableReplacedStr, path, -1)
> tryPath 里面存在 $uri 这样的变量，应该需要解析出来吧？

是在上面debug的输出里面需要打印出请求路径对吧？不要tryPaths中的原路径。

2024-12-24 06:15 UTC, johnlanni requested changes

2024-12-24 06:15 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/README.md
> +| host         | string           | 必填  | -          | FQDN格式的主机名称，比如<bucket name>.oss-cn-hangzhou.aliyuncs.com                 |
建议两个配置：
serviceHost 配 oss 域名
serviceName 配FQDN格式的服务名称（控制台服务列表看到的名字）

2024-12-24 06:17 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/README.md
> +| host         | string           | 必填  | -          | FQDN格式的主机名称，比如<bucket name>.oss-cn-hangzhou.aliyuncs.com                 |
可以参考 ext-auth 里 endpoint 配置项里的 service_host 和 service_name 的概念：https://higress.cn/docs/latest/plugins/authentication/ext-auth/

2024-12-24 06:18 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/main.go
> +	requestPath := strings.Replace(config.tryPaths[index], VariableReplacedStr, path, -1)
我看错了，没看到上面的变量替换

2024-12-28 10:43 UTC, haifzhu commented on plugins/wasm-go/extensions/try-paths/README.md
> +| host         | string           | 必填  | -          | FQDN格式的主机名称，比如<bucket name>.oss-cn-hangzhou.aliyuncs.com                 |
> 建议两个配置： serviceHost 配 oss 域名 serviceName 配FQDN格式的服务名称（控制台服务列表看到的名字）

好的

2025-01-02 06:16 UTC, johnlanni commented
这个插件可以改名为 nginx-static-file，以 nginx location 的配置方式实现静态文件的代理（可能是到oss，或者后端的js服务） ，对nginx用户迁移会更有帮助一些：
```yaml
# 简化处理，按顺序匹配即可
locations:
- location: "~ ^/users/(.+\.(?:gif|jpe?g|png))$"
   # 支持基于 alias 做正则路径改写
   alias: "/data/w3/images/$1"
- location: "/images/"
   # 支持基于 alias 改写目标文件目录
   alias: "/data/w3/images/"
- location: "/images/"
   # 支持基于 root 确定文件根目录
   root: "/data/w3"
- location: "/images/"
   root: "/data/w3"
   # 支持基于 try_files 重试
   try_files: "$uri /images/default.gif"
   # 支持目录路径时，基于index查找文件
   index  index.html index.htm;
```

2025-01-03 13:58 UTC, closed without merging