feat: add an annotation for ignoring URI case in HTTP match
alibaba/higress pull request #174
Opened 2023-02-06 09:17 UTC by Charlie17Li

Signed-off-by: charlie <qianglin98@qq.com>

### Ⅰ. Describe what this PR did

add an annotation for ignoring URI case in HTTP match

### Ⅱ. Does this pull request fix one issue?

fixes #163 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-02-06 09:20 UTC, johnlanni commented
@Charlie17Li  Could you add an e2e test case for it?

2023-02-06 12:59 UTC, Xunzhuo requested changes

2023-02-06 12:59 UTC, Xunzhuo commented on test/ingress/conformance/tests/httproute-ignore-case-match.go
> +var HTTPRouteIgnoreCaseMatch = suite.ConformanceTest{
please add HTTPRouteIgnoreCaseMatch to [e2e_test.go](https://github.com/alibaba/higress/blob/main/test/ingress/e2e_test.go#L53)

2023-02-06 13:01 UTC, Xunzhuo commented on test/ingress/conformance/tests/httproute-ignore-case-match.go
> +	Description: "A Ingress in the higress-conformance-infra namespace that ignore URI case in HTTP match",
nit: ignore -> ignores

2023-02-06 13:55 UTC, Xunzhuo commented on test/ingress/conformance/tests/httproute-ignore-case-match.go
> +var HTTPRouteIgnoreCaseMatch = suite.ConformanceTest{
Because this could be referred as a separated pkg to use.

2023-02-14 11:34 UTC, Xunzhuo approved these changes
LGTM, thanks for your contribution @Charlie17Li !

2023-02-14 11:51 UTC, johnlanni approved these changes
LGTM

2023-02-14 11:52 UTC, merged