Add e2e test for cors annotations #171
alibaba/higress pull request #179
Opened 2023-02-08 03:00 UTC by Hinsteny

### Ⅰ. Describe what this PR did
Add e2e test for cors annotations #171

### Ⅱ. Does this pull request fix one issue?
NO

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
this is a test PR

### Ⅳ. Describe how to verify it
verify by make e2e test

### Ⅴ. Special notes for reviews

2023-02-08 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=179) it.</sub>

2023-02-08 03:12 UTC, Xunzhuo requested changes
Thanks for picking this up @Hinsteny. Please refer to current higress supported cors annotations to cover them all.



nginx.ingress.kubernetes.io/enable-cors | Ingress | 兼容 | 开启或关闭跨域
-- | -- | -- | --
nginx.ingress.kubernetes.io/cors-allow-origin | Ingress | 兼容 | 允许的第三方站点
nginx.ingress.kubernetes.io/cors-allow-methods | Ingress | 兼容 | 允许的请求方法，如GET、POST、PUT等
nginx.ingress.kubernetes.io/cors-allow-headers | Ingress | 兼容 | 允许的请求Header
nginx.ingress.kubernetes.io/cors-expose-headers | Ingress | 兼容 | 允许的暴露给浏览器的响应Header
nginx.ingress.kubernetes.io/cors-allow-credentials | Ingress | 兼容 | 是否允许携带凭证信息
nginx.ingress.kubernetes.io/cors-max-age | Ingress | 兼容 | 预检结果的最大缓存时间

2023-02-10 08:46 UTC, Xunzhuo commented
Thanks @Hinsteny, ping me when you are ready for review.

2023-02-10 12:49 UTC, Hinsteny commented
@Xunzhuo Please help to Review it again

2023-02-14 03:18 UTC, Xunzhuo approved these changes
Generally LGTM, thank you @Hinsteny !

2023-02-14 03:46 UTC, merged