feat: multi-stages build wasm-go
alibaba/higress pull request #192
Opened 2023-02-16 07:41 UTC by dspo

### Ⅰ. Describe what this PR did

使用 `make build` 会从头构建 wasm-go 的 builder 镜像，然后使用 tinygo 构建 wasm。
构建过程中会下载 Go 和 Tinygo 安装包，以及执行 apt-get update，会花费大量时间在网络 IO 上。
如果不想每次构建都从头开始，可以使用分阶段构建。下面介绍分阶段构建的 make 规则。

### `make builder`

`make builder` 用来构建 wasm-go 编译环境镜像。

```bash
make builder
```
<details>
<summary>输出结果</summary>
<pre><code>You can use the following command to build the final image in the next stage
WASM_BUILDER=wasm-go-builder:go1.20-tinygo0.27.0 PLUGIN_NAME=hello-world make bb
</code></pre>
</details>

可以指定 `GO_VERSION`, `TINYGO_VERSION` 参数决定 Go 和 Tinygo 版本号;
指定 `REGISTRY` 设置要推送的镜像仓库。

一旦构建出 builder 镜像，以后就可以复用这个镜像来构建 wasm-go, 而不必每次都从头开始构建。

### `make build-on-builder` 或 `make bb`

`make build-on-builder` 是利用上一阶段输出的 builder 镜像来构建 wasm-go.
`make bb` 是 `make build-on-builder` 的别名。

```bash
WASM_BUILDER=wasm-go-builder:go1.20-tinygo0.27.0 PLUGIN_NAME=request-block make bb
```
<details>
<summary>输出结果</summary>
<pre><code>image:            request-block:20230216-143723-c5845c1
output wasm file: extensions/request-block/plugin.wasm
</code></pre>
</details>

其中 `WASM_BUILDER=wasm-go-builder:go1.20-tinygo0.27.0` 是上一阶段输出的 builder 镜像。

### Ⅱ. Does this pull request fix one issue?

#189 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

无关主要业务逻辑, 无 Go 代码。

### Ⅳ. Describe how to verify it

分别执行 `make build` `make builder` `make bb` 以验证功能。

### Ⅴ. Special notes for reviews
@johnlanni

2023-02-16 08:39 UTC, johnlanni approved these changes

2023-02-16 08:39 UTC, johnlanni commented on plugins/wasm-go/README.md
> +| `TINYGO_VERSION` | 可选的   | 0.25.0                                   | TinyGo 版本号。                                                          |
```suggestion
| `TINYGO_VERSION` | 可选的   | 0.26.0                                   | TinyGo 版本号。                                                          |
```
默认是 0.26 吧

2023-02-17 03:27 UTC, johnlanni commented
流程似乎有点繁琐，是不是可以考虑基于docker buildx实现多platform的构建态镜像，可以自动根据架构拉取对应镜像实现插件编译

2023-02-23 09:53 UTC, dspo commented on plugins/wasm-go/Dockerfile
> +ARG BUILDER=docker.io/chenzhongrun/wasm-go-builder:go1.19-tinygo0.26.0
请提供一个 Higress 构建的 image, 作为默认的 builder

2023-02-23 10:02 UTC, dspo commented
> 流程似乎有点繁琐，是不是可以考虑基于docker buildx实现多platform的构建态镜像，可以自动根据架构拉取对应镜像实现插件编译

已处理。改为使用 wasm-go-builder 作为基础镜像构建 wasm-go plugin 制品，并提供该基础镜像的 Dockerfile 和构建方法（可使用 docker buildx 或 podman 构建 multi-arch image）

2023-02-24 01:49 UTC, johnlanni requested changes

2023-02-24 01:49 UTC, johnlanni commented on plugins/wasm-go/README.md
> +## 构建 wasm-go-builder 镜像
这个 readme 里可以不用介绍，如果有时间，可以 makefile里添加下用于构建基础镜像的命令，

2023-02-24 04:26 UTC, johnlanni approved these changes
LGTM

2023-02-24 04:26 UTC, merged