e2e: add testcases for whitelist-source-range annotations
alibaba/higress pull request #220
Opened 2023-02-27 18:50 UTC by PerforMance308

### Ⅰ. Describe what this PR did
#197 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-02-28 14:55 UTC, PerforMance308 commented
Does anyone have any ideas about why I failed the `Build and Test / coverage-test (pull_request)` CI?

2023-02-28 16:15 UTC, Charlie17Li commented
@PerforMance308 I've had this problem before. Just resubmit it

2023-02-28 16:16 UTC, PerforMance308 commented
> @PerforMance308 I've had this problem before. Just resubmit it

Thank you, will do that

2023-03-01 03:03 UTC, Xunzhuo commented on test/ingress/conformance/tests/httproute-whitelist-source-range.yaml
> +              number: 8080
nit: need a line at the end of yaml.

2023-03-01 03:04 UTC, Xunzhuo requested changes
nit, otherwise, lgtm.

2023-03-02 02:22 UTC, Xunzhuo approved these changes
LGTM, thanks!

2023-03-03 09:55 UTC, merged