doc: fix key_auth plugin readme
alibaba/higress pull request #256
Opened 2023-03-24 13:53 UTC by casun18

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-03-24 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=256) it.</sub>

2023-03-24 13:54 UTC, CH3CHO requested changes
“网关实例级别开启”一节里的例子是不是也需要改一下？

2023-03-24 14:05 UTC, casun18 commented
> “网关实例级别开启”一节里的例子是不是也需要改一下？
已修改

2023-03-24 14:08 UTC, CH3CHO approved these changes
LGTM

2023-03-25 07:50 UTC, johnlanni approved these changes
LGTM

2023-03-25 07:50 UTC, merged