README translation of key-auth plugin
alibaba/higress pull request #279
Opened 2023-04-07 15:48 UTC by Fkbqf

### Ⅰ. Describe what this PR did

README translation of the key-auth plugin
### Ⅱ. Does this pull request fix one issue?

#71 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-04-07 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=279) it.</sub>

2023-04-08 06:16 UTC, CH3CHO requested changes

2023-04-08 06:16 UTC, CH3CHO commented on plugins/wasm-cpp/extensions/key_auth/README_EN.md
> +After the authentication is passed, a `X-Mse-Consumer` field will be added to the header of the request. In this example, its value is `consumer1`, which is used to identify the name of the caller
Before letter "X", we should use "an" instead of "a". And there should be a stop (".") at the end of sentence.

2023-04-08 06:16 UTC, CH3CHO commented on plugins/wasm-cpp/extensions/key_auth/README_EN.md
> +**The request does not provide an API Key, returns 401**
What is the subject of "returns 401"?

2023-04-08 08:37 UTC, Fkbqf commented on plugins/wasm-cpp/extensions/key_auth/README_EN.md
> +**The request does not provide an API Key, returns 401**
> What is the subject of "returns 401"?

sry, corrected

2023-04-09 06:09 UTC, merged