optimize hpa & pdb version select
alibaba/higress pull request #40
Opened 2022-11-08 12:42 UTC by johnlanni

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-11-08 13:53 UTC, iutx commented
👍It's handled very quickly. 
The same commit.I started by trying to abstract the common library package, referenced by higress and istio. However, istio officials have already processed it, and only need add an hpa template to higress.

https://github.com/iutx/higress/commit/83a08286f8775683f30e6fd2ac11f98dca889e80

2022-11-08 14:13 UTC, SpecialYang requested changes

2022-11-08 14:13 UTC, SpecialYang commented on helm/istiod/values.yaml
> +  autoscalingv2API: true
Can we hide it? Can we determine which version should be used based-on k8s cluster version?

2022-11-09 02:28 UTC, SpecialYang approved these changes

2022-11-09 02:29 UTC, merged