feat: add chatgpt-azure-director
alibaba/higress pull request #435
Opened 2023-07-14 09:51 UTC by dspo

### Ⅰ. Describe what this PR did

添加一个 `chatgpt-azure-director` 插件, 可以让 ChatGPT 开发者可以在不修改客户端应用将 ChatGPT 实例从 OpenAI 迁移到 Azure。

此外，支持虚拟 api-key，使得可以基于一个 Azure 实例对 ChatGPT 能力进行二次分发。客户端应用可以基于虚拟 api-key 对使用者进行审计、计费等。

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

按目录下示例配置文件部署 envoy, 使用 OpenAI v1 协议访问 `/v1/models` `/v1/chat/completions` 等接口进行测试。

### Ⅴ. Special notes for reviews

2023-07-14 09:54 UTC, dspo commented
#436

2023-07-14 09:55 UTC, johnlanni commented
666

2023-07-18 02:07 UTC, johnlanni requested changes
请提交下 e2e test case

2024-04-23 07:42 UTC, johnlanni commented
已在AI Proxy插件中实现

2024-04-23 07:42 UTC, closed without merging