Wasm cpp bazel
alibaba/higress pull request #446
Opened 2023-07-21 07:29 UTC by Hinsteny

### Ⅰ. Describe what this PR did
support make build cpp wasmplugin and do e2e test

### Ⅱ. Does this pull request fix one issue?
NO

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
has e2e test case

### Ⅳ. Describe how to verify it
PLUGIN_TYPE=CPP PLUGIN_NAME=key_auth make higress-wasmplugin-test

### Ⅴ. Special notes for reviews
NO

2023-07-24 10:52 UTC, CH3CHO commented on test/e2e/e2e_test.go
> +var wasmPluginName = flag.String("WasmPluginName", "", "")
新加的参数为啥是首字母大写呢？

2023-07-25 05:40 UTC, johnlanni requested changes

2023-07-25 05:40 UTC, johnlanni commented on test/e2e/e2e_test.go
> +var wasmPluginName = flag.String("WasmPluginName", "", "")
@Hinsteny 请保持一致

2023-07-26 02:51 UTC, Hinsteny commented
@CH3CHO @johnlanni Just change the e2e_test file param name start with lowercase, pls help me RE again.

2023-07-26 02:55 UTC, johnlanni approved these changes
LGTM

2023-07-26 02:55 UTC, merged