support configuration domain suffix (#460)
alibaba/higress pull request #463
Opened 2023-08-03 11:18 UTC by teijinyer

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-08-03 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=463) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: teijinyer<br/>:x: yingjinting.yjt<br/><hr/>**yingjinting.yjt** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=463) it.</sub>

2023-08-03 12:37 UTC, johnlanni requested changes

2023-08-03 12:37 UTC, johnlanni commented on pkg/ingress/kube/util/util.go
> +        domainSuffix := os.Getenv("DOMAIN_SUFFIX")
It is more suitable as a global variable to avoid calling os.Getenv every time

2023-08-04 01:45 UTC, johnlanni requested changes

2023-08-04 01:45 UTC, johnlanni commented on pkg/ingress/kube/util/util.go
> +var domainSuffix := os.Getenv("DOMAIN_SUFFIX")
```suggestion
var domainSuffix = os.Getenv("DOMAIN_SUFFIX")
```

2023-08-04 06:34 UTC, CH3CHO requested changes

2023-08-04 06:34 UTC, CH3CHO commented on pkg/ingress/kube/util/util.go
> +	return fmt.Sprintf("%s.%s.svc.%s", name, namespace, domainSuffix)
Incorrect indentations here.

2023-08-04 06:51 UTC, johnlanni requested changes

2023-08-04 06:51 UTC, johnlanni commented on helm/core/templates/controller-deployment.yaml
> +            value: { { .Values.global.proxy.clusterDomain } }
```suggestion
            value: {{ .Values.global.proxy.clusterDomain }}
```

2023-08-07 08:26 UTC, johnlanni approved these changes

2023-08-07 08:26 UTC, merged