fix: routing priorities are not working properly
alibaba/higress pull request #472
Opened 2023-08-09 01:33 UTC by Charlie17Li

### Ⅰ. Describe what this PR did
the routing priorities are not working properly

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-08-09 03:01 UTC, CH3CHO commented on pkg/ingress/kube/common/tool.go
> +		if !caught1 && caught2 {
感觉这里写成二者相同的时候返回其中某一个更好理解一些

2023-08-09 06:05 UTC, johnlanni requested changes

2023-08-09 06:05 UTC, johnlanni commented on pkg/ingress/kube/common/tool.go
> +		if !caught1 && caught2 {
本质是如果加了header匹配，不应该被当作 AllCatch 吧？应该调整 isAllCatch 的判断逻辑，如果method/header/query等非空，则返回 false

2023-08-10 01:26 UTC, johnlanni commented
@Charlie17Li Please fix the UT

2023-08-11 01:55 UTC, johnlanni approved these changes

2023-08-11 01:55 UTC, johnlanni commented
Thanks!

2023-08-11 01:55 UTC, merged