feat: Implement basic-auth WASM plugin using the Go SDK
alibaba/higress pull request #515
Opened 2023-09-10 08:04 UTC by WeixinX

### Ⅰ. Describe what this PR did

用现有 Go SDK 实现 basic-auth, key-auth 等拥有 global_auth, consumer, allow 配置字段的 WASM 插件，同时也测试了 hgctl plugin 相关命令

先实现 basic-auth 进行尝试，如果觉得可行则继续迁移后面的插件

当前的实现方式是：用全局变量保存 globalConfig，但这种方式强依赖 pkg/matcher ParseRuleConfig 中先解析全局配置，再解析域名/路由级配置的逻辑， 否则保存的全局变量就会出错

个人认为这种方式可行，但可能不优雅，且对插件开发者不透明（目前没有更好的解决思路🤕）

### Ⅱ. Does this pull request fix one issue?

fix: #514 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-09-10 09:13 UTC, johnlanni commented
@WeixinX 我想的是可以考虑扩展 pkg/matcher，实现一个 wrapper.ParseOverrideConfigBy ，适配 GlobalConfig 和 RuleConfig 不等价的情况，需要传入2个函数，分别用于 GlobalConfig 和 RuleConfig 的解析，对应的函数类型为：
```go
// 已有的函数类型，可用于处理 GlobalConfig
type ParseConfigFunc[PluginConfig any] func(json gjson.Result, config *PluginConfig, log Log) error
// 新增的函数类型，可用于处理 RuleConfig，会将 GlobalConfig 通过 global 字段传入，可以用于对  PluginConfig 的 override
type ParseRuleConfigFunc[PluginConfig any] func(json gjson.Result, global PluginConfig, config *PluginConfig, log Log) error
```
这样 onHttpRequestHeaders 等方法不用调整，依然传入一个 PluginConfig，只是其中的全局配置已经被 override 好了

2023-09-10 10:39 UTC, WeixinX commented
@johnlanni 我理解错了，我以为不动 sdk 部分，那让我来试试 🫡

2023-09-11 08:30 UTC, WeixinX commented
@johnlanni @Xunzhuo 辛苦 review 啦 ~

2023-09-12 01:37 UTC, johnlanni requested changes

2023-09-12 01:37 UTC, johnlanni commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +		func(js gjson.Result, global PluginConfig, cfg *PluginConfig) error {
是否应该ctx.vm.parseRuleConfig为nil时，这个参数传nil？ 这里始终非nil的话，ParseRuleConfig里判断parseOverrideConfig都是非nil

2023-09-12 03:27 UTC, WeixinX commented on plugins/wasm-go/pkg/wrapper/plugin_wrapper.go
> +		func(js gjson.Result, global PluginConfig, cfg *PluginConfig) error {
oh，又写 bug 了🤥，谢谢指出，我修改下 ~

2023-09-18 03:08 UTC, WeixinX commented
@johnlanni 麻烦 review ~ ❤️

2023-09-18 03:11 UTC, johnlanni approved these changes
Great work! Thanks

2023-09-18 03:13 UTC, merged