feat: support KnativeIngress
alibaba/higress pull request #524
Opened 2023-09-14 10:02 UTC by vikizhao156

### Ⅰ. Describe what this PR did
support KnativeIngress

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-09-15 09:07 UTC, johnlanni requested changes

2023-09-15 09:07 UTC, johnlanni commented on pkg/ingress/config/kingress_config.go
> +		http2rpcs:           make(map[string]*higressv1.Http2Rpc),
These fields seems no usage.

2023-09-15 09:07 UTC, johnlanni commented on pkg/ingress/config/kingress_config.go
> +		return m.convertWasmPlugin(wrapperConfigs), nil
Seems no usage

2023-09-15 09:07 UTC, johnlanni commented on pkg/ingress/kube/kingress/status.go
> +		// search service in the mse vpc
```suggestion
```

2023-09-15 09:08 UTC, johnlanni commented
cc @SpecialYang

2023-09-18 05:58 UTC, vikizhao156 commented
Unused and duplicate code removed

2023-09-22 01:32 UTC, merged