feat:add oidc wasm plugin
alibaba/higress pull request #568
Opened 2023-09-28 14:42 UTC by Fkbqf

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-10-07 11:09 UTC, johnlanni requested changes

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provider.go
> +		err = setSharedData(GithubSharedDataKey, g.AccessToken, g.expires_in)
把token存到网关的内存里，这样实现是有问题的，下次带cookie来请求时，可能不会落在当前这个签发token的网关上

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +				githubProvider := oc.NewGithubProvider(oauth2Config)
有多种类型的provider，应该做一层interface的抽象，核心处理逻辑面向interface处理

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +
这里处理完了，应该直接return，这样后面的else就不用了，整体代码结构会更清晰

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		} else if strings.Contains(ctx.Path(), "oidc/callback") {
同上，这里的else if 可以变成 if

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +			} else {
同上，这里的else可以省略

2023-10-07 11:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +	} else {
同上，else可以省略

2023-10-30 01:55 UTC, johnlanni requested changes

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			re := regexp.MustCompile("<[^>]*>")
regex提前编译，不要在处理过程中编译

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/verifer.go
> +			leeway := 5 * time.Minute
评估下是否做成配置，如果要hardcode，建议通过全局变量进行管理，比较清晰

2023-10-30 01:55 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-oidc.yaml
> +        clientSecret: "SO8LC4b6JDMlVV5t0CdEqBn3mLYlsvN2rUFDIvXRLluK13uACT2dUTMtZDw9dOOP"
这个id和secret建议不要明文提交上来，可以考虑用keycloak等其他方式来做e2e test

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		if strings.Contains(ctx.Path(), "oidc/callback") {
callback路径问题，如线下沟通，待解决

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +	config.RedirectURL = json.Get("redirectUrl").String()
url校验问题，如线下沟通，待解决

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			proxywasm.AddHttpRequestHeader("X-MSE-IDToken", cfg.Option.RawIdToken)
如线下沟通，问题待解决

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/encryption.go
> +	StateSigningKey = "your-secret-key"
如线下沟通，问题待解决

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +package main
所有代码文件添加下copyright header，参考下其他插件，如果代码来自其他lib改动，也在copyright里进行说明

2023-10-30 01:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/cookie.go
> +var encryptionKey = []byte("avery strongkey!")
如线下沟通，问题待解决

2023-10-30 02:10 UTC, johnlanni requested changes

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +	}, 2000); err != nil {
超时时间要可以配置

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			SendError(log, " Miss authorization_endpoint ", http.StatusInternalServerError)
senderror之后不用return吗

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			SendError(log, " Miss token_endpoint ", http.StatusInternalServerError)
同上，类似问题挺多，senderror之后需要return吧？

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +
不用senderror？

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			log.Errorf("failed to verify token: %v", err)
只打印日志 不用中断后续处理吗？

2023-10-30 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +				return
不用senderror？

2023-10-30 02:21 UTC, johnlanni requested changes

2023-10-30 02:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +	v := ReturnURL(cfg.RedirectURL, cfg.Option.Code)
注意变量名命名，不要用单个字母，用有意义的名称

2023-10-30 02:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		log.Debugf("body %v", string(responseBody))
这种debug日志没必要吧

2023-10-30 02:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			log.Errorf("Incorrect invocation, retrying with different auth style")
应该用Error，不是Errorf

2023-10-30 02:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		log.Debugf("set cookie")
不要留这些自己debug时的日志，显得很不正式

2023-10-30 02:21 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Util.go
> +func GetParams(cookie string, path string) (string, string, string) {
建议用命名返回值，更清晰些：
func GetParams(cookie, path string) (cookie, code, state string) {

2023-10-30 06:46 UTC, johnlanni requested changes

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +| timeOut         | int     | 选填 | 500 （毫秒）       | 设置请求与认证服务连接的超时时长。如果频繁遇到超时错误，建议增加该时长。                          |
建议字段名称中透出单位，例如 timeoutMillis

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +	oc.IsValidRedirect(json.Get("redirectUrl").String())
redirectUrl 必须以callback结尾吧？这里是否应该校验下

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		if strings.Contains(ctx.Path(), "oauth2/callback") {
确定是 oauth2/callback，不需要支持配置了是么

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +| redirectUrl     | string  | 必填 | -              | 输入授权成功后的重定向地址，需要与 OIDC 中配置的重定向地址保持一致。该地址的后缀需为oauth2/callback。 |
看下其他插件的配置字段风格，都是下划线的，不是用驼峰

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/README.md
> +| redirectUrl     | string  | 必填 | -              | 输入授权成功后的重定向地址，需要与 OIDC 中配置的重定向地址保持一致。该地址的后缀需为oauth2/callback。 |
插件配置字段命名都是下划线的，不是驼峰，你参考下其他插件

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +	DefaultHandler := oc.NewDefaultOAuthHandler()
注意变量名命名规范，local变量首字母小写

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +	tm := time.Now()
注意命名规范

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +// Copyright (c) 2022 Alibaba Group Holding Ltd.
注意文件命名 provider.go

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Config.go
> +// Copyright (c) 2022 Alibaba Group Holding Ltd.
这个文件命名为什么是大写 Config

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Util.go
> +// Copyright (c) 2022 Alibaba Group Holding Ltd.
文件命名大写问题

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			d.ProcessToken(log, cfg)
重新调一次，不会无限递归吗？

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +	ProcessToken(log *wrapper.Log, cfg *Oatuh2Config) error
processToken和ProcessTokenVerify只有在handler内部调用，无需暴露给外部，是否不应该在interface中

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +	ProcesTokenVerify(log *wrapper.Log, cfg *Oatuh2Config) error
注意命名 ProcessTokenVerify

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		//todo
todo what?

2023-10-30 06:46 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +			d.ProcessRedirect(log, cfg)
这里不应直接调用ProcessRedirect，这样又要重复请求一次openid-configuration，对应的configuration获取到后，应该存入到userContext中：https://github.com/alibaba/higress/blob/901ad9619daa7a015086af1d5623b1b45cb1422f/plugins/wasm-go/pkg/wrapper/plugin_wrapper.go#L220-L226

2023-10-30 06:47 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +type OidcHandler interface {
给 interface 里每个方法增加注释，说明这个方法要完成什么功能

2023-10-30 06:55 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		codeURL := cfg.AuthCodeURL(statStr, opts)
这个函数定义在哪里，没找到

2023-10-30 07:00 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		codeURL := cfg.AuthCodeURL(statStr, opts)
cfg继承了oatuh2这个结构体，这个是oatuh2 的lib方法，用于封装authcodeurl

2023-10-30 07:09 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/Provide.go
> +		codeURL := cfg.AuthCodeURL(statStr, opts)
了解了

2023-10-30 07:54 UTC, CH3CHO commented on plugins/wasm-go/extensions/oidc/oc/Util.go
> +		return fmt.Errorf("expected Content-Type = application/json or application/json;charset=UTF-8, but got %s", contentType)
charset 是别的行吗，不是 UTF-8？似乎判定也没说不能是别的吧？

2023-10-30 07:56 UTC, CH3CHO commented on plugins/wasm-go/extensions/oidc/oc/Util.go
> +		return errors.New("call failed with status code")
是不是 statusCode 的值得写进去？

2023-10-30 10:38 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/oc/Util.go
> +		return errors.New("call failed with status code")
这个后面是放进去的

2023-10-30 13:36 UTC, johnlanni requested changes

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
这里为什么返回pause

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
返回pause时，如果没有sendresonse，或者也没有callback触发resume，请求就会一直卡住

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/provider.go
> +	defautl := NewDefaultOAuthHandler()
　default

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/provider.go
> +			jws, err := GenJswkey(val)
jsw 还是jws？

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/provider.go
> +			return
这里得senderror吧

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/provider.go
> +			log.Errorf("failed to verify token: %v", err)
需要senderror吧

2023-10-30 13:36 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/oc/util.go
> +func GetParams(name, cookie string, path string, key string) (oidcCookieValue, code, state string, err error) {
这里函数参数不应该这样写么：name, cookie, path, key string

2023-10-30 13:36 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-oidc.yaml
> +        client_secret: "hsvkkm0Rry2GfHwuSzhABWOTS3f2IVsJYfGNhMJwVdrxVCQToTDFcbKOGd1apTKO"
麻烦改成keycloak接入方式，不要存阿里云服务的key secret

2023-10-30 13:40 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
提前返回不让函数走下面的逻辑，这个exchange完token,会种cookie和跳转回用户指定的client_url

2023-10-30 13:42 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/oc/provider.go
> +			jws, err := GenJswkey(val)
jsonWebKey 这里需要改成jsw

2023-10-30 13:42 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
看下上面评论，如果没有sendresponse或者没有其他callback触发resume，pause会导致请求一直被卡住

2023-10-30 13:44 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		}
这里，如果请求不是callback path，是不是就卡住了

2023-10-30 13:45 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
senderror之后返回什么状态码都没关系，不过返回continue更不容易有误解，因为这里的pause并不能pause已经sendresponse之后的请求

2023-10-30 14:06 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
我明白您意思，这里预期来的请求是不携带的token
不挟带code来到的请求在ProcessRedirect中会被sendresonse到重定向地址登陆，
挟带code交换含有oauth2/callback路径来的会去交换token,检验完token后的也会sendresonse用户指定重定向地址，
进来的不携带oauth2/callback是非常预期外，我在配置里面校验必须携带oauth2/callback路径，在这里改成
		oc.SendError(&log, fmt.Sprintf("CallBack URL must end with oauth2/callback"), http.StatusBadRequest)
		return types.ActionContinue 
	这样合适吗

2023-10-31 03:59 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
可以的

2023-10-31 04:44 UTC, Fkbqf commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
我实验结果还是不行，因为这里加了return types.Actionpause的目的是为了去掉上面说的else,但是如果改成oc.SendError(&log, fmt.Sprintf("CallBack URL must end with oauth2/callback"), http.StatusBadRequest)
return types.ActionContinue

有可能还没来的及触发回调函数里面回调函数的重定向，就可能结束流程，走到了这里CallBack URL must end with oauth2/callback, 要比预期回调的触发早，就不能正常走其他流程

2023-10-31 05:42 UTC, johnlanni commented on plugins/wasm-go/extensions/oidc/main.go
> +		return types.ActionPause
你再梳理下，应该是满足callback path时return pause，不满足时 return continue

2023-10-31 09:15 UTC, johnlanni approved these changes
LGTM, Thanks!

2023-10-31 09:15 UTC, merged