fix gateway name
alibaba/higress pull request #672
Opened 2023-12-06 11:57 UTC by johnlanni

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

fix #667 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-12-11 02:58 UTC, SpecialYang requested changes
没看gw vs资源的name在哪生成的？

2023-12-11 02:58 UTC, SpecialYang commented on pkg/ingress/kube/common/tool.go
> +	return hexStr[:16]
我建议直接返回 hex.EncodeToString，这个一定是32位。另外只取前16会不会冲突？

2023-12-11 02:58 UTC, SpecialYang commented on pkg/ingress/kube/common/tool.go
> +func hashToDNSLabel(input string) string {
这个方法名字看着很怪

2023-12-11 02:58 UTC, SpecialYang commented on pkg/ingress/kube/common/tool.go
>  	if host == "*" {
要不统一hash了吧？不对*特殊处理了

2023-12-11 02:58 UTC, SpecialYang commented on pkg/ingress/kube/kingress/controller.go
> +	"github.com/alibaba/higress/pkg/ingress/kube/annotations"
这个文件整体的import顺序不对

2023-12-11 03:53 UTC, johnlanni commented on pkg/ingress/kube/common/tool.go
> +	return hexStr[:16]
done

2023-12-11 03:53 UTC, johnlanni commented on pkg/ingress/kube/common/tool.go
> +func hashToDNSLabel(input string) string {
done

2023-12-11 03:53 UTC, johnlanni commented on pkg/ingress/kube/common/tool.go
>  	if host == "*" {
done

2023-12-11 03:53 UTC, johnlanni commented on pkg/ingress/kube/kingress/controller.go
> +	"github.com/alibaba/higress/pkg/ingress/kube/annotations"
fixed

2023-12-11 06:40 UTC, johnlanni commented on pkg/ingress/config/kingress_config.go
> +			gateways = append(gateways, m.namespace+"/"+common.CreateConvertedName(m.clusterId, "*"))
这样更内聚一些，代码可读性好一些，成员变量没有太大必要

2023-12-12 06:15 UTC, SpecialYang commented on pkg/ingress/config/kingress_config.go
> +			gateways = append(gateways, m.namespace+"/"+common.CreateConvertedName(m.clusterId, "*"))
那这样会一直重复计算吧？毕竟是hash计算

2023-12-12 07:17 UTC, johnlanni commented on pkg/ingress/config/kingress_config.go
> +			gateways = append(gateways, m.namespace+"/"+common.CreateConvertedName(m.clusterId, "*"))
嗯 是的，不过我觉得这里的性能影响也很小，相比下还是可读性重要些

2023-12-14 03:04 UTC, SpecialYang approved these changes

2023-12-14 03:04 UTC, merged