feat: implement custom-response plugin in the golang version
alibaba/higress pull request #689
Opened 2023-12-13 01:59 UTC by cr7258

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/alibaba/higress/issues/592

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-12-13 01:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/higress?pullRequest=689) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/higress?pullRequest=689) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/higress?pullRequest=689) it.</sub>

2023-12-13 05:34 UTC, johnlanni commented
cc @WeixinX

2023-12-23 12:16 UTC, WeixinX requested changes
逻辑不符合预期，请再仔细对照并参考 CPP 的实现~

2023-12-23 12:16 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
当插件用于 Mock 响应（enableOnStatus 为空）时，可以在 onHttpRequestHeaders 里使用 proxywasm.SendHttpResponse 自定义响应；若用于修改响应（enableOnStatus 非空）时，在 onHttpRequestHeaders 里返回 types.ActionContinue 即可。参考 CPP:

```c++
FilterHeadersStatus PluginRootContext::onRequest(
    const CustomResponseConfigRule& rule) {
  if (!rule.enable_on_status.empty()) {
    return FilterHeadersStatus::Continue;
  }
  sendLocalResponse(rule.status_code, "", rule.body, rule.headers);
  return FilterHeadersStatus::StopIteration;
}
```

2023-12-23 12:16 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
而对于修改响应（enableOnStatus 非空）这种用例，需要在 onHttpResponseHeaders 进行处理，即通过 proxywasm.GetHttpResponseHeader(":status") 获取状态码与 enableOnStatus 列表中的状态码匹配，若命中，则返回自定义响应信息，否则直接返回 types.ActionContinue。参考 CPP:

```c++
FilterHeadersStatus PluginRootContext::onResponse(
    const CustomResponseConfigRule& rule) {
  GET_RESPONSE_HEADER_VIEW(":status", status_code);
  bool hit = false;
  for (const auto& status : rule.enable_on_status) {
    if (status_code == status) {
      hit = true;
      break;
    }
  }
  if (!hit) {
    return FilterHeadersStatus::Continue;
  }
  replaceResponseHeader(Wasm::Common::Http::Header::ContentType,
                        rule.content_type);
  sendLocalResponse(rule.status_code, "", rule.body, rule.headers);
  return FilterHeadersStatus::StopIteration;
}
```

2023-12-27 02:44 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +	enableOnStatus uint32            `yaml:"enable_on_status"`
Done

2023-12-27 02:44 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +	config.statusCode = uint32(json.Get("status_code").Int())
Done

2023-12-27 02:45 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +func parseConfig(json gjson.Result, config *CustomResponseConfig, log wrapper.Log) error {
Done

2023-12-27 02:47 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
@WeixinX  已根据建议完成了所有的修改，请重新review，谢谢。
另外我看到 `Build and Test Plugins / higress-wasmplugin-test (GO) (pull_request)` 测试失败了，但是我在本地跑的时候是成功的。
```
PLUGIN_TYPE=GO make higress-wasmplugin-test
......
--- PASS: TestHigressConformanceTests (50.32s)
    --- SKIP: TestHigressConformanceTests/CPPWasmPluginsBasicAuth (0.00s)
    --- SKIP: TestHigressConformanceTests/CPPWasmPluginsKeyAuth (0.00s)
    --- SKIP: TestHigressConformanceTests/CPPWasmPluginsRequestBlock (0.00s)
    --- PASS: TestHigressConformanceTests/WasmPluginsBasicAuth (1.08s)
        --- PASS: TestHigressConformanceTests/WasmPluginsBasicAuth/WasmPlugins_basic-auth (1.05s)
    --- PASS: TestHigressConformanceTests/WasmPluginsCustomResponse (1.06s)
        --- PASS: TestHigressConformanceTests/WasmPluginsCustomResponse/WasmPlugins_custom-response (1.04s)
    --- PASS: TestHigressConformanceTests/WasmPluginsJwtAuth (1.03s)
        --- PASS: TestHigressConformanceTests/WasmPluginsJwtAuth/WasmPlugins_jwt-auth (1.01s)
    --- PASS: TestHigressConformanceTests/WasmPluginsRequestBlock (1.04s)
        --- PASS: TestHigressConformanceTests/WasmPluginsRequestBlock/WasmPlugins_request-block (1.03s)
    --- PASS: TestHigressConformanceTests/WasmPluginTransformer (1.06s)
        --- PASS: TestHigressConformanceTests/WasmPluginTransformer/WasmPlugin_transformer (1.03s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteAppRoot (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteCanaryHeaderWithCustomizedHeader (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteCanaryHeader (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteCanaryWeight (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteConsulHttpBin (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteDefaultBackend (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteDownstreamEncryption (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteEnableCors (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteEnableIgnoreCase (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteEurekaRegistry (0.00s)
    --- SKIP: TestHigressConformanceTests/HttpForceRedirectHttps (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteFullPathRegex (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteHostNameSameNamespace (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteHttp2Rpc (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteMatchHeaders (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteMatchMethods (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteMatchPath (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteMatchQueryParams (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRoutePermanentRedirectCode (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRoutePermanentRedirect (0.00s)
    --- SKIP: TestHigressConformanceTests/HttpRedirectAsHttps (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteRequestHeaderControl (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteRewriteHost (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteRewritePath (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteSameHostAndPath (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteSimpleSameNamespace (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteTemporalRedirect (0.00s)
    --- SKIP: TestHigressConformanceTests/HTTPRouteWhitelistSourceRange (0.00s)
PASS
ok  	command-line-arguments	50.937s
```

2023-12-27 10:51 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
测试失败是因为 tinygo 编译报错

2023-12-27 11:11 UTC, johnlanni commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
编译问题还没来得及看，应该是镜像的系统兼容问题导致的

2023-12-27 11:53 UTC, WeixinX requested changes

2023-12-27 11:53 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +func parseConfig(json gjson.Result, config *CustomResponseConfig, log wrapper.Log) error {
CPP 实现中有这么一段逻辑：

```c++
  if (!JsonArrayIterate(
          configuration, "headers", [&](const json& item) -> bool {
            auto header = JsonValueAs<std::string>(item);
            if (header.second != Wasm::Common::JsonParserResultDetail::OK) {
              LOG_WARN("cannot parse header");
              return false;
            }
            std::vector<std::string> pair =
                absl::StrSplit(header.first.value(), absl::MaxSplits("=", 2));
            if (pair.size() != 2) {
              LOG_WARN("invalid header pair format");
            }
            if (absl::AsciiStrToLower(pair[0]) ==
                Wasm::Common::Http::Header::ContentLength) {
              return true;
            }
            if (absl::AsciiStrToLower(pair[0]) ==
                Wasm::Common::Http::Header::ContentType) {
              rule.content_type = pair[1];
              has_content_type = true;
              return true;
            }
            rule.headers.emplace_back(pair[0], pair[1]);
            return true;
          })) {
    LOG_WARN("failed to parse configuration for headers.");
    return false;
  }
```

它提取了头部 `content-type`，用于设置 content_type, has_content_type 参数，并忽略头部 `content-length` 。请添加相应逻辑和必要的测试用例。

2023-12-27 11:53 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
可能是我之前表述不太清楚，该插件的逻辑是这样的：

当 `enable_on_status` 为空时，该插件用于 Mock 响应，也就是说请求不会到达具体的服务后端，它会到达插件，并根据插件配置内容进行响应。因此对于这种情况，需要在 onHttpRequestHeaders 进行处理，而不是 onHttpResponseHeaders，前者是在到达具体后端前触发（before），后者是在后端向客户端响应时触发（after）。

当 `enable_on_status` 非空时，说明该插件用于匹配对应的后端响应状态码，若命中则修改后端的响应，所以在 onHttpResponseHeaders 进行处理没错。

请重点修改上述逻辑。

2023-12-27 11:53 UTC, WeixinX commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
建议同时添加一些 headers 字段进行测试 ~

2023-12-28 03:08 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +func parseConfig(json gjson.Result, config *CustomResponseConfig, log wrapper.Log) error {
添加了 `content-type` 和 `content-length` 相应的处理逻辑

2023-12-28 03:08 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +func onHttpResponseHeaders(ctx wrapper.HttpContext, config CustomResponseConfig, log wrapper.Log) types.Action {
逻辑已重新修改

2023-12-28 03:10 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
现在的测试框架是读取echoserver返回的body内容来判断请求和响应的元数据信息，由于mock将body修改了，因此无法对header进行判断。

2023-12-28 07:40 UTC, WeixinX requested changes

2023-12-28 07:40 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +		_, err := json.Marshal(config.body)
如果要验证 body 是否是有效 json，可以使用 json.Valid([]byte(body))

2023-12-28 07:40 UTC, WeixinX commented on plugins/wasm-go/extensions/custom-response/main.go
> +	config.enableOnStatus = make([]uint32, len(enableOnStatusArray))
假设 enableOnStatusArray == [200, 404, 502]，那么下面这段 append 逻辑会得到 config.enableOnStatus == [0, 0, 0, 200, 404, 502]，所以应该：

```go
config.enableOnStatus = make([]uint32, 0, len(enableOnStatusArray))
```

2023-12-28 08:17 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +	config.enableOnStatus = make([]uint32, len(enableOnStatusArray))
已修复，又写bug了 🤣

2023-12-28 08:17 UTC, cr7258 commented on plugins/wasm-go/extensions/custom-response/main.go
> +		_, err := json.Marshal(config.body)
已更新

2024-01-08 02:44 UTC, cr7258 commented
@WeixinX Hello, 问一下这个PR目前还有什么需要修改的地方吗？

2024-01-08 03:14 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
#733 这个PR正在支持，可以在合入之后再支持下这块的e2e 测试

2024-01-08 07:06 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
好的

2024-01-09 12:22 UTC, WeixinX approved these changes
LGTM

2024-01-12 06:10 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
@cr7258 e2e测试已经支持body的测试了，可以补充下测试用例

2024-01-12 06:12 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
OK

2024-01-12 06:13 UTC, johnlanni requested changes

2024-01-12 06:13 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
可以参考下：https://github.com/alibaba/higress/blob/a71ecf41d18426b264f9ec937cb5c171dfac5926/test/e2e/conformance/tests/go-wasm-transformer.go#L179-L192

2024-02-01 15:01 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.yaml
> +spec:
@johnlanni 测试用例已经补充

2024-02-17 10:48 UTC, WeixinX commented on test/e2e/conformance/tests/go-wasm-custom-response.go
> +			{
case3 预期与 ci 实际结果不符，请修复具体逻辑 ~

```bash
Sending Request:
< GET / HTTP/1.1
< Host: baz.com
< User-Agent: Go-http-client/1.1
< X-Echo-Set-Header: 
< Accept-Encoding: gzip
< 
< 

Received Response:
< HTTP/1.1 401 Unauthorized
< Content-Length: 78
< Content-Type: text/plain
< Date: Sat, 17 Feb 2024 10:23:08 GMT
< Server: istio-envoy
< Www-Authenticate: Basic realm=MSE Gateway
< 
< Request denied by Basic Auth check. No Basic Authentication information found.

    http.go:318: Response expectation failed for actual request: {{http   localhost /  false false   } baz.com HTTP GET map[X-Echo-Set-Header:[]] []  false <nil>}  not ready yet: expected status code to be 200, got 401 (after 1.583µs)
```

2024-02-17 10:57 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.go
> +			{
我发现这个测试案例有的时候成功，有的时候失败。 应该是basic-auth和custom-response插件的执行顺序是随机的，我试下加上优先级试试确保custom-response在basic-auth之前执行。

2024-02-18 01:35 UTC, cr7258 commented on test/e2e/conformance/tests/go-wasm-custom-response.go
> +			{
添加优先级后 https://github.com/alibaba/higress/pull/689/commits/959842539f54640fd44f2efffc228198d6d70bf2，测试案例通过

2024-02-20 01:39 UTC, johnlanni approved these changes
LGTM

2024-02-20 01:39 UTC, merged