feat: add request-validation plugin
alibaba/higress pull request #700
Opened 2023-12-16 14:59 UTC by sjcsjc123

### Ⅰ. Describe what this PR did

添加request validation的插件

### Ⅱ. Does this pull request fix one issue?

fixes: #682

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

后面补充一下

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

根据个人的理解去改的，没有照搬apisix，类比于apisix添加验证策略方式大致如下：
```yaml
{
    "body_schema": {
        "filed1": {
          "required": true,
          "type": "string",
          "minLength": 1,
          "maxLength": 10
        },
        "filed2": {
          "required": true,
          "type": "string",
          "minLength": 1,
          "maxLength": 10,
          "pattern": "^[a-zA-Z0-9]+$"
        }
    }
}
```
每个字段的object类型会映射为各自的策略方式，header写法一样，也可添加校验失败返回的code和message

2023-12-18 02:05 UTC, johnlanni requested changes

2023-12-18 02:05 UTC, johnlanni commented on plugins/wasm-go/extensions/request-validation/main.go
> +type Schema struct {
这里我们应该使用JsonSchema，因为Swagger和OAS3都是遵循JsonSchema，这个插件可以用于导入一份Swagger或OAS3格式的API文档后，基于文档约束对API请求进行校验。
可以参考下：https://swagger.io/docs/specification/data-models/keywords/

2023-12-18 04:28 UTC, sjcsjc123 commented on plugins/wasm-go/extensions/request-validation/main.go
> +type Schema struct {
好的，目前应该主要在字段`field1`  `filed2` 上面不支持这个规范，后面我修改一下

2023-12-18 05:40 UTC, johnlanni commented on plugins/wasm-go/extensions/request-validation/main.go
> +type Schema struct {
不是的，整个body可以被JsonSchema表示，你可以看下OAS3的规范

2023-12-18 05:42 UTC, johnlanni commented on plugins/wasm-go/extensions/request-validation/main.go
> +type Schema struct {
例如这是一个OAS3规范的API文档配置片段，schema 字段内的内容就是基于JsonSchema表示的:

```yaml
paths:
  /users:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example:   # Sample object
                id: 10
                name: Jessica Smith
      responses:
        '200':
          description: OK
```

2023-12-21 02:05 UTC, johnlanni commented
https://github.com/xeipuuv/gojsonschema
可以使用这个lib来做json schema的解析和校验

2023-12-22 09:05 UTC, sjcsjc123 commented
> https://github.com/xeipuuv/gojsonschema 可以使用这个lib来做json schema的解析和校验

好的

2023-12-25 05:38 UTC, johnlanni commented
@sjcsjc123 那这个PR我先转为draft了 等实现了json schema的解析校验之后再review下

2023-12-29 15:03 UTC, sjcsjc123 commented
@johnlanni 

>由于e2e暂不支持body传参，以及header暂只支持string类型，e2e测试提供的样例并不全面，以下为本地测试简单样例的结果。

**采用docker compose的方式来模拟wasm和envoy。**

- 本地header相关的测试结果如下：
![image](https://github.com/alibaba/higress/assets/88550136/d5cbf1b8-234d-444c-b034-a82a4daba8b2)
- 本地body相关的测试结果如下：
![image](https://github.com/alibaba/higress/assets/88550136/76404db2-4790-4a0e-a5a2-5d2a9e31d0b8)

2024-01-02 01:53 UTC, johnlanni commented
@sjcsjc123 建议用petstore的addpet接口来做一下测试：https://petstore.swagger.io/#/pet/addPet

2024-01-02 02:19 UTC, sjcsjc123 commented
> @sjcsjc123 建议用petstore的addpet接口来做一下测试：https://petstore.swagger.io/#/pet/addPet

我理解的是，为e2e框架添加新的测试板块，去构造一个支持携带body的http request请求，发送给wasm插件进行过滤，然后转发给addpet接口判断能否返回200响应是吗？

2024-01-02 02:27 UTC, johnlanni commented
@sjcsjc123 e2e框架支持带body测试的工作(#733 )目前正在做，你可以等这个完成再做测试，或者本地先手动测试一下也可以

2024-01-02 02:33 UTC, sjcsjc123 commented
好的，我等 #733 完成

2024-01-14 16:37 UTC, sjcsjc123 commented
@johnlanni e2e测试已完善body校验

2024-02-02 08:52 UTC, johnlanni approved these changes
LGTM

2024-02-02 08:52 UTC, merged