feat: add e2e test for envoy filter
alibaba/higress pull request #710
Opened 2023-12-18 16:05 UTC by sjcsjc123

### Ⅰ. Describe what this PR did

扩展e2e框架，使其支持envoy config的校验，并提供了make命令，可只执行envoy config相关的e2e测试

### Ⅱ. Does this pull request fix one issue?

fixes: #703 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

给出了configmap的tracing部分的e2e测试样例，执行`make higress-envoy-config-test`可只运行envoy config相关的测试，本地测试已通过

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-12-18 16:28 UTC, sjcsjc123 commented
![image](https://github.com/alibaba/higress/assets/88550136/3a4c91dc-f118-450e-a78a-b2ac611ce64d)
hgctl可正常执行

json文件如何添加license信息，这里testdata是移动过来的

2023-12-19 01:45 UTC, johnlanni commented
@sjcsjc123 License check failed, please add copyright to these go files.

2023-12-19 01:46 UTC, johnlanni commented
cc @Xunzhuo @2456868764

2023-12-19 02:13 UTC, johnlanni commented on pkg/config/testdata/config/input/in.all.json
> +
请去掉空行这样的类似改动

2023-12-19 02:16 UTC, sjcsjc123 commented on pkg/config/testdata/config/input/in.all.json
> +
已修复

2023-12-19 05:53 UTC, 2456868764 commented on test/e2e/conformance/utils/envoy/envoy.go
> +	TargetNamespace          string
这里测试用例角度看，这里有三种行为：检查Path 存在，检查Path不存在， 检查Path存在情况下匹配配置。 这里加个属性 ExpectAction 值为 Existed, NotExisted, Match

2023-12-19 05:54 UTC, 2456868764 commented on test/e2e/conformance/utils/envoy/envoy.go
> +	ExceptContainEnvoyConfig map[string]interface{}
这个名称为 ExpectContainEnvoyConfig 更合适一些

2023-12-19 06:00 UTC, 2456868764 commented on test/e2e/conformance/utils/envoy/envoy.go
> +func AssertEnvoyConfig(t *testing.T, expected Assertion) error {
变更配置，Envoy config 生效有一定延时，这里有超时，和重试等机制更合适， 可以参考 WaitForConsistentResponse func

2023-12-19 06:11 UTC, 2456868764 commented on test/e2e/conformance/tests/configmap-tracing.yaml
> +  higress: |-
这里 configmap  higress 配置是测试用例数据，需要测试不同场景结果，yaml只执行一次，放在这里有些问题，可以看一下 gzip这块测试 已经合并到主分支，可以考虑换成 gzip envoy 配置测试。

2023-12-19 06:18 UTC, sjcsjc123 commented on test/e2e/conformance/tests/configmap-tracing.yaml
> +  higress: |-
我也尝试过适配多个场景，目前只想到给出多个yaml文件，在testCase里修改指向yaml文件的信息来测试不同场景

2023-12-19 06:18 UTC, sjcsjc123 commented on test/e2e/conformance/utils/envoy/envoy.go
> +	ExceptContainEnvoyConfig map[string]interface{}
笔误

2023-12-19 06:20 UTC, sjcsjc123 commented on test/e2e/conformance/utils/envoy/envoy.go
> +	TargetNamespace          string
好的

2023-12-21 02:31 UTC, johnlanni requested changes

2023-12-21 02:31 UTC, johnlanni commented on Makefile.core.mk
> +.PHONY: higress-envoy-config-test
我不建议和 higress-conformance-test 分开，因为这部分配置的修改还是会影响到 conformance 的用例的

2023-12-21 02:36 UTC, johnlanni requested changes

2023-12-21 02:36 UTC, johnlanni commented on test/e2e/conformance/utils/envoy/envoy.go
> +	CheckTypeNotExist CheckType = "notexist"
加个TODO吧，可以支持定位判断，例如listener里name为xxx的config里是否match/exist/notexist，这样这个配置检查功能会更通用。可以用于一般的e2e test，而非只是envoyfilter的场景。

2023-12-21 02:40 UTC, sjcsjc123 commented on Makefile.core.mk
> +.PHONY: higress-envoy-config-test
这里参考的higress-wasmplugin-test部分，可让开发者只运行envoyfilter相关的测试，节省时间，其次修改flags参数也是可以的，这里用处不大

2023-12-21 02:41 UTC, sjcsjc123 commented on test/e2e/conformance/utils/envoy/envoy.go
> +	CheckTypeNotExist CheckType = "notexist"
好的

2023-12-21 07:03 UTC, sjcsjc123 commented on Makefile.core.mk
> +.PHONY: higress-envoy-config-test
已移除

2023-12-22 04:49 UTC, 2456868764 commented on test/e2e/conformance/utils/envoy/envoy.go
> +		return wait.PollImmediate(1*time.Second, 10*time.Second, func() (bool, error) {
这里测试逻辑 wait.PollImmedaite 是每隔 1秒钟 获取 envoy config 同时测试测试用例看用例是否通过。 问题点在于
比如延后一秒钟去获取到 envoyconfig ( 这个envoyconfig 有可能是没有生效，但是获取成功， 如果这个envoyconfig 通过这个测试用例， 那这个测试用例可能是有问题的（没有办法判断）。 可以参考做法
1. wait.PollImmedaite 用每隔两秒（延时2秒） 去获取 envoyconfig, 保证获取 envoyconfig 成功
2. 用第1步那到 envoyconfig 去测试测试用例记录测试是否成功。

把 1 和 2 包在一个 超时 （比如1分钟内）和重试 func 方法里，要连续判断一下 测试成功次数超过 比如3次。

你可以看一下 http测试 WaitForConsistentResponse， awaitConvergence func
本质是在30秒内要连续3次测试通过，才测试通过。

2023-12-22 04:51 UTC, 2456868764 commented on test/e2e/conformance/utils/kubernetes/helpers.go
> +	err = wait.PollImmediate(1*time.Second, 60*time.Second, func() (bool, error) {
这里可以不用加， 增加获取envoyconfig 延时时间就可以。

2023-12-22 09:07 UTC, 2456868764 commented on test/e2e/conformance/utils/envoy/envoy.go
> +func findKey(actual interface{}, key string, expectValue interface{}) {
这里最好用 func  返回值，不要用 flag 变量控制

2023-12-22 09:08 UTC, 2456868764 commented on test/e2e/conformance/utils/suite/suite.go
>  		s.SupportedFeatures = AllFeatures
这里没有把 envoy config feature 加到 AllFeatures

2023-12-22 09:10 UTC, 2456868764 commented on test/e2e/conformance/tests/configmap-gzip.go
> +				"window_bits":        12,
少了 DisableOnEtagHeader 比较

2023-12-22 09:11 UTC, 2456868764 commented on test/e2e/conformance/tests/configmap-gzip.go
> +			Path:            "configs",
这里Path是否可以直接定位定 httpConnectionManager 级别

2023-12-22 09:16 UTC, 2456868764 commented on pkg/config/gateway_config.go
> +package config
可以把这config package 移到 cmd/hgctl 下

2023-12-22 09:20 UTC, sjcsjc123 commented on pkg/config/gateway_config.go
> +package config
是pkg/cmd/hgctl还是cmd/hgctl

2023-12-22 09:32 UTC, 2456868764 commented on pkg/config/gateway_config.go
> +package config
这个是否移到 cmd/hgctl 下合适一些？

2023-12-22 09:36 UTC, sjcsjc123 commented on test/e2e/conformance/tests/configmap-gzip.go
> +				"window_bits":        12,
![image](https://github.com/alibaba/higress/assets/88550136/3cf14e37-c9d9-43e6-ba24-a8d6256a827f)
并没有DisableOnEtagHeader相关的信息

2023-12-22 11:10 UTC, 2456868764 commented on test/e2e/conformance/tests/configmap-gzip.go
> +				"window_bits":        12,
我看了是 gzip 代码BUG， DisableOnEtagHeader 这个位置设置错误，我提个PR 修复一下

2023-12-22 12:02 UTC, sjcsjc123 commented on test/e2e/conformance/tests/configmap-gzip.go
> +				"window_bits":        12,
好的

2023-12-25 05:49 UTC, 2456868764 commented on test/e2e/conformance/tests/configmap-gzip.go
> +				"window_bits":        12,
修复 DisableOnEtagHeader PR已经合并到主分支，这里麻烦再加一下这个属性

2023-12-26 06:56 UTC, 2456868764 commented
LGTM

2023-12-29 13:34 UTC, sjcsjc123 commented
@johnlanni

2023-12-29 13:38 UTC, johnlanni approved these changes

2023-12-29 13:39 UTC, merged