feat: optimize transformer go wasm plugin
alibaba/higress pull request #712
Opened 2023-12-19 10:10 UTC by Uncle-Justice

### Ⅰ. Describe what this PR did
1. 支持双向转换
2. map支持跨类型映射
3. kvt操作顺序自定义
4. 操作内部的字段命名优化

### Ⅱ. Does this pull request fix one issue?

#587 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
已附带响应e2e测试

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

> map支持跨类型映射

目前的代码结构决定了，map操作的顺序是headers->querys->body，即如果我要做headers的map操作，映射来源是querys时，实际参考的数据是未被transform过的旧query，以上逻辑应该是合理的，不过或许需要在readme中追加说明。

2023-12-19 12:51 UTC, johnlanni commented
请 @WeixinX  看下

2023-12-24 09:35 UTC, WeixinX requested changes
除了一下修改意见外，也请麻烦更新 README，另外由于 E2E 还未支持 body 的校验，在本地调试时也请多关注一下 ~

2023-12-24 09:35 UTC, WeixinX commented on plugins/wasm-go/extensions/transformer/main.go
> +			headers, err := proxywasm.GetHttpRequestHeaders()
> GetHttpRequestHeaders is used for retrieving HTTP request headers. Only available during types.HttpContext.OnHttpRequestHeaders and types.HttpContext.OnHttpStreamDone.

有一种方案是在 onHttpRequestHeaders 时获取 headers，并通过 ctx 传递。586 行同理。

也请添加 map from header 的测试用例 ~

2023-12-24 12:01 UTC, Uncle-Justice commented on test/e2e/conformance/tests/go-wasm-transformer.yaml
>            type: request
已完成。在yaml中删除type这个不必要的字段

2023-12-24 12:15 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
>  	// @Title 转换器类型
已删除非解释性的代码注释

2023-12-24 12:37 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +	paramType    ParamType
已将`Param.paramType`类型修改为`string`，直接根据`operate`值进行初始化；删除`ParamType`类型声明

2023-12-24 13:43 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +	if mapSource == "body" && (isHeaderChange || isQueryChange) {
已将不支持map的条件更加细化。比如此处，必须在headers或者query中检测出map操作，才不支持相应map操作

2023-12-24 15:28 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +			headers, err := proxywasm.GetHttpRequestHeaders()
1. 已在`onHttpReq/RespBody`中对headers和query的获取方式改为通过`ctx`
2. 已增加map from header to query的测试用例，发现因为在之前的代码读取headers时会将其全部改为小写（`func convertHeaders(hs [][2]string) map[string][]string`），而qquery并未做这样的操作， 导致如果headers中的某个fromKey含大写字母，query匹配不上，只能匹配小写版的fromKey，请问这个算预期内行为吗？

2023-12-24 15:29 UTC, Uncle-Justice commented on test/e2e/conformance/tests/go-wasm-transformer.yaml
> +    - ingress:
已将`transform-request-map-from-querys-to-headers`修改为只测试map效果

2023-12-24 16:02 UTC, Uncle-Justice commented on test/e2e/conformance/tests/go-wasm-transformer.yaml
> +        - higress-conformance-infra/wasmplugin-transform-request-arbitary-rule-order
> 感觉这个 operate 顺序可以与 remove->rename->replace->add->append->map->dedupe 差异更大些？

已改为上述的逆序operate测试

2023-12-25 08:39 UTC, Uncle-Justice commented
@WeixinX 谢谢你的指导和建议，以上修改意见均已做相应改动，README也已经更新。关于body的测试，在https://github.com/alibaba/higress/pull/733 中，我已经写了一点测试用例，后续等https://github.com/alibaba/higress/pull/733 合并后我会追加更完整的测试用例

麻烦recheck

2023-12-28 01:36 UTC, WeixinX requested changes

2023-12-28 02:48 UTC, WeixinX requested changes

2023-12-28 02:48 UTC, WeixinX commented on plugins/wasm-go/extensions/transformer/main.go
> +	typ     string
map 不需要 typ 字段，dedupe 同理

2023-12-28 05:48 UTC, johnlanni commented
@WeixinX proxywasm.GetHttpRequestHeaders() 获取到的header都是小写的

2023-12-28 07:38 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/README.md
> +| :----: | :----: | :----: | :----: | -------- |
已改正

2023-12-30 11:41 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +	typ     string
已删除```mapKvt```与```dedupeKvt```中的```typ```字段以及相应初始化逻辑

2023-12-30 11:42 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
>  type kvtGroup struct {
已删除未使用的```kvtGroup```结构

2023-12-30 12:43 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +	paramType    string
你说得对，这个后面也没有使用，该字段现已删除

2023-12-30 16:17 UTC, Uncle-Justice commented on plugins/wasm-go/extensions/transformer/main.go
> +			headers, err := proxywasm.GetHttpRequestHeaders()
已修改为：当映射来源为headers时，fromKey以小写形式去做匹配

2024-01-09 06:19 UTC, WeixinX approved these changes
LGTM

2024-01-18 06:52 UTC, johnlanni commented
@Uncle-Justice Please resolve the conflicts.

2024-01-18 07:58 UTC, Uncle-Justice commented
@johnlanni Roger that

2024-01-18 08:04 UTC, johnlanni approved these changes
Thanks!

2024-01-22 05:40 UTC, merged