feat: add sni-misdirect plugin for go
alibaba/higress pull request #720
Opened 2023-12-20 16:39 UTC by sjcsjc123

### Ⅰ. Describe what this PR did

添加go语言实现的sni-misdirect插件

### Ⅱ. Does this pull request fix one issue?

fixes: #595 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

提供部分e2e测试样例

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

目前e2e测试框架暂不支持发送http2请求

2023-12-21 02:11 UTC, johnlanni requested changes

2023-12-21 02:11 UTC, johnlanni commented on plugins/wasm-go/extensions/sni-misdirect/main.go
> +	}
这行下面的逻辑有问题，你和cpp的逻辑再对照下

2023-12-22 08:52 UTC, sjcsjc123 commented on plugins/wasm-go/extensions/sni-misdirect/main.go
> +	}
已修改

2023-12-25 06:52 UTC, johnlanni approved these changes
Thanks, LGTM

2023-12-25 06:52 UTC, merged