feat: e2e test support http body check
alibaba/higress pull request #733
Opened 2023-12-23 17:22 UTC by Uncle-Justice

### Ⅰ. Describe what this PR did
1. 支持e2e test发送POST请求，支持json，text/plain等类型的body
2. 支持e2e test对echo的body内容进行校验，支持json，text/plain等类型的body

### Ⅱ. Does this pull request fix one issue?

#551 #724 
### Ⅲ. Why don't you add test cases (unit test/integration test)? 

1. 已增加request-block go-wasm插件的测试用例，验证e2e框架能够发送POST请求并校验text/plain类型的body
2. 已增加transformer go-wasm插件的测试用例，验证e2e框架能够发送POST请求并校验json类型的body

### Ⅳ. Describe how to verify it
运行所有的插件e2e测试

### Ⅴ. Special notes for reviews

2023-12-25 06:55 UTC, johnlanni commented
cc @2456868764

2023-12-25 10:32 UTC, 2456868764 commented on test/e2e/conformance/utils/roundtripper/roundtripper.go
> +	method := request.Method
这里最好保持代码兼容，如果没有设置request.method, method 默认是 GET

2023-12-25 12:29 UTC, 2456868764 commented on test/e2e/conformance/utils/roundtripper/roundtripper.go
> +	if request.Method == "GET" {
这里建议是否 GET / POST 都返回同样 CapturedRequest 内容结构，如果 为POST， cReq 里body为空。这里要保持一致，而不是要区分不同method， method为POST时也可以做比如 Header等判断

2023-12-25 12:39 UTC, Uncle-Justice commented on test/e2e/conformance/utils/roundtripper/roundtripper.go
> +	method := request.Method
已改回原样，method默认GET，若request.Method不为空则依据request.Method

2023-12-25 12:41 UTC, 2456868764 commented
> cc @2456868764

我看了这个PR，主要在于支持POST请求时，请求返回 cReq 只包含 content-type 和 返回body， 而GET请求返回 cReq 包含 Path, Host,Method, Headers 等内容， 这样造成 POST 只能用于 body和cotent-type 断言，不能包含其他比如 Headers, Path, Host等断言，我建议 POST请求也要支持GET请求里包含内容。

@Uncle-Justice @johnlanni

2023-12-29 01:36 UTC, johnlanni requested changes

2023-12-29 01:36 UTC, johnlanni commented on test/e2e/conformance/utils/roundtripper/roundtripper.go
> +	} else if request.Method == "POST" {
e2e框架不应该根据Method做特殊判断，增加对于rawbody，rawheady的校验即可

2023-12-29 01:37 UTC, johnlanni requested changes

2023-12-29 01:37 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-transformer.go
> +					ExpectedResponse: http.Response{
比如实现一个 ExpectedRawResponse

2023-12-29 07:03 UTC, Uncle-Justice commented on test/e2e/conformance/utils/roundtripper/roundtripper.go
> +	} else if request.Method == "POST" {
好的

2023-12-30 12:32 UTC, Uncle-Justice commented
@johnlanni @2456868764 

总结：backend服务增加了可选为```echo-body```之后，最核心的问题在于**捕获请求```CapturedRequest```的赋值方式可能发生变化**

至于测试后续的比较过程```CompareRequest```主要比较的就是```CapturedRequest```与```ExpectedResponse```里面的header&body，比较的部分的确可以不分是GET还是POST，只追加对body部分的比较即可，没有怎么破坏原有的逻辑


但是以下情况应该是需要增加二选一判断的（不区分GET或POST）：
1. 当实际发出的请求中不含body时，后端应为```echo-server```，```CapturedRequest```的赋值方式应为client实际收到的**response body**中直接提取

2. 当实际发出的请求中含body时，后端应为```echo-body```，```CapturedRequest```的赋值方式应为client实际收到的response中直接提取，header对header，body对body

---

因此我计划的改动为：根据```ActualRequest```中有无body数据来确定```CapturedRequest```的赋值方式。

以上最大的问题在于，测试人员可能在```ActualRequest```中增加了body数据，但是backend误选为了echo-server，我能想到的补救措施是做一点检查，比如此情况下检测到client收到的response body中含有"headers"字段，就弹一个warn，提醒可能是后端服务选错了。

2023-12-30 12:53 UTC, johnlanni commented
@Uncle-Justice 不是的 echo sever会将请求body塞在响应的json中，依然可以用于校验网关是否对request body做了预期的修改，请求body的校验只能基于echo server。相比之下echo sever是个更通用的测试后端，而echo body目前只是用于插件需要特定的响应body来触发特定测试case。

2023-12-31 07:40 UTC, Uncle-Justice commented
详细沟通后总结：

1. echo-server backend增加返回body["body"]的功能，对于Request的校验，目前只支持backend为echo-server这种返回```body["headers"], body["body"]```的情况
2. echo-body backend支持返回raw header以及raw body
3. 对于Response的校验，追加body读取和校验的逻辑，不限定具体的backend，只需要测试人员写明期望的body和headers形式即可
4. 不支持测试人员在同一个测试用例中，同时要求```ExpectedRequest```和```ExpectedRepsonse```
5. 对于Request和Reponse，均支持同时对Headers，body等内容的断言

2024-01-09 07:11 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +		expected.Meta.CompareTarget = "Request"
这里Request 和 Response建议定义常量

2024-01-09 07:48 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +			if cReq.Headers["Content-type"] == nil || len(cReq.Headers["Content-type"]) == 0 {
这里 获取 content-type 时 Coent-type 大小写是否有影响？

2024-01-09 07:51 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +			cTyp := cReq.Headers["Content-type"][0]
这里coent-type 大小写？

2024-01-09 09:03 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +		if expected.Request.ExpectedRequest.Body != nil && len(expected.Request.ExpectedRequest.Body) > 0 {
CompareRequest 和 CompareReponse 这里增加很多功能，建议根据不同 content-type写个unit test？

2024-01-09 10:25 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +		if expected.Request.ExpectedRequest.Body != nil && len(expected.Request.ExpectedRequest.Body) > 0 {
这里根据不同 content-type， 建议写下 unit test

2024-01-09 10:25 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +func CompareResponse(cRes *roundtripper.CapturedResponse, expected Assertion) error {
建议写下 unit test

2024-01-09 11:20 UTC, Uncle-Justice commented on test/e2e/conformance/utils/http/http.go
> +		expected.Meta.CompareTarget = "Request"
已将"Reqeust"&"Response"定义为常量CompareTargetRequest&CompareTargetResponse。涉及到该常量的比较或者测试输入也已做响应改动

2024-01-09 11:26 UTC, Uncle-Justice commented on test/e2e/conformance/utils/http/http.go
> +			if cReq.Headers["Content-type"] == nil || len(cReq.Headers["Content-type"]) == 0 {
http中的header内容读取进来的时候，对所有的kv对应该都是不区分大小写的

不过为了统一写法，本PR中涉及到的该字段已全部修改为```Content-Type```

2024-01-09 12:36 UTC, 2456868764 commented on test/e2e/conformance/utils/http/http.go
> +			if cReq.Headers["Content-type"] == nil || len(cReq.Headers["Content-type"]) == 0 {
这里 cReq.Headers 是从 返回 Response  json.Unmarshal 过来map, 这里 key 是区分大小写的。 resp.Header.Get("Content-type") 这个方法是不区分大小写。

2024-01-09 13:01 UTC, Uncle-Justice commented on test/e2e/conformance/utils/http/http.go
> +			if cReq.Headers["Content-type"] == nil || len(cReq.Headers["Content-type"]) == 0 {
你说的有道理，从```cReq.Headers```这个```map[string][]string```中取的时候需要注意key的大小写问题，已全部统一为```Content-Type```

2024-01-12 04:08 UTC, 2456868764 commented
LGTM

2024-01-12 06:08 UTC, merged