feat(plugin): implement golang version of plugin jwt-auth
alibaba/higress pull request #743
Opened 2023-12-31 07:55 UTC by Ink-33

### Ⅰ. Describe what this PR did
This merge request contains the `jwt-auth` plugin implemented in golang.   

### Ⅱ. Does this pull request fix one issue?

#232 , #591 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Test cases are still in progress due to the complexity.

### Ⅳ. Describe how to verify it
As #589, all behaviors of this plugin should be same with the currently cpp verison of `jwt-auth`. Maybe we need to use plently of tese cases to verify it.

### Ⅴ. Special notes for reviews
Same with IV. Since I am not particularly familiar with cpp, I hope that reviewers will understand some errors and I will correct them in time🙏

2024-03-04 06:50 UTC, johnlanni commented
@Ink-33 Is this draft PR ready for review, or is there still unfinished work?

2024-03-04 06:53 UTC, Ink-33 commented
> @Ink-33 Is this draft PR ready for review, or is there still unfinished work?

Yes it's ready for review and I will update the branch later today.

2024-03-04 08:36 UTC, johnlanni commented
@Ink-33 Please add an e2e test for it.

2024-05-15 13:07 UTC, Ink-33 commented on plugins/wasm-go/extensions/jwt-auth/go.mod
> +toolchain go1.21.5
should be removed

2024-05-15 13:07 UTC, Ink-33 commented on plugins/wasm-go/extensions/jwt-auth/go.mod
> +go 1.21
switch to 1.19

2024-05-16 01:39 UTC, johnlanni commented
@Ink-33 Please add e2e test cases, refer to: https://github.com/alibaba/higress/pull/759/files#diff-00090f4cf6417f2566ebc91e56b6b5d0e12a834a184f4b814d51bc89581d796b

2024-05-16 01:45 UTC, Ink-33 commented
> @Ink-33 Please add e2e test cases, refer to: https://github.com/alibaba/higress/pull/759/files#diff-00090f4cf6417f2566ebc91e56b6b5d0e12a834a184f4b814d51bc89581d796b

got it. I would like to add three parts of test cases including normal, rejected, and normal with all features one by one.

btw, how to run e2e test case on my local dev environments?

2024-05-16 01:55 UTC, johnlanni commented
> > @Ink-33 Please add e2e test cases, refer to: https://github.com/alibaba/higress/pull/759/files#diff-00090f4cf6417f2566ebc91e56b6b5d0e12a834a184f4b814d51bc89581d796b
> 
> got it. I would like to add three parts of test cases including normal, rejected, and normal with all features one by one.
> 
> btw, how to run e2e test case on my local dev environments?

Please refer this guide: https://github.com/alibaba/higress/tree/main/test#how-to-implement-test-environment-reusability

2024-05-18 13:00 UTC, Ink-33 commented on test/e2e/conformance/tests/go-wasm-jwt-auth.go
> +
here need to add
```
Register(WasmPluginsJWTAuth...)
```

2024-05-20 08:26 UTC, Ink-33 commented
@johnlanni allow 里面配置多个 consumer 且全部验证失败应该返回哪个错误码给请求，或者直接用 verify failed 兜底呢？

![Image_1716193181343.png](https://github.com/alibaba/higress/assets/51873347/67b6f5f9-dd32-4f31-ab76-be695c28e8a9)

2024-05-20 08:37 UTC, johnlanni commented
> @johnlanni allow 里面配置多个 consumer 且全部验证失败应该返回哪个错误码给请求，或者直接用 verify failed 兜底呢？
> 
> ![Image_1716193181343.png](https://private-user-images.githubusercontent.com/51873347/331994592-67b6f5f9-dd32-4f31-ab76-be695c28e8a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQzMDMsIm5iZiI6MTcxNjE5NDAwMywicGF0aCI6Ii81MTg3MzM0Ny8zMzE5OTQ1OTItNjdiNmY1ZjktZGQzMi00ZjMxLWFiNzYtYmU2OTVjMjhlOGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA4MzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODZiZjhkY2QyZGUxZWIzMWZkNzIxOWRkMThmOTU1ZTk3ZGQ5MmNjYjYxMjVlNjYxODNiNzNjZTI0ZGVlNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-VzWCRZ9QmDQ6zTX0hrz5Y_hEpr6BoH_wd8aOcrsX4)

返回 403 即可，错误原因可以用 verify failed

2024-05-24 07:32 UTC, johnlanni requested changes

2024-05-24 07:32 UTC, johnlanni commented on plugins/wasm-go/extensions/jwt-auth/config/parser.go
> +	// GlobalAuth 为 true 时代表插件全局启用，需要标记 enabled 为 true
貌似没看到解析生成 config.GlobalAuth的代码？

类似：https://github.com/alibaba/higress/blob/e09edff827b94fa5bcc149bbeadc905361100c2a/plugins/wasm-go/extensions/basic-auth/main.go#L149-L153v

2024-05-24 07:51 UTC, Ink-33 commented on plugins/wasm-go/extensions/jwt-auth/config/parser.go
> +	// GlobalAuth 为 true 时代表插件全局启用，需要标记 enabled 为 true
我用那个GlobalAuthCheck去做了一下判断但是好像没覆盖全部情况，我看下怎么改

2024-06-06 02:19 UTC, johnlanni approved these changes
LGTM, Thanks！

2024-06-06 02:22 UTC, merged