feat: e2e test opt
alibaba/higress pull request #746
Opened 2023-12-31 10:05 UTC by sjcsjc123

### Ⅰ. Describe what this PR did

e2e测试优化，实现测试环境复用

### Ⅱ. Does this pull request fix one issue?

#709 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-01-05 02:01 UTC, johnlanni commented
cc @2456868764

2024-01-10 12:09 UTC, 2456868764 commented on test/e2e/e2e_test.go
> +func TestCleanHigressConformanceTests(t *testing.T) {
CleanupBaseResources 这个参数为 True 才 cleanup

2024-01-10 12:10 UTC, 2456868764 commented on test/e2e/conformance/utils/suite/suite.go
>  func (suite *ConformanceTestSuite) Run(t *testing.T, tests []ConformanceTest) {
Cleanup 清除内容和 Setup里面内容要保存一致，包括 Secret 和 suite.BaseManifests内容

2024-01-10 12:16 UTC, 2456868764 commented on Makefile.core.mk
> +# higress-conformance-test-prepare prepares the environment for higress conformance tests.
这里可以增加 合并 docker-build kube-load-image install-dev 主要build, load image to cluster 动作。可以把整个e2e测试拆分成 1. prepare (包括build 和 load images)  2. build & load images 3. run higress-e2e test  4. cleanup 四个动作。

2024-01-11 10:07 UTC, 2456868764 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
这里是什么情况考虑要拆分成三个Test方法？

2024-01-11 11:19 UTC, sjcsjc123 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
在makefile里的run-higress-e2e步骤会自动按照顺序执行这三个方法。拆分成三个，可以复用prepare里生成的base resource资源，修改e2e代码后直接运行run方法，测试结束后，执行clean方法清除base resource

2024-01-11 11:19 UTC, sjcsjc123 commented on Makefile.core.mk
> +# higress-conformance-test-prepare prepares the environment for higress conformance tests.
1和2是否重复了，prepare是指创建kind集群吗

2024-01-11 11:23 UTC, sjcsjc123 commented on test/e2e/conformance/utils/suite/suite.go
>  func (suite *ConformanceTestSuite) Run(t *testing.T, tests []ConformanceTest) {
我印象中清除namespace，会自动清除所有的secret之类的；添加上去也可

2024-01-11 11:30 UTC, 2456868764 commented on Makefile.core.mk
> +# higress-conformance-test-prepare prepares the environment for higress conformance tests.
有个情况是比如 higress-controller 代码变更后，是否需要重新build，部署到cluster里，然后再重新运行 e2e 测试？

2024-01-11 11:34 UTC, 2456868764 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
修改e2e代码后直接运行run方法，是指手动运行 TestRunHigressConformanceTests 这个方法吗？

2024-01-11 11:54 UTC, 2456868764 commented on test/e2e/conformance/utils/suite/suite.go
>  func (suite *ConformanceTestSuite) Run(t *testing.T, tests []ConformanceTest) {
我看了一下namaespace 都在 manifests.yaml里创建，只删除manifests.yaml资源也OK。

2024-01-11 12:04 UTC, sjcsjc123 commented on test/e2e/conformance/utils/suite/suite.go
>  func (suite *ConformanceTestSuite) Run(t *testing.T, tests []ConformanceTest) {
好的

2024-01-11 12:05 UTC, sjcsjc123 commented on Makefile.core.mk
> +# higress-conformance-test-prepare prepares the environment for higress conformance tests.
这个可以通过hgctl的code-debug功能，不需要重新build，[地址](https://higress.io/zh-cn/blog/e2e-debug#higress-core%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95e2e%E6%B5%8B%E8%AF%95)

2024-01-11 12:06 UTC, sjcsjc123 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
对的，就不需要重新准备base resource之类的或者跳过base resource的检查

2024-01-12 07:03 UTC, sjcsjc123 commented
@2456868764 已取消移除cleanup参数，不过只能放在TestClean方法上，三个func不共享testing.T，会在prepare阶段就把base resource给清理了

2024-01-16 07:37 UTC, 2456868764 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
主要为了可以单独手动运行测试 tests.ConformanceTests里测试内容， 分开三个测试方法，同时依赖这三个测试执行次序来完成一次完整 e2e 测试，感觉不是很好方法，现在是要把 make run-higress-e2e-test 分成三个阶段 base，运行测试，cleanup, 我建议 e2e_test.go 增加一个参数比如 --test-phase, --test-phase 有三个值:base, test, cleanup, 默认值为空，如果为空就执行base,test, 和 cleanup三个动作一个完整 e2e test.  同时make 时增加一个环境变量： TEST_PHASE, 比如  TEST_PHASE=base make run-higress-e2e-test 这样就只执行base阶段。

2024-01-16 07:55 UTC, sjcsjc123 commented on test/e2e/e2e_test.go
> +func TestPrepareHigressConformanceTests(t *testing.T) {
```
go test -v -tags conformance ./test/e2e/e2e_test.go --ingress-class=higress --debug=true
```
这个命令是按照顺序执行这三个Test方法，添加这个flag参数是有什么用处吗

是否可以这样理解，三个Test方法还是改成一个Test方法，用这个flag来控制运行SetUp/Run/Clean方法

伪代码：
```
func TestRunTest(){
      //如果包含Base
      if flag.Base {
           Setup(t)
     }
     //如果包含Test
     if flag.Test {
          Run(t, comformance)
     }
     //如果包含Clean
      if flag.Clean {
         Clean(t)
     }
}
```

这样的话开发者在开发的过程中，需要反复修改flag参数，似乎会增加复杂度，但也有一个好处就是三个Test方法共用了一个testing.T，能够避免setup的时候就已经清除base resource了

2024-01-17 00:33 UTC, 2456868764 commented
LGTM

2024-01-22 05:50 UTC, johnlanni commented
https://github.com/alibaba/higress/tree/main/test

@sjcsjc123 请更新一下这篇[README](https://github.com/alibaba/higress/blob/main/test/README.md) ，补充下在本地运行e2e test时复用环境的建议

2024-01-22 15:06 UTC, sjcsjc123 commented
> https://github.com/alibaba/higress/tree/main/test
> 
> @sjcsjc123 请更新一下这篇[README](https://github.com/alibaba/higress/blob/main/test/README.md) ，补充下在本地运行e2e test时复用环境的建议

已添加

2024-01-24 06:09 UTC, johnlanni requested changes

2024-01-24 06:09 UTC, johnlanni commented on test/README.md
> +> Note: You can use `TestArea` flag to control which area you want to run.
简单说明要复用e2e环境的步骤是怎样即可，可以加一小节。
另外可以帮忙把这篇README搞一个中文版本吗 🙏

2024-01-24 08:55 UTC, sjcsjc123 commented on test/README.md
> +> Note: You can use `TestArea` flag to control which area you want to run.
已添加

2024-01-24 08:58 UTC, sjcsjc123 commented
@2456868764 之前test-area为setup的时候存在cleanup为true在setup阶段就清除环境的问题。需要重新review。

2024-01-24 09:03 UTC, sjcsjc123 commented on test/e2e/conformance/utils/flags/flags.go
> +	TestArea             = flag.String("test-area", "all", "Test area to run, like all to run setup/run/clean, setup to run setup only, run to run run only, clean to run clean only")
已更改解释

2024-01-26 08:45 UTC, johnlanni approved these changes
LGTM, Thanks!

2024-01-26 08:45 UTC, merged