close #590
alibaba/higress pull request #747
Opened 2024-01-03 11:14 UTC by OnlyPiglet

### Ⅰ. Describe what this PR did

Implement the Golang version of the existing CPP Wasm plugin: bot-detect

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-01-05 01:59 UTC, johnlanni commented
cc @WeixinX

2024-01-08 03:08 UTC, johnlanni commented
@OnlyPiglet Please add an e2e test for it like this PR: #720

2024-01-09 12:06 UTC, WeixinX requested changes

2024-01-10 03:03 UTC, OnlyPiglet commented
> @OnlyPiglet Please add an e2e test for it like this PR: #720

👌

2024-01-10 03:04 UTC, OnlyPiglet commented on plugins/wasm-go/extensions/bot-detect/README.md
> +_rules_:
👌，I will change this

2024-01-26 08:51 UTC, johnlanni commented
@OnlyPiglet hello，这块e2e test补充有进展吗

2024-01-28 02:05 UTC, OnlyPiglet commented
> @OnlyPiglet hello，这块e2e test补充有进展吗

finished will merge this

2024-01-31 01:57 UTC, johnlanni requested changes

2024-01-31 01:57 UTC, johnlanni commented on plugins/wasm-go/extensions/bot-detect/README.md
> +## 对特定路由或域名开启
这里可以不用说明，在wasmplugin crd里会统一说明通过crd配置如何实现路由/域名生效

2024-01-31 03:36 UTC, OnlyPiglet commented on plugins/wasm-go/extensions/bot-detect/README.md
> +## 对特定路由或域名开启
👌

2024-01-31 03:51 UTC, johnlanni approved these changes
LGTM

2024-02-02 08:57 UTC, merged