feat: add debug mode for higress
alibaba/higress pull request #753
Opened 2024-01-04 15:21 UTC by sjcsjc123

### Ⅰ. Describe what this PR did

为higress提供debug模式的启动方式，开发者无须重新构建higress-core镜像

### Ⅱ. Does this pull request fix one issue?

fixed: #729
 
### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

后面补充

### Ⅴ. Special notes for reviews

2024-01-04 15:52 UTC, sjcsjc123 commented
- 运行higress debug后，controller， gateway pods重启正常

![image](https://github.com/alibaba/higress/assets/88550136/7301af21-c8e8-4107-9435-0b3d0d14af5c)

- configmap中xds地址替换正常

![image](https://github.com/alibaba/higress/assets/88550136/e8edeaf1-834c-49a2-a66f-3e8e44b19540)

- e2e测试正常，e2e执行过程中，本地higress有对应的日志产生

![image](https://github.com/alibaba/higress/assets/88550136/5213abed-f700-470d-9f30-efc0fb0baf60)

- 运行higress recover命令后，controller， gateway pods重启正常

![image](https://github.com/alibaba/higress/assets/88550136/cc66c545-e486-4b37-afb8-bcdf451cc959)

- configmap中xds地址恢复正常

![image](https://github.com/alibaba/higress/assets/88550136/7526d07f-ca96-4e67-8a60-1d3feae7ab36)

- e2e测试正常

![image](https://github.com/alibaba/higress/assets/88550136/d8fdcdc0-34ce-457f-bc9f-a5fccbb8e565)

2024-01-05 01:58 UTC, johnlanni requested changes

2024-01-05 01:58 UTC, johnlanni commented on pkg/cmd/server.go
> +			err = updateXdsIpAndRollout(clientSet, ip, serverArgs.GrpcAddress)
这个在启动命令里修改不合适，建议做成hgctl的子命令，因为修改之后是需要改回来的。

2024-01-05 01:58 UTC, johnlanni commented on pkg/cmd/server.go
> +		Use:     "debug",
是否做成server子命令下的参数即可，无需做成单独的子命令，我理解需要调整的地方只有kubeconfig的来源，至于GatewaySelectorValue调整server子命令下的参数默认值即可

2024-01-05 05:08 UTC, sjcsjc123 commented
计划修改如下：

- higress serve debug子命令，通过debug的方式，修改GatewaySelectorValue默认值，kubeconfig依然让开发者手动指定
- hgctl code-debug run命令，修改xds地址，并重启deployment
- hgctl code-debug clean命令，恢复xds地址，并重启deployment

2024-01-05 14:02 UTC, sjcsjc123 commented
![image](https://github.com/alibaba/higress/assets/88550136/3c6aa592-0b5c-4efc-aca8-fa7fcf78964f)
@johnlanni 本地已通过测试

2024-01-08 02:19 UTC, johnlanni approved these changes
LGTM

2024-01-08 02:19 UTC, merged