feat: wasm support opa (Open Policy Agent)
alibaba/higress pull request #760
Opened 2024-01-07 13:41 UTC by baerwang

### Ⅰ. Describe what this PR did
#680 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-01-08 02:10 UTC, johnlanni requested changes

2024-01-08 02:10 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/main.go
> +	filename string
filename这个配置似乎无意义。我们是否应该支持配置多个module规则，然后配置每个module规则对应的规则名？

2024-01-08 04:16 UTC, baerwang commented on plugins/wasm-go/extensions/opa/main.go
> +	filename string
每个流量对应module嘛

2024-01-11 05:48 UTC, johnlanni commented
cc @WeixinX

2024-01-11 06:02 UTC, johnlanni requested changes

2024-01-11 06:02 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/main.go
> +		proxywasm.SendHttpResponse(http.StatusForbidden, nil, []byte("opa state not is 200"), -1)
这块是否透传opa的错误码？建议参考下apisix的实现

2024-01-11 06:02 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/main.go
> +	if !rsp["result"].(bool) {
强制类型转换可能crash，需要判断类型转换是否成功

2024-01-11 07:54 UTC, baerwang commented on plugins/wasm-go/pkg/common/client.go
> +func Client(json gjson.Result) (wrapper.HttpClient, error) {
新写的插件还要再写这一块的代码，重复性太多了，需要统一封装，这个也是重复的逻辑https://github.com/alibaba/higress/blob/5e509e7032ca6cbf4ebd944f299bcbc60e027cf1/plugins/wasm-go/extensions/oidc/main.go#L133

2024-01-11 07:56 UTC, baerwang commented on plugins/wasm-go/extensions/opa/main.go
> +func uriParams(path string) map[string]string {
这个没有的

2024-01-11 08:07 UTC, baerwang commented on plugins/wasm-go/extensions/opa/main.go
> +		proxywasm.SendHttpResponse(http.StatusForbidden, nil, []byte("opa state not is 200"), -1)
apisix有个插件可以处理状态的，我返回400，apisix会帮我处理成4x之类的

2024-01-12 03:08 UTC, johnlanni commented on plugins/wasm-go/pkg/common/client.go
> +func Client(json gjson.Result) (wrapper.HttpClient, error) {
但是可能和用户自己插件的配置字段冲突，还是放进插件里吧。框架里做到ClusterClient这个粒度的封装就足够了。

2024-01-12 03:27 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/main.go
> +func uriParams(path string) map[string]string {
说错了，net/url库，例如：
u,_ := url.Parse(path)
params, _:=url.ParseQuery(u.RawQuery)

2024-01-15 09:43 UTC, johnlanni commented
https://github.com/alibaba/higress/tree/main/test/e2e/conformance/base

你看看是不是应该把opa server的yaml放进base manifest里，可以确保在跑case时，这个pod ready了

2024-01-15 09:55 UTC, johnlanni commented
https://github.com/alibaba/higress/blob/a71ecf41d18426b264f9ec937cb5c171dfac5926/test/e2e/conformance/utils/suite/suite.go#L120-L126

注意下这里

2024-01-15 10:25 UTC, baerwang commented
> https://github.com/alibaba/higress/blob/a71ecf41d18426b264f9ec937cb5c171dfac5926/test/e2e/conformance/utils/suite/suite.go#L120-L126
> 
> 注意下这里

还是不行

2024-01-16 07:29 UTC, sjcsjc123 commented on test/e2e/conformance/tests/go-wasm-opa.go
> +					TargetNamespace: "infra-backend-v1",
这里是否要与go-wasm-opa.yaml里的NameSpace保持一致，TargetBackend也是？

比如TargetNamespace改成higress-conformance-infra
TargetBackend改成infra-backend-v1

2024-01-17 01:47 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +    servicePort: 8181
没有配置namespace，我看测试用例里请求超时了

2024-01-17 01:49 UTC, johnlanni commented on test/e2e/conformance/base/manifests.yaml
> +        - name: infra-backend-v1
这里的修改去掉一下，原本锁进没有问题

2024-01-17 01:49 UTC, johnlanni commented on test/e2e/conformance/base/opa.yaml
> +  namespace: higress-conformance-app-backend
注意下时这个namespace，你的插件配置里要配上

2024-01-17 02:04 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/main.go
> +	}
需要补充一下单元测试

2024-01-18 02:43 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: curl-opa
为什么是请求到 curl-opa，而且我没看到有这个名称的service，只有一个pod

2024-01-18 02:44 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +    servicePort: 8181
还是没有配置namespace?

2024-01-18 02:44 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.go
> +					TargetBackend:   "curl-opa",
这个targetbackend的功能验证，只有默认的echoserver可以支持

2024-01-18 02:45 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/config.go
> +			Namespace:   namespace,
看下这里，如果没有配置namespace，就会去default命名空间下找了

2024-01-24 05:45 UTC, johnlanni requested changes

2024-01-24 05:45 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
为什么路由还要到opa服务，不能用echoserver吗。我理解opa服务只要在插件里去请求就可以了

2024-01-29 02:05 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
@baerwang 我看你又提交了一些修改，但这里不做修改的原因能说明一下吗

2024-01-29 14:14 UTC, baerwang commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
这是个e2e的例子，用户想要做什么操作，自己就去配置就可以了

2024-01-30 02:10 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
我的建议是参考其他认证插件的e2e，使用通用的ingress路由：
https://github.com/alibaba/higress/blob/e67ed481cfde66becbf22c418b4ea151bfecd2aa/test/e2e/conformance/tests/go-wasm-key-auth.yaml#L15-L33

这样对于opa认证通过的测试用例，应该expect返回200，现在是expect返回404，无法识别是路由正确了后端返回的404，或是网关找不到路由导致的404。

2024-01-30 02:15 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/README.md
> +| serviceSource | string | 必填   | -   | k8s,nacos,ip,route                   |
为route的意义不大，不会有路由目标服务是opa server的情况

2024-01-30 02:16 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/README.md
> +| host          | string | 非必填  | -   | 服务主机（serviceSource为`route`必填）        |
为ip的时候，一般也有可能要设置host，比如这个ip对应的是个nginx，需要根据host找virtualserver

2024-01-30 02:19 UTC, johnlanni commented
@baerwang 整体问题不大了，上面的修复建议调整后就可以合入。感谢🙏

2024-01-30 04:53 UTC, baerwang commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
都说了这是e2e的例子，为什么需要根据用户的场景来做？

2024-01-30 05:33 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/config.go
> +			ServiceName: serviceName,
这里不加host吗

2024-01-30 05:34 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/README.md
> +| host          | string | 非必填  | -   | 服务主机（serviceSource为`ip,route`必填）     |
也不是必填吧，配置了host就给client设置上，没有配置就不设host

2024-01-30 05:35 UTC, johnlanni commented on plugins/wasm-go/extensions/opa/README.md
> +| serviceSource | string | 必填   | -   | k8s,nacos,ip,route                   |
宿主机？route cluster的意思是用当前ingress路由的目标服务作为httpcall的的服务

2024-01-30 05:38 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.go
> +						StatusCode: stdHttp.StatusNotFound,
你看下这里用404状态码做expectResponse，无法区分是否路由生效呀，没有创建这个ingress的时候，请求这个路径也是返回404，这样的e2e 用例显然是不合理的。所以上面建议你把目标服务改掉。

2024-01-30 05:43 UTC, johnlanni commented on test/e2e/conformance/tests/go-wasm-opa.yaml
> +                name: opa
先不说e2e测试应该尽量使用用户常见的使用场景，从而才有真正的测试价值；
目前的核心问题是你现在expect 404的做法本身有歧义，假设后面逻辑发生变更，这里不再返回404，因为这里检测的是404，路由还没生效的时候返回的404就会直接检测成功。

2024-01-30 07:25 UTC, johnlanni approved these changes
LGTM

2024-01-30 07:29 UTC, merged