feat:add higress automatic https
alibaba/higress pull request #854
Opened 2024-03-01 12:33 UTC by 2456868764

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

现在是Preview版本，主要流程和功能完成
待完成：
1. configmap storage 分片
2. configmap storage UT
3. helm chart 
4. ci

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-03-05 09:58 UTC, johnlanni requested changes

2024-03-05 09:58 UTC, johnlanni commented on pkg/cert/config.go
> +}
当automaticHttps为false时，允许配置一个静态secret，用于这个域名的证书

2024-03-06 03:30 UTC, 2456868764 commented on cmd/cert/main.go
> +	if err := app.NewManagerCommand(ctx).Execute(); err != nil {
好的， 现在 certmagic solver token 是保存内存里，要是否可以解决这个问题，另外可以在 controller 启动参数加个开关项 比如  --enable-automatic-https?

2024-03-06 03:32 UTC, johnlanni commented on cmd/cert/main.go
> +	if err := app.NewManagerCommand(ctx).Execute(); err != nil {
嗯 可以的

2024-03-06 03:33 UTC, 2456868764 commented on pkg/cert/config.go
> +}
这里加静态secret配置，只是一个保存配置，不作任何处理？

2024-03-06 05:42 UTC, johnlanni commented on pkg/cert/config.go
> +}
用于控制此域名关联的ingress对应的证书

2024-04-15 03:44 UTC, zzjin commented
这个configmap,有可能考虑改成CRD的模式吗,配置在一个configmap里面,不同的域名的RBAC会比较难控制

2024-04-16 02:13 UTC, johnlanni commented
@zzjin 这个configmap我们不希望放到用户命名空间下，而是放在系统命名空间下（如:higress-system)，统一交由集群SRE来管理

2024-04-16 04:10 UTC, 2456868764 commented
> higress-https



> @2456868764 这个配置里的cert字段是否应该是higress的子字段比较合理

现在 cert 是保存新 higress-https configmap 里，是要保存到 higress-config configmap 里 higress 属性下？

2024-04-16 04:12 UTC, 2456868764 commented
> higress-https



> @2456868764 这个配置里的cert字段是否应该是higress的子字段比较合理

现在 cert 是保存新 higress-https configmap 里，是要保存到 higress-config configmap 里 higress 属性下？

2024-04-16 05:39 UTC, johnlanni commented
> > higress-https
> 
> > @2456868764 这个配置里的cert字段是否应该是higress的子字段比较合理
> 
> 现在 cert 是保存新 higress-https configmap 里，是要保存到 higress-config configmap 里 higress 属性下？

哦，独立出来也有好处，可以用hgctl简化运维

2024-04-16 05:50 UTC, johnlanni requested changes
似乎没有看到在将ingress转换为istio gateway资源时，根据此份configmap配置credential的逻辑？

2024-04-16 05:50 UTC, johnlanni commented on helm/core/values.yaml
> +      "name": "http",
name不能重复，得换一个名字

2024-04-16 05:52 UTC, johnlanni commented
> 似乎没有看到在将ingress转换为istio gateway资源时，根据此份configmap配置credential的逻辑？


https://github.com/alibaba/higress/blob/9c112a03db25f33f56dde3bc6019e335629955f1/pkg/ingress/kube/ingressv1/controller.go#L438-L441

@2456868764 即这段逻辑需要调整适配

2024-04-16 08:13 UTC, 2456868764 commented
> > 似乎没有看到在将ingress转换为istio gateway资源时，根据此份configmap配置credential的逻辑？
> 
> https://github.com/alibaba/higress/blob/9c112a03db25f33f56dde3bc6019e335629955f1/pkg/ingress/kube/ingressv1/controller.go#L411-L442
> 
> 
> @2456868764 即这段逻辑需要调整适配

好的，我修改一下

2024-04-21 01:52 UTC, 2456868764 commented
> > 似乎没有看到在将ingress转换为istio gateway资源时，根据此份configmap配置credential的逻辑？
> 
> https://github.com/alibaba/higress/blob/9c112a03db25f33f56dde3bc6019e335629955f1/pkg/ingress/kube/ingressv1/controller.go#L411-L442
> 
> 
> @2456868764 即这段逻辑需要调整适配

@johnlanni 已经适配，麻烦看一下

2024-04-22 01:52 UTC, johnlanni requested changes
能否添加一个e2e test，可以只验证static secret的方式，校验服务端返回的证书与配置的是否一致

2024-04-22 01:52 UTC, johnlanni commented on pkg/cert/config_test.go
> +package cert
少了license

2024-04-23 02:12 UTC, johnlanni requested changes
现在区分了ingressv1和ingress两个目录对应不同的ingress版本，除了 ingressv1， ingress目录下的controller也需要调整一下

2024-04-25 12:38 UTC, 2456868764 commented
> 现在区分了ingressv1和ingress两个目录对应不同的ingress版本，除了 ingressv1， ingress目录下的controller也需要调整一下

ingress & ingressv1 都修改，增加了 e2e test ,  另外配置在 higress-https 里 secret 应该在 higress-system namespace 下？

2024-04-28 01:50 UTC, johnlanni approved these changes
LGTM

2024-05-09 02:56 UTC, merged