add try-paths plugins
alibaba/higress pull request #902
Opened 2024-04-01 16:05 UTC by haifzhu

### Ⅰ. Describe what this PR did
add try-paths wasm go plugin to implement try_files function of nginx。

### Ⅱ. Does this pull request fix one issue?
Fix the issue: Add support of try_files usage #840

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
test cases be added in codes.

### Ⅳ. Describe how to verify it
enable the plugin on the route, and check its retry function on envoy log.

### Ⅴ. Special notes for reviews
no

2024-04-08 11:15 UTC, johnlanni commented
@haifzhu Please add an e2e test like this PR：https://github.com/alibaba/higress/pull/759/files#diff-e1bcf2918c10b3b1792f4d5bf4f8d46c92929572af2060964f566af2e45bc5da

2024-04-10 02:26 UTC, johnlanni requested changes

2024-04-10 02:26 UTC, johnlanni commented on plugins/wasm-go/extensions/try-paths/main.go
> +var defaultTimeout uint32 = 60000
默认60秒超时有点久，建议改成1秒，另外可以支持一下配置

2024-05-23 12:44 UTC, closed without merging

2024-12-16 05:39 UTC, johnlanni commented
@haifzhu 没注意这个PR为什么关闭了？

2024-12-16 05:45 UTC, haifzhu commented
这个插件用递归实现的，判错逻辑也不够，所以暂时关闭了，如果有需求可以再优化下。