feat: Add an AI-Proxy Wasm plugin for POC
alibaba/higress pull request #921
Opened 2024-04-23 02:26 UTC by CH3CHO

### Ⅰ. Describe what this PR did

Add an AI-Proxy Wasm plugin for POC.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-05-08 06:39 UTC, johnlanni requested changes

2024-05-08 06:39 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `contexts`  | array of object | 非必填  | -   | 配置目标 AI 服务提供商的信息 |
contexts描述要调整下

2024-05-08 06:39 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 域名和路由级配置
这个当前插件还不支持，可以后续再支持，文档里可以先去掉

2024-05-08 06:39 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 域名和路由级配置
后续如果要实现，可以参考下：https://github.com/alibaba/higress/blob/6577ae88226bfaccd00f29e94811c8000ffde8f0/plugins/wasm-go/extensions/basic-auth/main.go#L36

2024-05-08 06:39 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 使用通义千问配合纯文本上下文信息
是否增加一节纯做协议转换的配置示例

2024-05-08 13:28 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 域名和路由级配置
OK

2024-05-08 13:31 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `contexts`  | array of object | 非必填  | -   | 配置目标 AI 服务提供商的信息 |
Fixed

2024-05-08 13:32 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +### 使用通义千问配合纯文本上下文信息
Done

2024-05-09 02:27 UTC, johnlanni requested changes

2024-05-09 02:27 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `id`           | string                  | 必填   | -   | AI 服务提供商的唯一标识                                                  |
id是不是不用必填

2024-05-09 02:27 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `id`          | string | 必填   | -   | 上下文信息的唯一标识                       |
同上

2024-05-09 02:27 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +  - type: azure
这里配置格式是列表吗，看上面字段说明是object

2024-05-09 02:34 UTC, johnlanni requested changes

2024-05-09 02:34 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/main.go
> +func getApiName(path string) provider.ApiName {
这个是不是应该放到provider实现中，如果provider是openai，应该要支持所有API，例如embedding等。

2024-05-09 02:36 UTC, johnlanni requested changes

2024-05-09 02:36 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `token`        | string                  | 必填   | -   | 用于在访问 AI 服务时进行认证的令牌                                            |
token建议做成 array of string，请求时随机选择token

2024-05-09 02:42 UTC, johnlanni requested changes

2024-05-09 02:42 UTC, johnlanni commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `context`      | object                  | 非必填  | -   | 配置 AI 对话上下文信息                                                  |
建议增加个protocol字段，不配置时，使用提供商自身协议（直接透传，只是设置一下认证token），当配置为openai时，为当前实现的逻辑。

2024-05-13 01:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/README.md
> +| `context`      | object                  | 非必填  | -   | 配置 AI 对话上下文信息                                                  |
done

2024-05-13 01:57 UTC, CH3CHO commented on plugins/wasm-go/extensions/ai-proxy/main.go
> +func getApiName(path string) provider.ApiName {
OK

2024-05-14 08:59 UTC, johnlanni approved these changes
Great Work!

2024-05-14 09:00 UTC, merged